### ISSUE TITLE
Rendre le service dispo à l'URL projetdumois.fr

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#1]
J'ai ouvert le ndd, Adrien tu es admin coté OVH

**Comment by overflorian** [comment]
En testant aujourd'hui, le service n'est plus accessible sur projetdumois.fr

**Comment by PanierAvide** [comment]
Bizarre, _chez moi ça marche_ :thinking:

**Comment by overflorian** [comment]
OK ça fonctionne en effet sans le WWW. Tu peux créer cette redirection stp ?

**Comment by PanierAvide** [comment]
Théoriquement c'est bon désormais

**Comment by overflorian** [comment]
yes indeed. Merci
