### ISSUE TITLE
Afficher des stats de suivi d'évolution du mapping

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#10]
Il faudrait afficher des stats (tableau numérique + courbe graphique) :
- de l'intégration de données externes (exemple : % de cinémas mappés dans OSM par rapport à ceux présents dans une BDD externe (exemple : celle du CNC pour les cinémas))
- des tags améliorés durant le projet du mois.

Sachant qu'il y a 
- plusieurs tags importants à suivre
- que l'on rajoute souvent des tags en cours de projet
- que ces tags évoluent en cours de projet

_Use case :_
1. On veut intégrer les ref:FR:CNC aux cinémas en France : on affiche donc tous les cinémas avec ce tag : https://overpass-turbo.eu/s/VwT
Voir le tableau sur la page https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:CNC#Avancement

2. Par la suite, on se rend compte que certains cinémas n’apparaissent pas dans le fichier du CNC. Du coup on ajoute des ref:FR:CNC=no
Pour continuer à avoir des stats qui ont un sens, il faut donc exclure cette valeur : https://overpass-turbo.eu/s/VwV

En bonus, on pourrait afficher _ sur un même graphique_ ces différents indicateurs pour pouvoir les comparer.
En bonus ++, il devrait être facile de partager ces stats sur le wiki osm et sur les réseaux sociaux (et donc il faut que ça soit BEAU ;))

**Comment by overflorian** [comment]
en bonus +++ on pourrait avoir une évolution visuelle cartographique du mapping. 2 solutions :
-un "overpass to gif" automatique pour un résultat du genre :
![300px-Animation_mapping_cinémas](https://user-images.githubusercontent.com/11553211/85943328-af11c400-b92f-11ea-92af-486a95651551.gif)
-une timeline avec un slider déplaçable pour avancer / reculer dans le temps et voir l'évolution du mapping

**Comment by gendy54** [comment]
Hello,
Je ne sais pas si y a des trucs intéressants sur cette page: https://wiki.openstreetmap.org/wiki/Schwerpunkt_der_Woche
En tout cas, j'ai trouvé un truc sympa: https://osm.wikidata.link/ Poke @PanierAvide

**Comment by pyrog** [comment]
Pour les DAE, afficher le nombre de tags opening_jours=24/7 et les autres valeurs sous forme de 2 barres empilées (ou 2 aires si le graphisme montré l'évolution au cours du temps)

**Comment by overflorian** [comment]
Quelqu'un aurait une solution technique pour générer des cartes comme je l'ai proposé ci-dessus ? ça serait tellement mieux d'avoir un rendu visuel cartographique : on pourrait identifier les territoires les plus contributeurs en un clin d’œil.

**Comment by PanierAvide** [comment]
La solution technique on l'a plus ou moins, exemple https://docs.mapbox.com/mapbox-gl-js/example/timeline-animation/

Le truc c'est le temps de mettre en place ça, il faut modifier la gestion de la base pour avoir un avant/après.

**Comment by overflorian** [comment]
ok, bonne nouvelle.
D'après moi, ce n'est pas vraiment prio pour l'instant.

**Comment by pyrog** [comment]
Il y a probablement moyen d'automatiser ça avec un script et quelques
requêtes overpass.

Pour l'affichage, à tester avc une heatmap ou des effets de "lumières"
