### ISSUE TITLE
Tous les mots dièse ne sont pas détectés

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#102]
Cf. note [2397642](https://www.openstreetmap.org/note/2397642) et sur [NotesReview](https://ent8r.github.io/NotesReview/expert/?query=%23scubadiving%20%23projetdumois&limit=10&closed=true)

<img width="244" alt="Capture d’écran 2020-10-24 à 13 28 35" src="https://user-images.githubusercontent.com/2158081/97080600-da19d500-15fc-11eb-84f3-9f1679027460.png">

**Comment by PanierAvide** [comment]
Corrigé, ce sera déployé dans la journée
