### ISSUE TITLE
Gestionnaire de notes : homogénéiser l'interface graphique

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#103]
Utiliser aussi des glissières à la place des cases à cocher.

<img width="33%" valign=top alt="Liste" src="https://user-images.githubusercontent.com/2158081/97080738-f79b6e80-15fd-11eb-9d03-f402bac5abfa.png"> <img width="33%" valign=top alt="Carte" src="https://user-images.githubusercontent.com/2158081/97080715-ccb11a80-15fd-11eb-88dd-458db9d95274.png">

**Comment by PanierAvide** [comment]
Je ferme ce ticket là aussi, ça va aller dans #105 avec un affichage fond rempli/pas rempli.
