### ISSUE TITLE
Gestionnaire de notes : regrouper les badges

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#104]
Prêts à intégrer est affiché sous forme de badge.
Il devrait se trouver au début de la liste des badges.

<img width="33%" valign=top alt="Liste" src="https://user-images.githubusercontent.com/2158081/97080738-f79b6e80-15fd-11eb-9d03-f402bac5abfa.png">

**Comment by PanierAvide** [comment]
Je ferme celui-là car la proposition graphique de #105 résoudrait ce ticket également.
