### ISSUE TITLE
Améliorer la liste des filtres du gestionnaire de notes

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#105]
Des badges contenant les auteurs des "notes" pourraient être ajoutés côte à côtes (au cas où il y en aurait beaucoup).
Dans le second essai, les badges sont **triés** par ordre alphabétique et le nombre **d'occurrences** est affiché.

<img width="33%" valign=top alt="Badges auteurs" src="https://user-images.githubusercontent.com/2158081/97081376-5ebb2200-1602-11eb-962b-dfc768d4b7df.png">  <img width="33%" valign=top alt="Capture d’écran 2020-10-24 à 14 31 21" src="https://user-images.githubusercontent.com/2158081/97081864-99728980-1605-11eb-9b47-0b07def98bcb.png">

**Comment by PanierAvide** [comment]
Cette proposition de disposition des badges me plaît bien, il faut lui ajouter :
- L'interactivité des badges : 2 états activé/désactivé qui se manifeste par le remplissage ou non du fond du badge
- L'affichage de tous les filtres proposés sous forme de badges (photo et anonymes)

**Comment by overflorian** [comment]
Je suis chaud pour tes propositions. Rien à redire.

**Comment by PanierAvide** [comment]
Ajouté, ce sera déployé dans la journée
