### ISSUE TITLE
Open the service in UK

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#106]
To do:
* [ ] Translate our documentation
* [ ] Help UK community set-up their server (domain name, database, website)
* [ ] Make website code translatable
* [ ] Translate fully website in English

**Comment by PanierAvide** [comment]
Haven't we decided that the UK community has to do that ? Except translation of course because it needs rework of website code, but this is being done (I started yesterday).

**Comment by PanierAvide** [comment]
@overflorian Maybe you can help on translating documentation ? Mainly README.md (might be in both French and English) and DEVELOP.md (can be only in English)

**Comment by overflorian** [comment]
I translated the README.md, @PanierAvide can I please leave you with DEVELOP.md?

**Comment by rouelibre1** [comment]
I'm happy to help with the website's translation in English (just asked for permission to access the project on transifex @PanierAvide I believe you are the one who can accept the request ?)

**Comment by PanierAvide** [comment]
You should have the right to edit on Transifex, but let me know if it's not the case already.

**Comment by pyrog** [comment]
Do you have a link to the project on Transifex ?😉

**Comment by rouelibre1** [comment]
@PanierAvide I'm stuck, found the project and sent a request to help with English translation but it seems to be pending approval.
@pyrog https://www.transifex.com/openlevelup/projetdumoisfr/ Found it by searching on the site, the search icon is not obivous, it looks like this 

![image](https://user-images.githubusercontent.com/73238613/99388945-9dc55600-28d6-11eb-9fd1-21be33838b8d.png) 

next to your profile picture in the menu.

**Comment by PanierAvide** [comment]
@rouelibre1 There was in fact a request waiting for approval, but not where I expected so that's why I missed it, sorry for that. It should be OK now.
