### ISSUE TITLE
Projet du mois de décembre : lieux de dépistage Covid19

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#107]
à faire :

- [X] créer les badges
- [X] écrire un descriptif
- [ ] définir les tags
- [ ] [créer la page wiki](https://wiki.openstreetmap.org/wiki/FR:Project_of_the_month/Centres_de_d%C3%A9pistage_Covid) et la compléter
- [ ] configurer le site
- [ ] importer les données dispos en open data

**Comment by overflorian** [comment]
Je viens de créer les badges : [badge-test-covid.zip](https://github.com/vdct/ProjetDuMois/files/5440675/badge-test-covid.zip)

![badge-test-covid](https://user-images.githubusercontent.com/11553211/97212950-565d1580-17c1-11eb-967f-7b403222c39f.png)
![badge-test-covid-mini](https://user-images.githubusercontent.com/11553211/97212958-58bf6f80-17c1-11eb-875b-f2f2eb2cd313.png)

**Comment by PanierAvide** [comment]
Pour le site, si quelqu'un a moyen de faire un descriptif plus ou moins long (qui va apparaître sur l'accueil) dans le modèle de celui-ci ce serait chouette : https://github.com/vdct/ProjetDuMois/blob/master/projects/2020-09_aed/howto.md

**Comment by overflorian** [comment]
L'objectif est d'identifier dans OpenStreetMap un maximum de lieux où il est possible de faire un test Covid-19. Pour cela, il y a deux façons principales de participer :
- Parcourir votre quartier ou votre ville et trouver des lieux de dépistage : centres de santé, laboratoires d'analyse médicale ... Attention : il ne faut prendre en compte que les lieux permanents. Les centres de tests temporaires comme par exemple les tentes ne sont pas concernés.
- Vérifier et intégrer les hôpitaux, cliniques, centres de santé, laboratoires d'analyse médicale ... listés sur la carte : ceux-ci sont extraits de bases officielles (Ministère de la santé) mais peuvent être positionnés approximativement. Sur la base de votre connaissance locale ou de visites terrain, ajoutez-les dans OSM.

**Comment by PanierAvide** [comment]
Je ferme le ticket comme le sujet est passé à la trappe, ne pas hésiter à rouvrir si besoin.
