### ISSUE TITLE
Indiquer clairement les sources Osmose

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#108]
Dans le projet des défibrillateurs on a parfois des POIs rouges (osmose) en doublon.
Ils proviennent en fait de plusieurs sources.

Exemple : DAE du [gymnase Saint-Florent à Strasbourg](https://projetdumois.fr/projects/2020-09_aed/map#map=18.39/48.591728/7.719323)

<img width="25%" alt="Gymnase Saint-Florent" src="https://user-images.githubusercontent.com/2158081/97689339-b42c7e80-1a9b-11eb-8c00-ecb0f53632ae.png">

- [Direction Générale de la Santé](http://osmose.openstreetmap.fr/fr/error/47803fb6-26a0-44a3-ba8b-8f6615070d9b) (GeoDAE)
- [data.gouv.fr:Service Départemental d'Incendie et de Secours du Bas-Rhin](http://osmose.openstreetmap.fr/fr/error/38b83ec0-303a-1339-0e8c-c5c70d851625) (SDIS 67)

**Comment by PanierAvide** [comment]
Plus un problème à gérer côté Osmose.
