### ISSUE TITLE
Icônes manquantes dans le style vectoriel liberty

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#109]
À [Vaxoncourt]( https://projetdumois.fr/projects/2020-09_aed/map#map=17.88/48.291884/6.411729) l'église est affichée mais pas la mairie.
<img width="50%" alt="Vaxoncourt" src="https://user-images.githubusercontent.com/2158081/97775146-aab81a80-1b5e-11eb-906f-0e02453e3826.png">

La console javascript affiche le message suivant :
`[Warning] Image "town_hall_11" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event. (mapbox-gl.js, line 31)`

D'après [maputnik/osm-liberty/README.md#usage](https://github.com/maputnik/osm-liberty/blob/gh-pages/README.md#usage), il faut :
* Soit une clé d'accès au Cloud Maptiler pour accéder aux glyphs
* Soit héberger une copie

Dans tous les cas la ligne [osm-libertystyle.json#L24](https://github.com/maputnik/osm-liberty/blob/b6f0920d556afb95a9e73a40a0c075acceb75e1b/style.json#L24) doit être mise à jour.
```json
  "glyphs": "https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key={key}",
```

**Comment by pathmapper** [comment]
Salut a tous! Le symbole de la mairie est fixé par https://github.com/maputnik/osm-liberty/pull/89.

**Comment by pyrog** [comment]
@pathmapper tu es francophone ?
