### ISSUE TITLE
Open the service in Switzerland

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#111]
Once our service will be available in English (see https://github.com/vdct/ProjetDuMois/issues/106) @chnuessli will translate it into German and will fork and install a Switz instance on his own server. He is aware that he needs a vector tile server.
Good news!

**Comment by chnuessli** [comment]
We discussed this yesterday on our monthly meeting. Some people seems to be interested to start this in Switzerland. Maybe we have to clarify how much effort you want to put in this. But overall, we find it very interesting.

Things that must be clarified before the start.
- Who will be attending (one person is no person, we need to put the work on different shoulders)
- How much effort do you have to put in before the start
- Can we go with the already hosted website, by the french community
- Will it be expandable to germany with the same instance, like the swiss?

**Comment by overflorian** [comment]
Hi @chnuessli, that's a good news, thanks for the feedback.

On our side, @pyrog is helping with the translation. Maybe @pyrog you'd like to give an update? When the service will be available in English according to you?

We decided not to open the french instance to other countries, sorry. Therefore you'll need a proper install. I believe it could work for Swiss + Germany on the same instance without any problem, but @PanierAvide may have a more precise opinion than mine.

**Comment by rouelibre1** [comment]
If you need some help with translations, I can jump in to speed things up.

**Comment by overflorian** [comment]
That's great, thanks @rouelibre1 ! The first file to translate would be this one please https://github.com/vdct/ProjetDuMois/blob/master/DEVELOP.md 
For the next steps, maybe @pyrog or @PanierAvide could help?

**Comment by rouelibre1** [comment]
@overflorian I'm done. I just need a little help on how to share the file properly (I'm not used to github)

**Comment by pyrog** [comment]
Sorry, I didn't took time on this project.

You could email me your file to first.last@gmail.com. (My real name is there: https://github.com/pyrog)

**Comment by rouelibre1** [comment]
@pyrog ok, it's done

**Comment by sfkeller** [comment]
Just a question: 
Seems that it's not ready yet to be translated to german an italian, isn't it?
How do you plan introduce i10n in this nice project (e.g. using Transifex)?

**Comment by pyrog** [comment]
I @sfkeller. I don't have rights on the project and Transifex.

I suggest that you translate directly from [en.json](https://github.com/vdct/ProjetDuMois/blob/b6acec95d5a39fd7bd8a1163d9bd62ab40d94998/website/locales/).
Copy it to de.json, keep french "keys" (left part) and add german strings (right part).

Keep in mind that the native language is french, but you could read both english and french to find the better german translation.

```son
{
	"Catalyseur d'énergies pour OpenStreetMap": "Energy catalyst for OpenStreetMap",
	"Projet du mois OpenStreetMap": "OpenStreetMap Project of the Month",

```

**Comment by sfkeller** [comment]
Voilà! Here's the german translation (thanks to Peter Berger!):
[de.json.zip](https://github.com/vdct/ProjetDuMois/files/5605117/de.json.zip)

**Comment by chnuessli** [comment]
Hallo @sfkeller, i've created a pull request for the preparation to the german site.
https://github.com/vdct/ProjetDuMois/pull/114

**Comment by overflorian** [comment]
Great! Could you please translate the following tweet for me?

"Projet du mois is now available in Switzerland 🇨🇭! In French, English and German"

What would be the URL used? Thanks

**Comment by sfkeller** [comment]
@overflorian We are really only just in the preparation phase. So nothing to tweet yet :-(.

We now need more instructions, 1. about how to implement a projet and 2. how to install an own instance and 3. how to test the whole thing - besides clarifing here, where to put the instance - and who is willing to contribute in this whole work.

**Comment by overflorian** [comment]
I know we are not ready yet. I let you guys finish before tweeting.

**Comment by sfkeller** [comment]
Though neither a committed volunteers here, nor an instance is yet ready, it seems to be possible for us - at least for me - to prepare some projects.

Can someone point me to a good example and to some instructions about how to specify a project?

**Comment by sfkeller** [comment]
J'ai trouvé quelques trucs et j'ai créé des pages Wiki ici: https://wiki.openstreetmap.org/wiki/FR:Project_of_the_month_Switzerland

@PanierAvide: Pourrais-tu nous donner quelques conseils afin que nous puissions installer une instance du projetdumois code sur un de nos serveurs et tester un "projet du mois" (par exemple Défis)?

**Comment by PanierAvide** [comment]
Tous les détails pour installer le service sont ici : https://github.com/vdct/ProjetDuMois/blob/master/DEVELOP.md

Je peux compléter si besoin en fonction des questions précises qui pourront arriver lors de l'installation.

**Comment by sfkeller** [comment]
Supposons que nous voulions tester le projet "2020-09_aed": que devons-nous faire pour indiquer à l'application d'afficher le projet "2020-09_aed" (éventuellement renommé en "2021-02_aed")?

**Comment by PanierAvide** [comment]
Par défaut, le projet qui s'affiche est celui dont les dates dans les fichiers `info.json` correspondent. Donc pour avoir le projet AED, il faut modifier `start_date` et `end_date` dans `info.json` pour que la date du jour soit incluse dans l'intervalle.

**Comment by sfkeller** [comment]
Encore une question : comment rendre le howto.md bilingue ou multilingue? https://github.com/vdct/ProjetDuMois/blob/master/projects/2020-09_aed/howto.md
Nous pourrions faire une section par langue DE, FR, EN. 
Mais existe-t-il un mécanisme plus sophistiqué?

**Comment by PanierAvide** [comment]
Pas d'actuellement implémenté non, même si on pourrait imaginer un système avec des suffixes ou préfixes de code langue. Le plus simple va être une section par langue pour l'instant.

**Comment by rouelibre1** [comment]
I translated DEVELOP.md in english and shared it with @pyrog 
@PanierAvide have you received the file from him too ? I can share it here it's it's useful to anyone, but not sure how to do it

**Comment by sfkeller** [comment]
@rouelibre1 Many thanks. 
That translation to english would be helpful.
Actually it your be optimal, if this file would be published - and maintained - at main branch:, e.g. as 
https://github.com/vdct/ProjetDuMois/blob/master/DEVELOP_en.md (or similar).

**Comment by pyrog** [comment]
@rouelibre1 The file is in #113 😃

**Comment by rouelibre1** [comment]
Oh that's right thank you. What would be the next step ?

**Comment by chnuessli** [comment]
I created a pull request for the german aed project to prepare our first project of the month. https://github.com/vdct/ProjetDuMois/pull/116

**Comment by chnuessli** [comment]
Dear fellow translators
as @PanierAvide is correct, we should continue on our own german repo. I propose we will follow it here: https://github.com/chnuessli/ProjetDuMois

**Comment by PanierAvide** [comment]
Hi, I don't know if you're still interested in opening an instance in Switzerland, but internationalization has been released today so UI can be translated.

**Comment by PanierAvide** [comment]
No news, closing the issue.

**Comment by sfkeller** [comment]
@PanierAvide : Thanks for reaching out.

There are actually still plans around to implement a ProjetDuMois. See https://wiki.openstreetmap.org/wiki/FR:Project_of_the_month_Switzerland 

But we decided to implement it on a different software stack, which is based on basic building blocks, which can be reused for other purposes. See https://github.com/sosm/osmhistorydb-ch/wiki . 

So we're still interested in exchanging ideas!

**Comment by PanierAvide** [comment]
Thanks for your feedback, great to hear that you're still working on this topic. Note that with work of @flacombe, you can now plug ProjetDuMois website on an existing OSM database, see https://github.com/vdct/ProjetDuMois/blob/master/DEVELOP.md#disable-imposm3-usage

**Comment by sfkeller** [comment]
Interesting to see.
The currently planned front end will bei Apache Superset.
But this could be replaced with ProjetDuMois.
Will there be a docker config. available for this ProjetDuMois?

**Comment by PanierAvide** [comment]
It's not planned as now, but we may create a Docker config if that could help you.
