### ISSUE TITLE
Eléments non rendu

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#112]
Le polygone de la [mairie](https://www.openstreetmap.org/way/240205297) n'est pas affiché dans [PdM](https://projetdumois.fr/projects/2020-09_aed/map#map=18.69/46.7549897/5.6115611) alors qu'il est parfaitement visible dans [Maputnik](https://maputnik.github.io/editor/#17.64/46.754982/5.611741/18.2) avec le style OSM Liberty.
<img width="25%" alt="PdM" src="https://user-images.githubusercontent.com/2158081/98778442-a7405100-23f2-11eb-984a-fd94882c0c6b.png"> <img width="25%" alt="Maputnik" src="https://user-images.githubusercontent.com/2158081/98778735-0f8f3280-23f3-11eb-9d8e-11c6a0903a4a.png">

**Comment by pyrog** [comment]
[église de Carentoir](https://projetdumois.fr/projects/2020-09_aed/map#map=17.39/47.817008/-2.133894)

<img width="33%" alt="église Carentoir" src="https://user-images.githubusercontent.com/2158081/101977062-2c659280-3c4b-11eb-9cc9-2612339c2cde.png">

**Comment by pyrog** [comment]
Terrains de sport dans [PdM](https://projetdumois.fr/projects/2020-09_aed/map#map=17.11/47.724911/-3.330596)  et dans [Maputnik](https://maputnik.github.io/editor/#17.07/47.72504/-3.329766) en vue inspection.
<img width="33%" valign="top" alt="Projet du Mois" src="https://user-images.githubusercontent.com/2158081/101977276-d4c82680-3c4c-11eb-90b5-b8f6e9ccdd14.png"> <img width="33%" alt="Maputnik" src="https://user-images.githubusercontent.com/2158081/101977286-f32e2200-3c4c-11eb-8c54-ef5269e3763c.png">

**Comment by pyrog** [comment]
Cimetière dans [PdM](https://projetdumois.fr/projects/2020-09_aed/map#map=17/47.72471/-3.33599), dans [Maputnik](https://maputnik.github.io/editor/#17/47.72471/-3.33599) et dans le rendu [osm standard](https://www.openstreetmap.org/#map=17/47.72471/-3.33599)

Ici ce n'est pas un problème de style mais de tuiles vectorielles qui ne contiennent pas les cimetières.

**Comment by PanierAvide** [comment]
@frodrigo

**Comment by overflorian** [comment]
Tant qu'on est sur les cimetières, je suggère de rendre les surfaces et les names des cemetery=sector comme dans OSMontrouge cf. https://osmontrouge.fr/@48.822474,2.319080,17.30
Exemple d'objet https://www.openstreetmap.org/way/666033635

**Comment by frodrigo** [comment]
Le schéma de données des tuiles est celui du projet OpenMapTiles (et le même que MapTiller).

Les cimetières sont définis dans landuse https://openmaptiles.org/schema/#landuse

Si c'est chez MapTiler mais pas sur le serveur de tuiles osm-fr, là par contre il y a un bug.

Les isgalement ne sont pas à remonter à PDM, mais à
* Si problème avec le serveus ou ces tuiles https://github.com/osm-fr/infrastructure/issues
* Si problème ave les mise à jour des tuiles https://github.com/makina-maps/makina-maps
* Si problème avec le schéma des tuiles https://github.com/openmaptiles/openmaptiles
* Si problème avec le style, voir projet github du style

**Comment by pyrog** [comment]
Il doit y avoir un peu de tout : style mais aussi un problème de génération de tuiles (cf. #117).

Dans le style il y a aussi l'ordre Z des rues, mais je ne sais plus si j'ai fait un ticket.

**Comment by pyrog** [comment]
Les [bâtiments non rendus](https://projetdumois.fr/projects/2020-09_aed/map#map=17.93/47.81931/-2.132216) sont en rouge dans la copie d'écran de JOSM.

<img valign=top width="33%" alt="Projet du Mois" src="https://user-images.githubusercontent.com/2158081/101985149-82a3f700-3c86-11eb-9c08-d96bc9bbc9b1.png"> <img valign=top width="33%" alt="Maputnik" src="https://user-images.githubusercontent.com/2158081/101985171-a49d7980-3c86-11eb-8880-4a072f5846c8.png">  <img valign=top width="33%" alt="JOSM" src="https://user-images.githubusercontent.com/2158081/101985217-f0502300-3c86-11eb-97c7-b220bcea00fd.png">

**Comment by pyrog** [comment]
Autre exemple : [Super U de Carentoir](https://projetdumois.fr/projects/2020-09_aed/map#map=18/47.808727/-2.128767).

Le [bâtiment](https://www.openstreetmap.org/way/360231933) (en bleu) n'est pas affiché : il a 2 tags principaux.
```
building=yes
shop=supermarket
```
<img width="33%" alt="PdM" src="https://user-images.githubusercontent.com/2158081/101986245-314b3600-3c8d-11eb-8f48-26eb9868e984.png"> <img width="33%" alt="JOSM" src="https://user-images.githubusercontent.com/2158081/101986241-27293780-3c8d-11eb-8987-b45a50db4252.png">

**Comment by PanierAvide** [comment]
Je ferme le ticket comme ça ne concerne pas le code de projetdumois.

**Comment by pyrog** [comment]
> ça ne concerne pas le code de projetdumois.

Certes, mais tant que le problème n'est pas réglé en amont, PdM n'est pas "fiable" 😞 
Je suggère de laisser ces tickets ouverts et de mettre une étiquette "rendu vectoriel".

https://www.openstreetmap.org/relation/11634124 non rendu
(3 polygones dans une relation multipoligone avec un tag building)

<img width="33%" alt="Capture d’écran 2020-12-25 à 09 27 51" src="https://user-images.githubusercontent.com/2158081/103127875-79a62300-4693-11eb-9ff0-8020fc4200ed.png">

Le bâtiment est visible dans Maputnik avec les styles Brigth et Liberty. Il s'agit probablement d'un problème de génération de tuiles cf. #117

**Comment by frodrigo** [comment]
Ici, ça n'a aucune chance d'être traité. Reporte ça au bon projet. C'est un sujet que tu connais, tu peux en plus identifier le problème et le projet qui va bien.

**Comment by frodrigo** [comment]
F12 pour savoir d'où ça vient.

**Comment by pyrog** [comment]
F12 dans Safari ne fonctionne pas 😉 
Dans Chrome ça m'affiche les requêtes réseau.

Je vois que les tuiles sont bien chargées, mais ça ne me dit pas si le polygone se trouve dans la tuile ou pas.

**Comment by pyrog** [comment]
### Tuiles MapTiler
https://maputnik.github.io/editor/#19.58/45.9189404/6.0909044
https://api.maptiler.com/tiles/v3/14/8469/5834.pbf?key=KDhMfHvorAFkFe64wlZb


Chargement des tuiles MapTiler dans Maputnik : https://api.maptiler.com/tiles/v3/tiles.json?key={key}
<img width="33%" alt="Capture d’écran 2020-12-25 à 15 48 42" src="https://user-images.githubusercontent.com/2158081/103137373-b6404180-46c8-11eb-8a14-163cf62b7ae2.png">

Affichage en mode "inspect" : le polygone du bâtiment est présent 😃 
<img width="33%" alt="Capture d’écran 2020-12-25 à 15 51 21" src="https://user-images.githubusercontent.com/2158081/103137413-133bf780-46c9-11eb-96d0-8fe6b14cabbf.png">

### Tuiles OpenStreetMap France
https://projetdumois.fr/projects/2020-09_aed/map#map=19.58/45.9189404/6.0909044
https://tile-vect.openstreetmap.fr/data/v3/14/8469/5834.pbf

Chargement des tuiles OSM France dans Maputnik : https://tile-vect.openstreetmap.fr/data/v3.json
<img width="33%" alt="Capture d’écran 2020-12-25 à 15 45 43" src="https://user-images.githubusercontent.com/2158081/103137331-59448b80-46c8-11eb-8ce5-1e92cef08f2c.png">

Affichage en mode "inspect" : le polygone du bâtiment est absent 😞 
<img width="33%" alt="Capture d’écran 2020-12-25 à 15 44 27" src="https://user-images.githubusercontent.com/2158081/103137313-31edbe80-46c8-11eb-8aea-31cef15c1440.png">

**Comment by pyrog** [comment]
> Terrains de sport dans [PdM](https://projetdumois.fr/projects/2020-09_aed/map#map=17.11/47.724911/-3.330596) et dans [Maputnik](https://maputnik.github.io/editor/#17.07/47.72504/-3.329766) en vue inspection.

https://github.com/maputnik/osm-liberty/issues/91

**Comment by pyrog** [comment]
> Cimetière dans [PdM](https://projetdumois.fr/projects/2020-09_aed/map#map=17/47.72471/-3.33599), dans [Maputnik](https://maputnik.github.io/editor/#17/47.72471/-3.33599) et dans le rendu [osm standard](https://www.openstreetmap.org/#map=17/47.72471/-3.33599).

`amenity=grave_yard` absent. Cf. https://github.com/openmaptiles/openmaptiles/issues/1057

**Comment by pyrog** [comment]
> Tant qu'on est sur les cimetières, je suggère de rendre les surfaces et les names des cemetery=sector comme dans

Ticket à ouvrir dans [OpenMapTiles](https://github.com/openmaptiles/openmaptiles)

**Comment by overflorian** [comment]
Hello,
Je constate encore pas mal de blanc sur la carte, c'est très génant pour bien positionner les POIs.

Et si on faisait un petit point des éléments qui sont maintenant bien ou mal rendus et de l'avancement des issues que l'on a fait upstream. @pyrog ?

**Comment by frodrigo** [comment]
Je n'ai pas encore déployé la correction.
