### ISSUE TITLE
Implémenter des skeletons

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#115]
Dans la catégorie "nice to have" : afin de faire croire à l'utilisateur que le temps de chargement des notes est plus court, il suffit d'afficher des "skeletons" à la place de la roue de chargement. 
Comme par exemple pour YouTube ou Pinterest :
![image](https://user-images.githubusercontent.com/11553211/100542090-5761e680-3248-11eb-9261-0af3f5e77eb0.png)
Dans l'idéal, le bon nombre de colonne est affiché en skeleton.
Idée trouvée sur https://www.ux-republic.com/top-3-des-elements-ui-a-ne-pas-oublier-dans-votre-conception/

**Comment by PanierAvide** [comment]
C'est fait et en prod

**Comment by overflorian** [comment]
C'est du lourd ! Merci
