### ISSUE TITLE
Élément non généré dans les tuiles

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#117]
La [maison des associations](https://www.openstreetmap.org/way/251413338) ne semble pas générée dans les tuiles du [Projet du Mois](https://projetdumois.fr/projects/2020-09_aed/map#map=19.01/47.8171197/-2.1324852&sidebar=).

C'est un polygone `building=yes` qui n'est pas affiché, alors que les bâtiments similaires à côté le sont.
Ce polygone est bien présent dans les tuiles utilisées par [Maputnik](https://maputnik.github.io/editor/#18.67/47.8170502/-2.1328399).

Voir aussi #112.

**Comment by pyrog** [comment]
Idem pour l'[Hôpital de Carentoir](https://www.openstreetmap.org/way/251415822/history#map=19/47.81828/-2.13331). L'[extrémité du bâtiment](https://www.openstreetmap.org/way/251416363) est bien affichée.
Polygone `building=hospital` visible dans [Maputnik](https://maputnik.github.io/editor/#19/47.81828/-2.13331) mais pas dans [PdM](https://projetdumois.fr/projects/2020-09_aed/map#map=19/47.81828/-2.13331).
<img width="33%" alt="Capture d’écran 2020-12-12 à 08 41 16" src="https://user-images.githubusercontent.com/2158081/101978523-cfbba500-3c55-11eb-8d1d-c46f32816291.png"> <img width="33%" alt="Capture d’écran 2020-12-12 à 08 41 46" src="https://user-images.githubusercontent.com/2158081/101978527-e06c1b00-3c55-11eb-9c25-fa51a83a2a4c.png">

Ces deux polygones ont les mêmes propriétés d'après la vue inspection de Maputnik.
<img width="261" alt="Capture d’écran 2020-12-12 à 08 38 34" src="https://user-images.githubusercontent.com/2158081/101978460-6e93d180-3c55-11eb-9266-7dea9191ae72.png">

**Comment by PanierAvide** [comment]
@frodrigo

**Comment by PanierAvide** [comment]
Je ferme le ticket, ça n'est pas du ressort de projetdumois, cf https://github.com/vdct/ProjetDuMois/issues/112#issuecomment-743728299
