### ISSUE TITLE
Ordre d'affichage incorrecte des couches highway

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#118]
[Exemple](https://projetdumois.fr/projects/2020-09_aed/map#map=18.79/47.8182017/-2.1327794)
<img width="33%" alt="Capture d’écran 2020-12-12 à 14 18 54" src="https://user-images.githubusercontent.com/2158081/101985003-605da980-3c85-11eb-8a47-811dcda9fc76.png">

**Comment by PanierAvide** [comment]
Je ferme le ticket, ça n'est pas du ressort de projetdumois, cf https://github.com/vdct/ProjetDuMois/issues/112#issuecomment-743728299
