### ISSUE TITLE
Osmupdate : osh file has no timestamp

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#124]
Lors de l'update des données via le script 09_project_update_tmp.sh, osm update affiche le message 
`osmupdate: file /data/files/pdm/france-internal.latest.osh.pbf has no file timestamp.`

osmupdate execute ensuite son opération statistics pour déterminer la date du fichier qui dure plusieurs minutes  
N'y aurait-il pas un moyen de garder le timestamp dans un fichier à coté pour l'éviter ?

Je ne connais pas osmupdate si bien que, ça je le garde dans un coin de ma tête pour regarder

**Comment by PanierAvide** [comment]
Si tu trouves je suis clairement preneur, j'avais rapidement creusé mais pas trouvé grand chose...

**Comment by flacombe** [comment]
Sur cette page : https://wiki.openstreetmap.org/wiki/Osmupdate#Updating_OSM_Files

On voit qu'ils ajoutent le timestamp entre les deux noms de fichier dans la ligne de commande.
`osmupdate old_file.pbf 2020-12-22 13:00:00Z new_file.pbf`

Ainsi à l'init on n'a pas de moyen de le savoir, mais on pourrait le connaître depuis la dernière update ?

**Comment by PanierAvide** [comment]
C'est sûr, il faut prévoir de le stocker entre deux mais sur le principe oui.

**Comment by flacombe** [comment]
PdM fonctionne avec --day, ainsi pas la peine d'avoir la date exacte H-1 par rapport à la dernière exécution suffit.

Je te fais ça tout de suite ;)

**Comment by PanierAvide** [comment]
Si tu as moyen de regarder pour la mise à jour des `features` aussi... :smile:

**Comment by flacombe** [comment]
Sans problème, à quel problème penses-tu ?

**Comment by PanierAvide** [comment]
C'est le même problème, quand on fait tourner osmupdate dans `21_features_update_tmp.sh` (généré par `20_features_update.js`), osmupdate recherche dans le fichier le timestamp le plus récent.

**Comment by flacombe** [comment]
Ah oui un problème que je n'ai pas avec imposm désactivé.
Ok je fait ca en même temps, wait for it

**Comment by flacombe** [comment]
A clore
