### ISSUE TITLE
Osmium : Unknown command or option 'tags-count'

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#127]
Mon package osmium 1.10.0 n’expose pas la commande tags-count dans l'help.
Elle est utilisée dans le code, d'où vient-elle ?

**Comment by PanierAvide** [comment]
C'est dans la version master : https://docs.osmcode.org/osmium/master/osmium-tags-count.html

Sur mon poste c'est une 1.12.1, compilée depuis le dépôt Git sur la base des instructions qu'on peut retrouver pour installer GéoDataMine ici https://framagit.org/PanierAvide/GeoDataMine

**Comment by flacombe** [comment]
Merci à toi pour l'écriture de cette procédure, que j'ai réussi à conduire jusqu'au bout sans erreur et du 1er coup !

Tests réalisés, ca fonctionne
