### ISSUE TITLE
Execution des recomptages passés non nécessaire dans project:update

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#128]
Actuellement, le script de recomptage liste tous les jours d'un projet pour exécuter un dénombrement par jour. Chaque jour voit l’exécution des comptages de tous les jours précédents mais cela ne me semble pas nécessaire.

Ne vaudrait-il pas mieux déterminer la plage de jours à dénombrer entre la date courante et le timestamp ayant servi de point de départ pour le refresh de l'OSH?
On s’économiserait la requête DELETE vidant les comptage existants pour un projet, n'est-ce pas ?

Je propose ceci dans l'idée d'avoir plusieurs comptages pour un projet, ce qui pourrait devenir couteux de tout refaire chaque jour même si ce n'est pas un problème dimensionnant aujourd'hui

**Comment by PanierAvide** [comment]
C'est sûr qu'il y a matière à optimiser. Ça n'a pas été fait car la démarche de mise en place était assez expérimentale, nécessitant un traitement par lot de bout en bout. Ça vaudrait le coup de laisser la possibilité malgré tout de pouvoir tout recompter (à travers un paramètre lors de l'exécution ?) pour faciliter la maintenance ou le rechargement en cas d'erreurs.

**Comment by flacombe** [comment]
C'est évidemment nécessaire.
Le recomptage complet serait facilement possible en supprimant le fichier WORK_DIR/osh_timestamp ajouté pour osmupdate. En son absence, on prendrait la date de début de chaque projet par défaut.

**Comment by PanierAvide** [comment]
Ça me va, si c'est bien documenté sur la façon de re-générer les stats dans leur intégralité.

**Comment by PanierAvide** [comment]
Merci pour la PR ;)
