### ISSUE TITLE
Sommer les résultats de osmium tags-count dans project:update

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#129]
osmium tags-count semble renvoyer autant de ligne qu'il trouve combinaisons clé/valeur.
Certains projets peuvent nécessiter de définir des filtres comme building=* ou power=pole,tower provoquant une sortie multiligne d'osmium.

Il faut adapter le script project:update autour de la ligne 190 de sorte à ce que nbday prenne la somme de toutes les lignes.

**Comment by PanierAvide** [comment]
Pour reproduire ce comportement, qu'est-ce que tu as mis comme configuration dans `info.json` ?

**Comment by flacombe** [comment]
Le fichier est ici : 
https://github.com/flacombe/ProjetDuMois/blob/feature/enedis/projects/2021-01_poteaux/info.json

**Comment by PanierAvide** [comment]
Le commit mentionné devrait résoudre le problème :wink:
