### ISSUE TITLE
Lien vers la home dans le header

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#13]
Dans le header flottant, avant le menu "Participer / statistiques / Données", on pourrait rajouter le logo rond qui renvoi vers la home, de la même taille taille que le texte :

![logo-projet-du-mois-rond](https://user-images.githubusercontent.com/11553211/89789390-d22fb600-db20-11ea-8a7b-857521121d38.png)

**Comment by PanierAvide** [comment]
Visible en permanence, ou seulement quand le bandeau devient "collé" au haut de page ?

**Comment by overflorian** [comment]
seulement quand il est collé dans l'idéal

**Comment by PanierAvide** [comment]
C'est fait, il est visible tout le temps pour que ce soit plus rapide à mettre en oeuvre.

**Comment by overflorian** [comment]
Ça rend super, merci
