### ISSUE TITLE
Décomptes osmium erronés

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#132]
Hello

J'ai des décomptes fait par osmium tags-count un peu étranges quand je compares avec le taginfo-fr.

```
osmium time-filter "/data/files/pdm/usefull_ids.osh.pbf" 2020-10-15T00:00:00Z -o - -f osm.pbf | osmium tags-count - -F osm.pbf power=pole,tower
123504	"power"	"tower"
11677	"power"	"pole"
osmium time-filter "/data/files/pdm/usefull.osh.pbf" 2020-10-15T00:00:00Z -o - -f osm.pbf | osmium tags-count - -F osm.pbf power=pole,tower
115779	"power"	"tower"
11212	"power"	"pole"
```

Entre les deux fichiers usefull_ids et usefull, les décomptes ne sont pas les mêmes et cela m'étonne.
En comparant avec taginfo, les proportions n'ont aucune commune mesure.
http://taginfo.openstreetmap.fr/tags/power=tower => ~255k
http://taginfo.openstreetmap.fr/tags/power=pole => ~564k

En relançant les traitements depuis le début, j'ai les mêmes résultats, avec le fichier de france métropolitaine.

Toute aide bienvenue :)

**Comment by PanierAvide** [comment]
Le traitement est fait en plusieurs temps de manière à récupérer l'historique complet des modifications pour les objets qui ont eu à un moment de leur vie les tags demandés (table `pdm_changes`) :
- usefull_ids.osh.pbf : le fichier qui contient les objets avec les tags souhaités (historique partiel)
- usefull.osh.pbf : le fichier avec les objets disposant des tags souhaités (historique complet)

Pour le comptage brut c'est donc `usefull.osh.pbf` qu'il faut utiliser.

Je viens de faire le test avec le script `09_project_update_tmp` et j'ai bien un décompte cohérent avec taginfo (825602 objets), ce n'est pas un problème dans ton fichier PBF ? Ou la version d'osmium utilisée ?

**Comment by flacombe** [comment]
Merci d'avoir regardé si rapidement.
Tu as raison, j'ai du me planter dans le rechargement de l'OSH.
L'opération faite correctement, voici une courbe qui me plait mieux !
![image](https://user-images.githubusercontent.com/5690599/103142629-7b5cfe80-4706-11eb-8f6d-31a11112e7d2.png)

Bonne nuit
