### ISSUE TITLE
Un identifiant osm_id numérique déclanche une erreur JS dans createFeatureButton

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#134]
Hello

J'ai commencé à brancher mon serveur de tuiles à pdm, et j'ai naïvement envoyé des tuiles contenant une propriété osm_id numérique.  
Une erreur js est levée dans website/templates/components/edit_button.pug, ligne 103 : un objet numérique n'a pas de fonction replace

Si osm_id doit etre une chaine de texte ou composé d'une certaine façon, il faut mettre à jour la doc, sinon modifier le JS pour accepter les entiers.

Voir la stack:
TypeError: options.osmid.replace is not a function map:1860:93
    createFeatureButton http://enedis.infos-reseaux.com/projects/2021-01_poteaux/map#map=12.11/46.02059/6.1305:1860
    getDescription http://enedis.infos-reseaux.com/projects/2021-01_poteaux/map#map=12.11/46.02059/6.1305:2357
    <anonyme> http://enedis.infos-reseaux.com/projects/2021-01_poteaux/map#map=12.11/46.02059/6.1305:2460
    showFeature http://enedis.infos-reseaux.com/projects/2021-01_poteaux/map#map=12.11/46.02059/6.1305:2785
    fire http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:31
    _afterEase http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:35
    flyTo http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:35
    _stop http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:35
    stop http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:35
    _renderFrameCallback http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:35
    <anonyme> self-hosted:876
    run http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:35
    _render http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:35
    _frame http://enedis.infos-reseaux.com/lib/mapbox-gl/mapbox-gl.js:35

**Comment by PanierAvide** [comment]
`osm_id` doit être un identifiant OSM au format classique `type/numéro` par exemple `node/1234`. Je pense qu'on doit rester sur cette logique là car côté client il y a plein de code qui se base sur ce format là (liens vers OSM, éditeurs, ...).

**Comment by flacombe** [comment]
Le problème est qu'imposm3 créé bien une colonne osm_id chez moi, de type numérique.
Comment obtiens-tu cet identifiant incluant la primitive ?

J'utilise le type `id` pour la colonne osm_id produite par imposm3 de mon côté

**Comment by PanierAvide** [comment]
C'est ici que se fait la manip pour avoir l'identifiant OSM, donc pas via Imposm mais dans les vues mises à dispo pour le rendu vectoriel : https://github.com/vdct/ProjetDuMois/blob/master/db/20_features_update.js#L56

**Comment by PanierAvide** [comment]
Je ferme ce ticket car à priori ça ne pose plus problème côté portail Enedis ? N'hésite pas à mettre à jour s'il subsiste un point à régler là-dessus.
