### ISSUE TITLE
Note à traiter

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#14]
Afficher l'auteur et la date de la note.
Si possible toute la discussion.

Le texte "Une personne a créé une note ici, vérifiez puis éditez OSM pour intégrer les informations" me semble inutile 😉 

Exemple : https://projetdumois.fr/projects/2020-09_aed/map#16.52/45.029499/1.782839

**Comment by PanierAvide** [comment]
Ça a du sens d'afficher toute la discussion, dates et auteurs.

Le petit texte a vocation à guider les débutants sur ce à quoi correspond une note, donc effectivement inutile pour une personne habituée, mais il restera quand même :wink:

**Comment by pyrog** [comment]
> Ça a du sens d'afficher toute la discussion, dates et auteurs.

C'était une question ?

> Le petit texte a vocation à guider les débutants sur ce à quoi correspond une note…

Parfait, mais alors mettre ça dans un panneau "astuce".
Il pourrait être désactiver avec par exemple une "croix" indiquant au survol "ne plus m'afficher cette astuce".

**Comment by PanierAvide** [comment]
> C'était une question ?

Une réponse plutôt :smile: 

> Parfait, mais alors mettre ça dans un panneau "astuce".
> Il pourrait être désactiver avec par exemple une "croix" indiquant au survol "ne plus m'afficher cette astuce".

C'est sûr que ce serait l'idéal, par contre ça ne me semble pas la priorité comparé à d'autres sujets. Le dépôt reste ouvert aux contributions évidemment.

**Comment by pyrog** [comment]
### Remarque
Pour un DAE à intégrer, il n'y a pas ce petit texte pour les débutants. (Cf. https://github.com/vdct/ProjetDuMois/issues/18)

**Comment by PanierAvide** [comment]
Les notes sont affichées en entier, avec la notice dans un petit encart bleu.

**Comment by pyrog** [comment]
Comme dans Ça Reste Ouvert 😄 

Le texte déborde dans cet exemple :
<img width="200" alt="Note à traiter" src="https://user-images.githubusercontent.com/2158081/91048758-679c7100-e61c-11ea-9375-bd82ae526727.png">

**Comment by PanierAvide** [comment]
J'arrive pas à reproduire ce bug de dépassement, problème lié au navigateur ?

**Comment by pyrog** [comment]
Oui avec **Safari** et **Chrome**.
Ça fonctionne bien avec **Firefox**.

**Comment by PanierAvide** [comment]
Corrigé.

**Comment by pyrog** [comment]
Nickel avec ces 3 navigateurs, merci 😸
