### ISSUE TITLE
Input 3state avec valeur null

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#140]
Je rencontre un cas dans lequel un champ édité par un input 3state ne serait utile qu'avec la valeur yes.

La clé location:transition est courraient utilisée avec la valeur yes et est tout simplement omise pour tout autre cas.
Actuellement, les utilisateurs vont mettre plein de "no" en utilisant le 3strate puisque la valeur par défaut est "je ne sais pas".
Ces éditions ne seront pas utiles en définitive.

Ne faudrait-il pas un input 2state qui met le tag à yes ou le supprime sinon ?

**Comment by PanierAvide** [comment]
Ça me va si `2state` = yes/vide.
