### ISSUE TITLE
Liste de dates incomplete en cas de refresh projet sans osh_timestamp

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#142]
Les statistiques projet sont complètement rafraichies en cas d'absence d'un fichier WORK_DIR/osh_timestamp.
Une liste de dates est incluse dans le script bash permettant de recalculer les statistiques chaque jour.

Problème : cette liste de date correspond au moment ou est appelée la commande `npm run project:update` et ne sera plus adaptée dès 24h plus tard.

Il faut inclure dans le bash le moyen de générer la liste des dates nécessaires au moment où `09_project_update_tmp.sh`a besoin de recalculer tous les points de temps

**Comment by PanierAvide** [comment]
Dans l'instance de prod, le script `npm run project:update` et `09_project_update_tmp.sh` sont systématiquement lancés l'un après l'autre. Dans quelle mesure ce serait intéressant de décorréler l'exécution des deux ?

**Comment by flacombe** [comment]
Ah je n'avais même pas fait attention à cela.
De mon côté je génère les scripts avec npm une fois et le cron n'execute que le bash tous les jours.

C'est intéressant pour faciliter le debug, on regarde le bash et point.
Je suis arrivé à tout remettre dans le bash dans la PR en cours quoi qu'il en soit
