### ISSUE TITLE
Des contributeurs s'affichent en double sur le podium

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#144]
Voir la capture ci-dessous, il arrive que certains contributeurs soient affichés deux fois sur le podium.
Il doit y avoir un problème de distinct ou de group by dans l'une des requêtes, je vais investiguer

![image](https://user-images.githubusercontent.com/5690599/103706902-eda6cc00-4fad-11eb-8789-5de5ce10639c.png)

**Comment by PanierAvide** [comment]
C'est possible que ce soit purement un problème d'affichage côté client, comme la 4e marche du podium est ajoutée spécifiquement pour afficher l'utilisateur connecté. C'est possible que ce soit lié au fait que tu sois en 4e position.

**Comment by flacombe** [comment]
Ce n'est pas qu'un problème d'affichage, les noms sont bien en double dans la table pdm_leaderboard

![image](https://user-images.githubusercontent.com/5690599/104110915-aafe3000-52dc-11eb-959e-5e07de306c17.png)
