### ISSUE TITLE
Nouveaux badges poteaux électriques

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#148]
Sur demande de @flacombe voici une proposition de badges pour les poteaux électriques.
![flowRoot12095-2-5-3-6-5](https://user-images.githubusercontent.com/11553211/104161302-ee4ac280-53f2-11eb-95b3-9deb91bad5a7.png)
[badge-poteau-electrique.zip](https://github.com/vdct/ProjetDuMois/files/5794672/badge-poteau-electrique.zip)

Pour être honnête, je ne suis pas hyper satisfait du résultat, qu'en pensez-vous @flacombe @PanierAvide ?

**Comment by PanierAvide** [comment]
Sur le principe c'est pas si mal, juste le symbole de poteaux est pas trop parlant. Peut-être avec celui-ci ça passerait mieux ? https://thenounproject.com/search/?q=electricity+pole&i=2504231

**Comment by overflorian** [comment]
Je suis bien plus satisfait de ma deuxième proposition :
![g10662](https://user-images.githubusercontent.com/11553211/104221459-309af080-5441-11eb-9b7a-9a9ff7eb527d.png)
[badge-poteau-electrique.zip](https://github.com/vdct/ProjetDuMois/files/5797557/badge-poteau-electrique.zip)
Banco bongo ?

**Comment by PanierAvide** [comment]
Sympa :wink:

**Comment by flacombe** [comment]
Super, je prends la seconde version aussi

Merci à toi

**Comment by PanierAvide** [comment]
Je ferme le ticket
