### ISSUE TITLE
Erreur suite à ajout de contribution

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#149]
Lors de l'édition d'un point depuis une couche Osmose sur l'éditeur intégré, j'ai une erreur relative à cette trace

```
ReferenceError: addContribution is not defined
    onceDone https://enedis.openstreetmap.fr/projects/2021-01_substations/map:1571
map:1608:13
    onFeatureFormSubmit https://enedis.openstreetmap.fr/projects/2021-01_substations/map:1608
```

Bizarre non ?

(Mais la contribution est bien envoyée)

**Comment by PanierAvide** [comment]
Un problème sur le paramètre qui permet de vérifier si un projet est actif ou non. La fonction addContribution permet de comptabiliser côté projetdumois les contributions en "temps réel" plutôt que d'attendre la mise à jour des données depuis OSM.
