### ISSUE TITLE
Afficher sur la carte les photos Mapillary

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#15]
Ça serait plus pratique d'afficher (en option ?) la couche Mapillary.
Idem pour OpenStreetCam, voir Wikimedia…

**Comment by PanierAvide** [comment]
Ça pourrait pour d'autres projets du mois, sur celui des défibrillateurs les photos ne m'ont pas été d'une grande aide sur Pic4Review (ajouté 3/4 DAE). Quel usage avais-tu en tête ?

**Comment by pyrog** [comment]
> Quel usage avais-tu en tête ?

Vérifier si le DAE est visible sur le terrain. Ça aide avec une note un peu trop concise comme la [2291438](https://www.openstreetmap.org/note/2291438).

De plus (et surtout ?) cliquer sur le lien Mapillary pour afficher leur carte (ce qui peut être long), pour s'apercevoir qu'il n'y a pas de photo est un peu frustrant.

**Comment by PanierAvide** [comment]
Une solution intermédiaire pourrait être de n'afficher le lien Mapillary que s'il existe une photo à proximité, ce serait plus simple à intégrer que la couche photo.

**Comment by PanierAvide** [comment]
Plus j'y pense, plus j'ai l'impression qu'afficher Mapillary en fond ça va nous amener à recréer Pic4Review...

**Comment by PanierAvide** [comment]
C'est fait
