### ISSUE TITLE
Style vectoriel : routes mineures tracées par dessus les routes tertiaires

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#151]
<img width="33%" alt="PdM" src="https://user-images.githubusercontent.com/2158081/105354895-83b73500-5bf1-11eb-9e0a-7e26a4a4b9c7.png">

C'est corrigé dans https://github.com/maputnik/osm-liberty/issues/90 😎 
<img width="33%" alt="osm-liberty" src="https://user-images.githubusercontent.com/2158081/105355019-b9f4b480-5bf1-11eb-8533-f99b60c5d0f1.png">

**Comment by PanierAvide** [comment]
@frodrigo comment ça se passe pour répercuter ça sur le serveur OSMFR ?

**Comment by frodrigo** [comment]
Just a clone of the style repo / gh-pages
Updated.

**Comment by PanierAvide** [comment]
Merci pour la mise à jour, et merci @pyrog pour le signalement :wink:
