### ISSUE TITLE
Différence de décompte entre fil de l'eau et recalcul from scratch

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#153]
Sur le projet Enedis, j'ai voulu recalculer l'intégralité des statistiques pour supprimer des erreurs introduites par osmose plus tôt ce mois-ci.

Ca n'a pas fonctionné pour Osmose (ce n'est pas grave) mais j'ai observé une grande différence entre les décomptes fait tout ce mois-ci au fil de l'eau et les nouvelles valeurs calculées cet après-midi.
Il semble que la mise à jour du fichier osh ne permet pas à osmosis de voir les mises à jour de tags. Ainsi un objet munis de tags lui permettant d’apparaître dans le projet en cours aujourd'hui sera vu tel quel jusqu'à sa date de création.

Voir les deux graphes ci-dessous :
Au fil de l'eau :
![lsj0b4CD jpg large](https://user-images.githubusercontent.com/5690599/105611029-4d291800-5db3-11eb-931c-ff28db132186.jpeg)

Après recalcul :
![image](https://user-images.githubusercontent.com/5690599/105611041-616d1500-5db3-11eb-845b-f4690942e9e2.png)

Le graphique au fil de l'eau traduit mieux la situation réelle : les marches correspondent à des campagnes de nettoyage de tags sur des objets existants dans OSM au début de la période d'observation

Est-ce que cela correspond à quelque chose de souhaité d'après vous ?

**Comment by PanierAvide** [comment]
Ce qui est souhaité en tout cas c'est d'avoir un décompte qui traduit la réalité : à chaque instant t, que l'on ait le nombre d'objets dans OSM portant les tags sélectionnés.

Je suis pas sûr de comprendre, quand tu parles d'osmosis c'est dans ton installation Enedis ? Car dans le dépôt actuel on utilise osmupdate pour la mise à jour du fichier OSH au fur et à mesure.

Et du coup la différence est due au fait que dans un cas, on compte l'objet depuis sa version 1 (même s'il n'a pas encore les tags), là où dans l'autre cas on ne compte qu'au jour de la présence effective du tag ?

**Comment by flacombe** [comment]
Nous sommes d'accord, osmupdate fait la mise à jour, osmosis fait ensuite le filtrage pour obtenir le décompte jour par jour.

Au fil de l'eau disons qu'on compte les objets à leur version courante alors que lors du recalcul complet, on voit l'objet dans l'état qu'il a actuellement jusqu'à la date de la création de sa version 1.
Regardes, sur le fil de l'eau, le graphe commence avec ~60k objets alors que lors du recalcul complet on voyait déjà 116k objet début octobre (la valeur attendue est bien ~60k, peut-être même moins)

On ne peut pas dire que la date ne soit pas prise en compte par osmosis, sinon on aurait une droite mais il devrait considérer la version antérieure des objets et pas celle en cours.

Je crois que le bug se manifeste également au fil de l'eau. Chez moi je recompte aussi les valeurs à J-2 du fait du timestamp (c'est voulu)
J'étais surpris que les changesets de nettoyage soient comptés à J-2 systématiquement alors qu'ils ont été fait à J-1. Mais vu que la plupart des objets existaient et que ces changeset de nettoyage n'en créé que quelques uns, le compte à J-2 les inclue aussi.

Si ce n'est pas clair je peux faire un chronogramme.
C'est un cas super intéressant, on rentre dans le dur là :)

**Comment by PanierAvide** [comment]
C'est clair que c'est pas le bug le plus simple à résoudre :stuck_out_tongue: 

Comment on peut avancer pour résoudre ça ? Tu veux te pencher sur le sujet où je regarde de mon côté ? En sachant que débugger la mise à jour au fil de l'eau ce sera pas bien évident...

**Comment by flacombe** [comment]
Non c'est clair que c'est pas simple.
Pour que tu arrives à le reproduire :
- Fige un fichier .osh sans mise à jour à une date t0.
- Laisse moi faire un ou deux départements sur le nettoyage des poteaux en fin de semaine.
- Calcule ensuite la volumétrie correspondant au filtre n/power=pole,tower&n/operator=Eedis sur les deux fichiers à une date t-1 antérieure à t0.
- Les valeurs sont attendues identiques et le bug fera qu'elles seront différentes du fait du nettoyage sur des objets existants à t-1

Je vais me plonger dans la dos d'osmosis pour voir si il y a une option oublié ou faire un rapport de bug le cas échéant

**Comment by flacombe** [comment]
Hello

J'ai de nouveaux éléments sur ce problème.
Il semble que ca vienne de différences que je n'ai pas encore qualifié entre le fichier filtered.osh.pbf et le fichier usefull.
Illustration :

```
$> osmium time-filter "/data/files/pdm/filtered_poteaux.osh.pbf" 2021-01-01T00:00:00Z -o - -f osm.pbf | osmium tags-count - -F osm.pbf power=pole,tower | cut -d$'\t' -f 1 | paste -sd+ | bc
69026
$> osmium time-filter "/data/files/pdm/usefull_poteaux.osh.pbf" 2021-01-01T00:00:00Z -o - -f osm.pbf | osmium tags-count - -F osm.pbf power=pole,tower | cut -d$'\t' -f 1 | paste -sd+ | bc
126568
```
A la même date, les deux fichiers n'affichent pas le même décompte. La valeur attendue est 69026, celles du fichier filtered.

Est-ce que cela te dit quelque chose ?

**Comment by PanierAvide** [comment]
Que le filtered donne le bon nombre ça semble logique, comme c'est juste le filtre attributaire qui est appliqué. Dans usefull, on ajoute l'historique complet de chaque objet pour suivre les évolutions avant/après modifications, et trouver les ajouts de tags à considérer sur objets existants, ou la suppression des tags à considérer. Normalement usefull c'est donc filtered + des autres versions des objets de filtered sans les tags à considérer. Un problème au niveau du tags+count ?

**Comment by flacombe** [comment]
La documentation de time-filter donne

> One command is only useful for history files: time-filter. It is used to filter objects from a history file based on time. To get all objects visible at a point in time use a command line like this:
>
>osmium time-filter history.osm.pbf 2015-01-01T00:00:00Z -o 2015.osm.pbf
>
>The output is a normal OSM data file containing the data as it would have looked at the start of the year 2015 (UTC time as always with OSM).

Ainsi tags-count devrait donner le bon nombre ensuite vu qu'aucune version ne se chevauche.
Je dis que la valeur attendue est obtenue avec le filtered parce que l'ordre de grandeur est plus proche de la réalité. Le fichier filtered ne montrera pas les objets supprimés depuis la date retenue toutefois.
C'est pour ca que le choix de faire le tags-count sur le fichier usefull est pertinent : il faut prendre en compte les objets supprimés.

Ce serait le fichier usefull qui est mal formé ?

**Comment by flacombe** [comment]
Je crois que je viens de comprendre : dans mon cas, j'ai *beaucoup* d'objets auxquels on ajoute les tags nécessaires au projet très progressivement et à des dates très éloignées dans le temps.
Le cycle de vie d'un poteau classique est le suivant :
* 2012 : Création d'un noeud vierge
* 2015 : Ajout de power=pole
* 2021 : Ajout de operator=Enedis

Vu que je cherche tous les objets power=pole&operator=Enedis, le filtered ne contient que ces objets à date.
Je créé ensuite le fichier useful avec getid, puis refabrique un fichier à date du 1er janvier 2018.
Mon noeud ci-dessus va se retrouver avec power=pole uniquement.
Vu que le filtre utilisé pour faire les stats utilise le dernier morceau du filtre de info.json, ici n/power=pole, le nœud à l'époque incomplet se retrouve comptabilisé.

Il m'a fallu créer un fichier .osm avec time-filter et l'ouvrir dans josm pour m'en rendre compte.
Je prépare un patch pour ça !

**Comment by flacombe** [comment]
L'explication était bien la bonne
![image](https://user-images.githubusercontent.com/5690599/106369573-ec6d8280-6352-11eb-8ed8-cc1d4fff40b6.png)

La solution nécessite de filtrer séquentiellement le .osm.pbf de chaue point de temps lors du calcul des stats.
Ca restera sous-optimal tant que osmium ne permettra pas des sélections avec des & logiques.
J'ai réussi à tenir le timing quand même, le script est un peu plus lent mais ca reste très acceptable
