### ISSUE TITLE
Les points du podium croissent sans cesse

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#156]
Sur le projet Enedis, je prends des points au podium même sans avoir contribué (dans des proportions délirantes)
https://enedis.openstreetmap.fr/projects/2021-01_poteaux#statistics

C'est toujours cool pour l'égo mais je suspecte un problème dans le calcul :)

Je vais refaire une passe ce weekend et en profiter pour fixer #143 puisqu'il semble que ce soit un problème lié

Wait for the PR

**Comment by PanierAvide** [comment]
Merci pour ce retour. En regardant rapidement j'arrive pas à retrouver quand est vidée la table `pdm_user_contribs`, ça veut dire qu'à chaque mise à jour les points sont potentiellement doublés ? Ça expliquerait pas mal de choses :stuck_out_tongue:
