### ISSUE TITLE
Ux écran de positionnement

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#158]
Voici l'écran de positionnement d'un objet à ce jour :
![Screenshot_20210205-130957.jpg](https://user-images.githubusercontent.com/11553211/107032268-d6791b00-67b3-11eb-8012-c8dcae47df47.jpg)

Je recommande de ne pas utiliser le terme "objet".
Proposition de rewording : "Position exacte ↲ Bougez la carte"

C'est une proposition au rabais car dans l'idéal il faudrait plutôt supprimer toute mention écrite hors bouton et indiquer visuellement cette fonctionnalité. Avec un tremblement de la carte d'une micro-seconde + un indicateur animé.

PS : J'ai fait un petit benchmark et toutes les applis avec carte évitent soigneusement d'avoir un tel écran. Je vais creuser les idées. 

PPS : idée complémentaire : rajouter un tag lorsque l'utilisateur a l'outrecuidance de placer un POI à un niveau de zoom inférieur à 16 :
fixme=Position approximative à préciser. Contribution au zoom 17 via le site ProjetDuMois.fr

**Comment by overflorian** [comment]
OK j'ai eu une idée complémentaire ici https://github.com/vdct/ProjetDuMois/issues/159

**Comment by PanierAvide** [comment]
J'ai changé le message en "Placer à la position exacte", et ajouté le tag fixme si le zoom est <= 16. Ce sera déployé dans l'après-midi.

**Comment by overflorian** [comment]
Merci !
