### ISSUE TITLE
Ajouter un défibrillateur manquant

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#16]
En cliquant depuis un POI, ça sera pratique de positionner le curseur exactement sur celui-ci.

Et aussi de préremplir les champs de saisie quand il y a des données disponibles.

**Comment by PanierAvide** [comment]
+1

**Comment by pyrog** [comment]
La notion d'ajout n'est peut-être pas très clair pour un débutant ?

L'ajout peut se faire avec 5 éditeurs depuis cette page : JOSM | iD | OSM | Osmose et l'éditeur intégré (accessible par le gros bouton bleu).

Un seul bouton serait plus simple :
La première fois, on propose de choisir un des éditeurs en donnant éventuellement des conseils pour les débutants.

**Comment by pyrog** [comment]
Pour ajouter un nouveau DAE (sans avoir cliqué sur au préalable sur un POI existant), les liens des autres éditeurs ne sont pas visibles.
<img width="200" alt="Capture d’écran" src="https://user-images.githubusercontent.com/2158081/91008768-5b45f300-e5df-11ea-8bf0-80509b19205f.png">

**Comment by PanierAvide** [comment]
L'interface propose désormais un bouton d'édition "unifié", avec les différentes options d'édition intégrées. Ça comprend aussi la fermeture automatique de notes / signalements Osmose une fois la contribution réalisée via l'outil. Et le préremplissage du formulaire autant que possible. Cf afad604bf034dcb97604d063a6632a7432e364f9
