### ISSUE TITLE
Redimentionner logo 

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#160]
Le logo "principes pour le développement numérique" dépasse sur mobile et provoque une désagréable possibilité de scrolling horizontale :
![Screenshot_20210204-131540.jpg](https://user-images.githubusercontent.com/11553211/107038641-198bbc00-67bd-11eb-9e28-beaf08af5e57.jpg)

Je pense qu'il suffit de lui limiter sa largeur à 100% de l'écran pour corriger ça.

**Comment by PanierAvide** [comment]
Corrigé, je déploie ça dans l'après-midi
