### ISSUE TITLE
Lisibilité des nombres

### ISSUE THREAD

**Issue by gendy54** [vdct/ProjetDuMois#163]
Hello,

**Problématique:**
Sur la page https://enedis.openstreetmap.fr/projects/2021-01_poteaux#statistics, je trouve que les nombres sont difficiles à lire.
Sur ce projet, on pourra atteindre des nombres à 1 millions (de poteaux).

![image](https://user-images.githubusercontent.com/10323517/107154410-1803f480-6973-11eb-9514-c87f3fc32ca3.png)
![image](https://user-images.githubusercontent.com/10323517/107154442-41248500-6973-11eb-956f-ca6842ce0f4d.png)

**Proposition:**
- les afficher avec un séparateur de milliers
- et/ou les aligner à droite (dans le classement uniquement)

**Comment by PanierAvide** [comment]
C'est corrigé, je laisse @flacombe déployer sur son instance :wink:

**Comment by flacombe** [comment]
Merci Adrien, c'est aussi déployé chez moi !
