### ISSUE TITLE
Télécommande JOSM

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#17]
### Safari
Elle ne fonctionne pas.

Il y a ce bug sur le site OSM (en fait une gestion de sécurité trop stricte dans Safari).
Le site OSM affiche un message d'erreur indiquant que la télécommande ne fonctionne pas.

### Firefox et Chrome
Charge toutes les données dans JOSM et demande confirmation pour ajouter les tags.
Je propose de ne charger que le POI, et si possible sans demander de confirmation.

### Cas des notes
Aucun POI n'est ajouté. Il faudrait en créer un avec les tags minimum :
* emergency=defibrillator
* source=https://www.openstreetmap.org/note/2291438

Pour la source, la mettre dans la source du changeset si c'est possible techniquement ?

**Comment by PanierAvide** [comment]
Merci du retour, un message d'erreur apparaît si la télécommande JOSM n'a pas pu être contactée. Au niveau du POI dans JOSM, pas trouvé de moyen de ne pas confirmer l'action. Je crois que ça doit se régler globalement dans les paramètres de JOSM, mais pas autrement.

Pour la source, il me semblait que mettre sur l'objet n'était plus trop apprécié. Le mieux est sur le groupe de modification, mais comme celui-ci ressert pour plusieurs modifications successives, ce n'est pas simple d'identifier la ou les sources. Notamment lors d'un ajout direct : est-ce par le terrain, connaissance locale, informations sous licence compatible diffusées par ailleurs... Pour l'instant on va rester sur pas de source ajoutée. L'objet du site n'est pas de refaire iD ou JOSM mais d'avoir un éditeur simple/simplifié.

**Comment by pyrog** [comment]
>Pour la source, il me semblait que mettre sur l'objet n'était plus trop apprécié.

Oui. Ça se pratique toujours concernant les imports (ce qui est le cas quand les données proviennent de GéoDAE).

> Le mieux est sur le groupe de modification

Oui.

> celui-ci ressert pour plusieurs modifications successives

Il faut peut-être la jouer à la Street Complete ?
1 POI ajouté ou modifié = 1 changeset

**Comment by PanierAvide** [comment]
Il me semblait que StreetComplete regroupait les modifications par quête plutôt, car clairement la règle 1 modification = 1 changeset a déjà fait grincer des dents.

**Comment by pyrog** [comment]
Je me trompe peut-être d'outil ?
Mais il me semble que des éditeurs font ça. En tout cas des contributeurs le font avec JOSM ou iD.

Je n'étais pas chaud au départ, mais l'inverse n'est pas top non plus : un énorme changeset difficile à analyser.

**Comment by PanierAvide** [comment]
Pas de règle absolue, ce qui est sûr :
- iD et JOSM laissent le soin à l'utilisateur de juger de la taille du changeset
- Osmose, Pic4Review, MapContrib réutilisent autant que possible le même changeset
- StreetComplete regroupe par mission
- Le site osm.org n'est pas optimisé pour afficher les changeset, mieux vaut utiliser OSMCha
