### ISSUE TITLE
Signalement "déjà mappé"

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#170]
D'expérience personnelle sur le terrain, j'ai été frustré d'avoir à cocher "Rien ici" plutôt que d'indiquer la vérité, c'est à dire que je venais de mapper le POI.
C'est pour cela que je propose de rajouter une fonctionnalité avancée (c'est pour cela que je propose de la planquer un peu) :
![image](https://user-images.githubusercontent.com/11553211/108107663-d4ef0300-708f-11eb-9ab0-2444fc0d1b43.png)

En back-office, je n'ai même pas idée si cela peut changer quelque chose ou si c'est seulement de l'UI.

**Comment by PanierAvide** [comment]
J'ai changé le libellé en "Rien ici / déjà fait", ce sera déployé dans l'aprèm
