### ISSUE TITLE
Mise à jour des données en échec

### ISSUE THREAD

**Issue by PanierAvide** [vdct/ProjetDuMois#173]
Du fait de l'utilisation de l'outil osmupdate, le script de mise à jour des fichiers PBF est en échec :
```
==== Get latest changes
osmupdate Parameter: /tmp/pdm/france-internal.osm.pbf
osmupdate Parameter: 2021-02-21T21:55:43Z
osmupdate Parameter: /tmp/pdm/changes_features.osc.gz
osmupdate: newest sporadic timestamp: (no timestamp)
osmupdate: newest minutely timestamp: (no timestamp)
osmupdate Error: Could not get the newest minutely timestamp from the Internet.
```

C'est lié au changement d'outillage sur le serveur de prod OSM : https://github.com/openstreetmap/operations/issues/508

La seule solution apportée sur la liste osm-dev est d'avoir honte d'utiliser osmupdate : https://lists.openstreetmap.org/pipermail/dev/2021-February/031075.html

Donc hormis osmupdate qui est cassé, et osmosis qui est sur le chemin de la dépréciation (et accessoirement une usine à gaz), quels outils avons-nous à disposition pour mettre à jour sur la base des diffs un fichier PBF ? @flacombe

**Comment by mmd-osm** [comment]
Well, you can replace the "#" character in https://github.com/mapsme/osmctools/blob/master/osmupdate.c#L722 by "s", which would be the first character in the current state.txt file, and recompile osmupdate.c. I haven't tested it, but I think it should work.

**Comment by PanierAvide** [comment]
Thanks for your feedback, I will try this and see if this works.

**Comment by mmd-osm** [comment]
Ah, hold on, there's probably a need for some further changes:

changefile_timestamp is no longer available in https://github.com/mapsme/osmctools/blob/master/osmupdate.c#L741-L751, and subsequent logic somehow needs that value. Bummer.

**Comment by mmd-osm** [comment]
The proposal in https://lists.openstreetmap.org/pipermail/dev/2021-February/031077.html should also work.

**Comment by PanierAvide** [comment]
Fixed by e860690 (forcing use of hour diff files), thanks @mmd-osm for your hints.
