### ISSUE TITLE
Bouton de connexion simplifié

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#177]
Lorsque l'utilisateur est connecté à son compte osm.org sur le même navigateur, on peut faire mieux qu'un bouton de connexion : un bouton de connexion pré-rempli, comme sur cet exemple :
![image](https://user-images.githubusercontent.com/11553211/109174232-f1bcc200-7784-11eb-9322-dd8d13b410ea.png)

Ça ne fonctionnera pas avec la prochaine version de Firefox (cf. https://www.zdnet.fr/actualites/firefox-mozilla-propose-une-protection-totale-contre-les-cookies-39918495.htm) mais c'est tout de même intéressant pour une majorité d'utilisateurs.

@PanierAvide avant d'aller plus loin, est-ce qu'on est bons techniquement pour récupérer le pseudo + photo du compte OSM ?

**Comment by PanierAvide** [comment]
Bof bof ça fait un peu pistage des familles... Puis techniquement ça va être très aléatoire : si osm.org change le nom de son cookie c'est des modifs à refaire...

**Comment by overflorian** [comment]
Ok oublions ça dans ce cas
