### ISSUE TITLE
Description des DAE à ajouter

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#18]
Mettre en évidence la description sous le titre (Entourée en jaune pour l'exemple).

Le titre est pertinent (tag `name` 😉).
Je mettrais plutôt la localisation (tag `defibrillator:location`) à la place de l'horaire (tag `opening_hours`)

![Screenshot_2020-08-23 Projet du mois fr](https://user-images.githubusercontent.com/2158081/90988783-bb17ac00-e595-11ea-97c1-678a8c97d8eb.jpeg)

**Comment by PanierAvide** [comment]
C'est désormais affiché :wink:
