### ISSUE TITLE
Prendre en compte les suppressions dans pdm_changes

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#183]
Actuellement, je n'ai que des `edit` et `create` dans la table `pdm_changes`.

Le traitement xsltproc semble ne conserver que ces deux là sans prendre en compte les suppressions.

Dans le cas où une contribution est erronée et entraîne la suppression d'un objet pour le créer différemment ailleurs, ces suppressions légitimes pourraient ne pas être comptabilisées dans les stats.

A voir si c'est un besoin ou une erreur de raisonnement de ma part

**Comment by PanierAvide** [comment]
À priori dans les fichiers XSLT, les cas de suppressions sont bien prévus : https://github.com/vdct/ProjetDuMois/blob/master/db/osc2csv.xslt#L57

Tu as vu un cas qui pose problème ou ce n'est qu'une supposition ?

**Comment by flacombe** [comment]
Tu as raison, c'est une erreur de ma part, je n'ai pas considéré la bonne colonne pour faire mon select distinct.

C'est tout bon
