### ISSUE TITLE
Historique à 0 dans les stats géographiques

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#186]
Sur le suivi Enedis, j'ai un graphique à 0 sur toute la période malgré la présence des données dans les tuiles.
Une idée du pourquoi ?

![image](https://user-images.githubusercontent.com/5690599/110259554-88b92380-7fa8-11eb-803f-580d7a89e06e.png)

Je suspecte un traitement des tags en mode chaine de texte, mon serveur de tuiles (tegola) n'accepte pas de renvoyer du json, il m'oblige à mettre stats::text dans la requête
```
mars 07 23:52:14 oim001 tegola[5723]: 2021/03/07 23:52:14 map.go:304: err fetching tile (z: 4, x: 7, y: 5) features: for layer (pdm_boundaries) unable to convert field [4] (stats) of type (114 - json) to a suitable value: map[2020-10-01...
```

**Comment by PanierAvide** [comment]
À priori tu peux renvoyer le champ `stats` sous forme d'une chaîne de caractères contenant du JSON, les tuiles générées par `pg_tileserv` repassent sur du texte et donc le client reconvertit lui-même en JSON : https://github.com/vdct/ProjetDuMois/blob/master/website/templates/components/stats.pug#L350

**Comment by flacombe** [comment]
C'est réglé, j'avais laissé les dates au format timestamp alors qu'il fallait les ramener au format yyyy-mm-dd.

Cette issue sera fermée par la PR en cours
