### ISSUE TITLE
Afficher une imagerie aérienne

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#19]
Le rendu est zoomé ce qui rend les tuiles "floues" (du moins sur un ordinateur. Pas testé sur smartphone).

<img width="251" alt="Capture d’écran" src="https://user-images.githubusercontent.com/2158081/91006725-76faca80-e5da-11ea-9ce4-36738f02b984.png">

La version vectorielle serait plus "jolie", ou une version bitmap avec un niveau de zoom plus important.
De plus pour certains projets, une orthophoto serait plus adaptée.

Proposer au moins BDOrtho IGN ou une couche "Christian" HR pour les départements couverts.

**Comment by PanierAvide** [comment]
C'est clair qu'un fond vectoriel serait plus joli sur PC (sur smartphone l'effet flou n'est pas autant visible), mais fond vectoriel = prestataire externe + forfait qui peut devenir payant à un certain moment. Et il n'y a pas encore de rendu communautaire vectoriel utilisable pour ce genre de service.

Pour l'ortho ça a du sens, mais pareil pas forcément prioritaire sur le cas des défibrillateurs.

**Comment by PanierAvide** [comment]
Le rendu des tuiles est corrigé et il n'y a plus cet effet flou.

**Comment by pyrog** [comment]
>  Le rendu des tuiles est corrigé

👍

**Comment by PanierAvide** [comment]
Remplacé par #45
