### ISSUE TITLE
Implémenter le projet du mois de juin

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#2]
MVP :
- [x] La carte de France avec les remontées Osmose liées au Covid

V1 (celle pour laquelle on lance la com', dans l'idéal le 1er juin) :
- [x] [installé sur le ndd projetdumois.fr](https://github.com/vdct/ProjetDuMois/issues/1)
- [x] Lien vers JOSM avec infos pré-remplies sur le POI
- [x] Ajout d'un dashboard pour suivre l'évolution de l'avancement du projet du mois
- [x] Logo implémenté
- [x] Favicon implémenté
- [x] Lien "à propos" renvoit vers https://wiki.openstreetmap.org/wiki/FR:Project_of_the_month
- [x] Lien "Twitter" renvoit vers https://twitter.com/projetdumois

**Comment by PanierAvide** [comment]
Lié à https://github.com/osm-fr/osmose-frontend/issues/259

**Comment by PanierAvide** [comment]
Liens JOSM réalisé via 7b8b845

**Comment by PanierAvide** [comment]
À priori on est pas mal pour une première version désormais ?
