### ISSUE TITLE
Défibrillateurs dans OSM

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#20]
Les DAE dans OSM (en vert) ne sont pas affichés :
https://projetdumois.fr/projects/2020-09_aed/map#18.64/46.5763186/5.7506768
https://www.openstreetmap.org/node/6283641476

Je ne vois sur la carte que les POI bleus et rouges (pas au même niveau de zoom) et a priori aucun POI verts ou oranges (Défibrillateur potentiel)

**Comment by PanierAvide** [comment]
Corrigé, à noter que le service n'est pas officiellement lancé à l'échelle nationale (malgré la diffusion sans prévenir dans le Weekly OSM) d'où les différents bugs relevés.

**Comment by pyrog** [comment]
Merci pour la correction 😃 

> le service n'est pas officiellement lancé à l'échelle nationale

Je vois seulement les défibrillateurs à intégrer (POI rouge) à [la Réunion](https://projetdumois.fr/projects/2020-09_aed/map#9.26/-21.1341/55.5177), en [Guyane](https://projetdumois.fr/projects/2020-09_aed/map#7.96/4.91/-52.356), [Martinique](https://projetdumois.fr/projects/2020-09_aed/map#9.72/14.6338/-61.0194) et [Guadeloupe](https://projetdumois.fr/projects/2020-09_aed/map#9.23/16.1736/-61.4051).
Mais rien à [Mayotte](https://projetdumois.fr/projects/2020-09_aed/map#10.08/-12.8289/45.1592
) ni à [Saint-Pierre et Miquelon](https://projetdumois.fr/projects/2020-09_aed/map#9.53/46.9472/-56.2624).

> diffusion sans prévenir dans le Weekly OSM

Oui, c'est comme ça que je suis retourné sur le site 😄
