### ISSUE TITLE
Les valeurs trop longues ne s'affichent pas entiérement sur le graphique

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#206]
Sur le graphique qui récapitule l'utilisation des clefs, impossible connaître la fin de cette valeur (même en pointant / cliquant dessus) :
![image](https://user-images.githubusercontent.com/11553211/116431810-6628e580-a848-11eb-9a1d-c88de9328a08.png)

**Comment by PanierAvide** [comment]
On voit la valeur en passant la souris sur la barre bleue, pas le libellé ;-)

**Comment by overflorian** [comment]
oops, au temps pour moi. j'arguerai bien que ce n'est _mobile friendly_ mais je ne vais pas faire mon chieur
