### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#21]
En essayant d'afficher la page 404, le navigateur n'affiche plus aucune page même avec une URL valide. (cf. https://github.com/vdct/ProjetDuMois/issues/6#issuecomment-678907230)

La console javascript affiche le message suivant :

**Firefox**
```
GEThttps://projetdumois.fr/projects/2020-09_aed/map#8.62/48.9256/1.9838
[HTTP/1.1 502 Bad Gateway 113ms]

L’encodage de caractères du document HTML n’a pas été déclaré. Le document sera affiché avec des caractères incorrects pour certaines configurations de navigateur si le document contient des caractères en dehors de la plage US-ASCII. L’encodage de caractères de la page doit être déclaré dans le document ou dans le protocole de transfert. map
GEThttps://projetdumois.fr/favicon.ico
[HTTP/1.1 502 Bad Gateway 0ms]

```

**Chrome**
```
Failed to load resource: the server responded with a status of 502 (Bad Gateway)
/favicon.ico:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)
map#8.62/48.9256/1.9838:1 Failed to load resource: the server responded with a status of 502 (Bad Gateway)

```

**Safari**
`[Error] Failed to load resource: the server responded with a status of 502 (Bad Gateway) (favicon.ico, line 0)`

**Comment by pyrog** [comment]
Il me restait un onglet fonctionnel mais celui ci affiche maintenant :

<img width="153" alt="Capture d’écran" src="https://user-images.githubusercontent.com/2158081/91008242-38670f00-e5de-11ea-9225-f883e37bd8e2.png">

**Comment by PanierAvide** [comment]
Le service en prod était arrêté, c'est relancé.
