### ISSUE TITLE
Mise à jour du site de l'annuaire des entreprises

### ISSUE THREAD

**Issue by NathanBnm** [vdct/ProjetDuMois#214]
Actuellement lorsqu'un numéro de SIRET/SIREN apparaît dans les champs d'un élément la redirection est effectuée au clic vers https://entreprise.data.gouv.fr or il existe une nouvelle version du site à l'adresse http://annuaire-entreprises.data.gouv.fr

Pour obtenir l'adresse d'un établissement c'est très simple :

https://annuaire-entreprises.data.gouv.fr/etablissement/<SIRET ou SIREN>

Je propose donc de mettre à jour l'adresse vers le nouvel annuaire.

**Comment by PanierAvide** [comment]
Bonjour,
Merci pour ce retour, cependant ProjetDuMois.fr utilise tag2link ( https://github.com/JOSM/tag2link ) pour faire automatiquement les liens, la modification est à reporter là-bas pour que ça redescende ensuite automatiquement ici. Je vous laisse leur proposer ce changement ?
Cordialement.
