### ISSUE TITLE
Légende

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#22]
Que signifie _"Défibrillateur potentiel"_ ?
Idem pour  _"Note à traiter"_ si c'est un débutant qui utilise l'application 😉 

Une info bulle pourrait afficher un message plus explicite.

<img width="200" alt="Capture d’écran" src="https://user-images.githubusercontent.com/2158081/91008768-5b45f300-e5df-11ea-8bf0-80509b19205f.png">

**Comment by pyrog** [comment]
Après la correction de #20 je comprends à quoi correspondent ces DAEs potentiels.

Ça fait beaucoup de points oranges sur la carte.
Je propose de rendre visible/invisible les couches et/ou de ne montrer ces DAE qu'à un niveau de zoom plus élevé.

De plus **le nom du lieu** disposant potentiellement  d'un DAE **est trop petit** par rapport au titre et au "conseils pour les débutants"

<img width="300" alt="Capture d’écran" src="https://user-images.githubusercontent.com/2158081/91015317-3f484e80-e5eb-11ea-8d98-130b4aa2d698.png">

Lors de l'ajout, il faut aussi **pré-remplir les champs**.
Ici le **nom** et éventuellement les horaires du magasin si le DAE est à l'intérieur.

**Comment by PanierAvide** [comment]
> Lors de l'ajout, il faut aussi **pré-remplir les champs**.

Il ne _faut_ pas, ce _serait bien si_. L'usage de l'impératif est à réserver aux prestataires, pour du bénévolat le conditionnel passe mieux :grin: 

Ça vaudrait le coup de boucler avec @overflorian pour la partie mise en page et ergonomie, ou à regarder du côté de ce que peut faire StreetComplete.

**Comment by pyrog** [comment]
>Il ne faut pas, ce serait bien si

Ne pas se polariser sur la forme 😉 

Je m'inclus dans les bénévoles (déjà comme bêta testeur, et puis comme contributeur de code quand j'aurai avancé sur d'autres projets Open Source) 😃

**Comment by PanierAvide** [comment]
Les mots comptent moins dans une communication de visu, car le non-verbal permet de mieux comprendre les intentions de la personne. À l'écrit, la communication se résume aux __mots__ (éventuellement émoticônes :stuck_out_tongue: ) donc la _forme_ prend une plus grande place dans l'interprétation des intentions. On se polarise bien sur la forme de l'interface web ici, autant le faire aussi pour les messages, même si je ne doute pas que tes intentions soient bonnes :wink:

Si j'accorde autant d'importance à ce sujet, c'est que l'épuisement des bénévoles et le manque de renouvellement dans la communauté posent question. En veillant à garder une communication bienveillante et distincte de celle qu'on aurait en entreprise, on acte qu'une personne bénévole dispose de ressources limitées, qu'elles soient temporelles, matérielles, ou en capacité à accumuler du stress. Les messages échangés sur les listes et dépôts sont visibles de tous, gravés dans le marbre, et peuvent encourager ou décourager de nouvelles têtes à nous rejoindre. Ça demande un effort supplémentaire, mais qui me semble pertinent compte tenu des enjeux humains qui y sont liés :sun_with_face:

**Comment by PanierAvide** [comment]
J'ai tenté de clarifier la légende et afficher les points orange plus tard, cf 6943d6c.
