### ISSUE TITLE
Documenter l'extraction des notes

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#23]
Les notes OSM sont extraites ici :
https://github.com/vdct/ProjetDuMois/blob/08137a7114d8e2eeeae220182634b84a21fab394/db/10_project_update.js#L67

Les termes configuré là :
https://github.com/vdct/ProjetDuMois/blob/7653b6015f023e8e25d59656be5ddf3c3fd37562/projects/2020-09_aed/info.json#L48

On pourrait rajouter **DAE**

### À quel fréquence les notes sont-elles mises à jour ?
La [doc](https://github.com/vdct/ProjetDuMois/blob/08137a7114d8e2eeeae220182634b84a21fab394/DEVELOP.md#base-de-données) mentionne :
* une  _"[mise] à jour [quotidienne de] la base avec les nouvelles contributions"_ 
* une _"[mise] à jour [régulière des] données depuis OSM"_

**Comment by PanierAvide** [comment]
La doc a été complétée, merci de la suggestion :wink:
