### ISSUE TITLE
Ajouter le kit d'urgence hémorragique

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#231]
Lorsqu'un DAE est indiqué, on pourrait imaginer la possibilité d'indiquer la présence d'un kit d'urgence hémorragique.
Voici à quoi cela ressemble :

![IMG_20211113_112145.jpg](https://user-images.githubusercontent.com/11553211/141643786-64b4310e-704a-415c-b1c5-994233714287.jpg)

Pour l'instant je ne l'ai vu qu'une seule fois, ici : https://www.openstreetmap.org/node/9247845317

Je ne sais donc pas si c'est pertinent : est-ce que vous l'avez déjà vu sur le terrain ?
Je n'ai pas de proposition de tag à ce stade

**Comment by PanierAvide** [comment]
Première fois que je vois ça, je saurais pas dire si c'est hyper courant ou pas.

**Comment by PanierAvide** [comment]
Après avoir arpenté un peu plus les DAE de France et de Navarre, j'en ai jamais croisé donc on va dire que c'est pas courant.
