### ISSUE TITLE
« Via OSM.org » → cassé

### ISSUE THREAD

**Issue by AntoninCurtit** [vdct/ProjetDuMois#236]
![image](https://user-images.githubusercontent.com/30950182/144640410-341b607d-cc4a-468c-b37b-7ca14b99578d.png)

Lorsqu'on veut ouvrir un node sur osm.org (ici depuis https://enedis.openstreetmap.fr/), l'URL débloque légèrement.

- Ex d'URL cassée : https://www.openstreetmap.org/7122618126
- Attendue : https://www.openstreetmap.org/node/7122618126

**Comment by overflorian** [comment]
C'est réparé ?

**Comment by AntoninCurtit** [comment]
Yes !

**Comment by overflorian** [comment]
Cool 😎
