### ISSUE TITLE
Afficher les photos des POIs

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#24]
Je propose d'afficher les photos existantes.

#### OSM
 (clés `image`, `mapillary`, `wikimedia_commons`, `wikidata` et valeurs multiples).

#### Wikimedia Commons
Certaines photos contiennent les template `{{On OSM}}` et `{{On OSMHydrant}}`
Dans ce cas, recopier les photos dans la clé `wikimedia_commons` de l'objet OSM.
* [{{On OSMHydrant}}](https://commons.wikimedia.org/w/index.php?title=File:DAE,_Jura_(France)_02.jpg&action=edit)
* [{{On OSM}}](https://commons.wikimedia.org/w/index.php?title=File:DAE_à_proximité_de_l%27église_Saint-Didier_de_Neyron.jpg&action=edit)

#### Mapillary
Certaines photos contiennent des [tags](https://help.mapillary.com/hc/en-us/articles/115001963751-Tagging).
Exemple avec "defibrillator".

[<img width="400" alt="Mapillary Tag" src="https://user-images.githubusercontent.com/2158081/91017868-12963600-e5ef-11ea-82f2-a23b0973a861.png">](https://www.mapillary.com/app/?lat=51.02608605277777&lng=4.475946268055623&z=17&pKey=OuYFC7SuU99iOnMR7gS4AQ&focus=photo&x=0.4788070456349108&y=0.5767571080164776&zoom=0)

**Comment by PanierAvide** [comment]
Lié à #15

**Comment by pyrog** [comment]
> Lié à #15

Pas spécialement, dans le sens ou ça serait utile d'afficher les photos (quelque soit leur source) dans le panneau de gauche et/ou dans une vignette au survol du POI.

Ça permet  de vérifier la qualité du positionnement, de la description…
De visualiser le DAE…
D'inciter les contributeurs à mettre des photos.

Au passage, ça serait pratique si les POIs avec photos pouvaient être mis en évidence.
(Comme dans [EWP](https://europeanwaterproject.org) avec un contour plus épais ?)
<img width="353" alt="EWP" src="https://user-images.githubusercontent.com/2158081/91019687-b5e84a80-e5f1-11ea-98be-285acf6bcb06.png">


J'oubliais, il faudrait proposer l'ajout de photos dans l'éditeur intégré de POI 😃

**Comment by PanierAvide** [comment]
C'est lié dans le sens où des bouts de code seront commun aux deux tickets, même si visuellement ça ressortira différemment.

**Comment by pyrog** [comment]
On peut s'inspirer du code de [MapComplete](https://github.com/pietervdvn/MapComplete) 😃
Exemple de [DAE](https://pietervdvn.github.io/MapComplete/aed.html?z=19&lat=44.904&lon=4.1557#element)

**Comment by PanierAvide** [comment]
C'est implémenté, les photos sont lues sur les objets OSM et notes, exemple https://projetdumois.fr/projects/2020-09_aed/map#map=18.23/47.995553/0.192394&sidebar=
