### ISSUE TITLE
Création de notes depuis ProjetDuMois ?

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#25]
La note [2319820](https://www.openstreetmap.org/note/2319820) semble avoir été créée par [Projet du mois](https://projetdumois.fr/projects/2020-09_aed/map#18/46.4839/6.3538).
Elle "répond" à la note [1880062](https://www.openstreetmap.org/note/1880062).

Est-ce une note créée manuellement pour tester l'application ou une nouvelle fonctionnalité pas encore documentée ?

PS: Ces notes sont visibles sur NotesReview sous forme de [carte](https://ent8r.github.io/NotesReview/?closed=true&map=18%2F46.4844%2F6.3545) et de [liste](https://ent8r.github.io/NotesReview/expert/?query=d%C3%A9fibrillateur&from=11%2F08%2F2019).

**Comment by PanierAvide** [comment]
Bonne question, ce n'est pas une action de ma part. À noter que le bouton "ajouter un défibrillateur" sert à créer une note si l'utilisateur n'est pas authentifié (là où il sert à modifier OSM directement si l'on est connecté). Peut-être deux choses à faire pour que ce soit plus clair :
* Mettre le texte "Vous êtes connecté : ce formulaire va créer un point directement dans OpenStreetMap" ou la version alternative note dans un encart bleu comme les autres notices
* Ne pas afficher le bouton "ajouter un défibrillateur" lorsque on est sur le détail d'une note et pas authentifié (pour éviter la double note)

**Comment by PanierAvide** [comment]
Fait
