### ISSUE TITLE
Ajouter tous les commerces

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#254]
Une fois que l'on aura publié les [premiers types de commerces](https://github.com/vdct/ProjetDuMois/issues/243), définissons tous les types de commerces pour lesquels nous allons afficher un formulaire.

Nous avons déjà défini le périmètre des types de commerces ici : https://wiki.openstreetmap.org/wiki/France/WikiProject_BAse_Nationale_des_Commerces_Ouverte_(BANCO)
La prochaine étape est peut-être de lister tous les commerces actuellement affichés sur CRO pour comparer.
@PanierAvide tu peux m'indiquer où trouver la liste complète stp ?

Sous quelle forme veux-tu la liste finale ? Est-ce qu'un CSV conviendrait ? J'imagine ça :
catégorie | type | mots-clefs | tag | icône
-- | -- | -- | -- | --
alimentation | boulangerie | pain,baguette,chocolatine,boulanger | amenity=bakery | boulangerie.svg

(les mots-clefs permettraient à l'utilisateur de retrouver textuellement un type de POI)
(pour simplifier, je propose de n'utiliser [plus qu'une seule icône](https://github.com/vdct/ProjetDuMois/issues/253))

On va avoir des exceptions à gérer car sur CRO on ne pouvait pas créer de POI depuis la carte. En conséquence certaines catégories regroupaient sur CRO différents POIs, par exemple "Argent" regroupait les banques et distributeurs.
Au contraire sur commerces.openstreetmap.fr, il faudra une catégorie unique pour chaque type de POI.

Voilà les screenshots du front-end pour rappel :
![image](https://user-images.githubusercontent.com/11553211/167132482-4e634afb-9fd5-4526-9abe-c40bd7a47e5f.png)
![image](https://user-images.githubusercontent.com/11553211/167131970-462ff70a-8227-420f-bab0-85c8a5f9b26a.png)
![image](https://user-images.githubusercontent.com/11553211/167132032-71e17eea-40c4-46c6-907d-f2a38585cd0d.png)
![image](https://user-images.githubusercontent.com/11553211/167132094-c8b40052-958b-4e96-a773-e9e88e50cb35.png)
![image](https://user-images.githubusercontent.com/11553211/167132161-1e1b21bb-153d-408c-9854-f5df6e887596.png)
![image](https://user-images.githubusercontent.com/11553211/167132208-6caed10a-36b3-457e-824b-9416bae0ec68.png)
![image](https://user-images.githubusercontent.com/11553211/167132272-86080e66-c435-41b5-929e-da5e07348fed.png)
![image](https://user-images.githubusercontent.com/11553211/167132322-6a10360e-515c-4531-96ab-048690533c63.png)
![image](https://user-images.githubusercontent.com/11553211/167132377-3e76fe9f-504c-4d91-a602-ed8014ae6d7b.png)
![image](https://user-images.githubusercontent.com/11553211/167132446-1f2766a6-0658-4eb0-8f78-53059ee5551b.png)

Et voilà la liste des POIs qu'il est possible de créer dans Organic Maps, pour comparaison :
![Screenshot_20220506-143925](https://user-images.githubusercontent.com/11553211/167133516-a4da9490-34d0-445b-b8fd-0483b41dd05c.jpg)
![Screenshot_20220506-143930](https://user-images.githubusercontent.com/11553211/167133725-a7dba4fe-335e-48af-8c30-7d5f1ac54b89.jpg)
![Screenshot_20220506-143935](https://user-images.githubusercontent.com/11553211/167133766-9171019a-ec62-4e49-88fe-08f813c5e473.jpg)
![Screenshot_20220506-143940](https://user-images.githubusercontent.com/11553211/167133774-687a6f07-5dbc-4851-bc2f-fe7945c47502.jpg)
![Screenshot_20220506-143945](https://user-images.githubusercontent.com/11553211/167133787-0e571c09-3341-40c4-a333-165bb0209a1f.jpg)
![Screenshot_20220506-143950](https://user-images.githubusercontent.com/11553211/167133795-3a392640-d0b3-45d0-9691-f07849748287.jpg)
![Screenshot_20220506-143955](https://user-images.githubusercontent.com/11553211/167133802-71d25bfb-073b-4ae0-948a-05ef8f661dbb.jpg)
![Screenshot_20220506-144001](https://user-images.githubusercontent.com/11553211/167133807-37a79f3e-f4c8-41f2-9711-a0c091ddbcb2.jpg)
![Screenshot_20220506-144006](https://user-images.githubusercontent.com/11553211/167133812-6a373586-7438-4118-b7f7-e92d9d55b2dd.jpg)
![Screenshot_20220506-144011](https://user-images.githubusercontent.com/11553211/167133818-ff884bd1-7fb2-4765-95c8-5cc20d31fd0c.jpg)
![Screenshot_20220506-144016](https://user-images.githubusercontent.com/11553211/167133819-6456a339-7c93-4c48-9eeb-d4f504668c46.jpg)
![Screenshot_20220506-144021](https://user-images.githubusercontent.com/11553211/167133823-7d94d95a-bf9f-4979-9bed-1245863155b4.jpg)
![Screenshot_20220506-144026](https://user-images.githubusercontent.com/11553211/167133826-31ae994c-e837-47f5-bda3-1163449d76a2.jpg)
![Screenshot_20220506-144031](https://user-images.githubusercontent.com/11553211/167133834-889e7f27-57b6-4e87-b01c-279da39d0cd2.jpg)
![Screenshot_20220506-144036](https://user-images.githubusercontent.com/11553211/167133838-0e8b8bd6-346a-479c-8390-1b1ebf24e8ca.jpg)

**Comment by nlehuby** [comment]
J'ajoute ce lien : https://github.com/osm-fr/osmose-backend/blob/master/merge_data/shop_FR.mapping.json

ça permet d'avoir la liste des commerces pour lesquels on a une analyse Osmose d'intégration (source SIRENE)

**Comment by overflorian** [comment]
Merci, c'est très utile.
De mon côté, en m'aidant de Google Adwords, j'ai identifié ces mots-clefs tappés par les internautes pour "boulangerie" :
pain,gateaux,nourriture,café,boulanger,viennoiserie,patisserie,fournil,boulangerie artisanale,meunier,brioche

j'ai l'impression que c'est bien ce que l'on cherche à identifier : les mots-clefs tapés par les humains pour trouver le terme "boulangerie", même si cela implique d'inclure "patisserie" ou "café" qui est un autre type de POI.

PS : la démarche n'est pas automatisable, je compte donc traiter chaque type de POI individuellement. Il est donc important de valider l'utilité de cette démarche.

**Comment by overflorian** [comment]
Nouvelle liste en cours de construction pour rajouter une centaine de commerces : https://docs.google.com/spreadsheets/d/1XIXz5pcgb2OYligpXAovfpmxLS0X97pWv0Z1xOzc7G8/edit?usp=sharing
(les colonnes oranges sont à remplir)

**Comment by nlehuby** [comment]
Les libellés présents dans le fichier ont été récupérés depuis la traduction en français des presets d'ID et la description du tag dans taginfo. 
Mais je propose qu'on mette plutôt en qualité le label et la description dans les data items, puis d'utiliser ça à la place d'ID et taginfo.

**Comment by PanierAvide** [comment]
Je ferme le ticket comme à priori ça a été intégré entre temps
