### ISSUE TITLE
Sous-titre BANCO

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#257]
Avec @PanierAvide on vient de décider de nommer BANCO l'instance commerces.openstreetmap.fr
On va utiliser le logo de "Ça Reste ouvert" (on l'utilise déjà ici https://www.data.gouv.fr/fr/datasets/base-nationale-des-commerces-ouverte) et mettre tout simplement le titre "BANCO".
Adrien je sais que l'on s'était mis d'accord pour le sous-titre "Construisons la BAse Nationale des Commerces Ouverte" @PanierAvide mais honnêtement, sérieusement, vraiment, trouvons autre chose.

Je propose :
- Tous les commerces de France dans OpenStreetMap
- Tous les commerces de France #OpenStreetMap
- Tous les commerces dans OpenStreetMap #OpenData
- Trouver tous les commerces de France
- Recensons les commerces de France #OpenStreetMap

@nlehuby @flacombe @vdct et autres @vdct @pyrog : avis bienvenus

**Comment by nlehuby** [comment]
je vote pour la proposition d'origine : c'est mieux d'expliciter l'acronyme si on veut qu'il prenne non ?

**Comment by overflorian** [comment]
OK, je ne m'attendais pas à ça ;) donc je vais justifier ma position : je pense que l'important pour un sous-titre de site web est d'expliquer à quoi il sert. Rien de pire que d'arriver sur un site internet duquel je ne comprends même pas l'utilité.
Je pense que notre plateforme entre dans la catégorie des sites dont la raison d'être peut ne pas être perçue par les utilisateurs, et donc les titres et sous-titres sont très importants pour cela.

Auparavant, nous avions pour titre "projet du mois" qui donnait déjà une première idée, mais maintenant le titre est plus une marque abstraite : BANCO.
Du coup je pense qu'il y a besoin d'expliciter ce que l'utilisateur peut faire sur ce site.

Le plan C est d'[expliciter l’acronyme dans l'image](https://github.com/vdct/ProjetDuMois/issues/258) et d'expliquer l'utilité du site en sous-titre :
![logos-projet-du-mois-texte-sous-titre-en-contexte](https://user-images.githubusercontent.com/11553211/167366897-329e8d32-f5de-405a-96f9-aa875dbd4ee1.png)

Néanmoins je n'y suis pas favorable : cela rajoute de la complexité.
À moins ... à moins que l'on ne rende le sous-titre moins visible :
![logos-projet-du-mois-texte-sous-titre-en-contexte2](https://user-images.githubusercontent.com/11553211/167367320-69fa59ad-9fb9-4003-bd76-585c015f0081.png)

Et là on commence à parler :P

**Comment by nlehuby** [comment]
j'aime bien ton plan C avec en petit l'explication de l'acronyme.

"Les commerces de France dans OpenStreetMap" me semble pas mal comme sous-titre (le "tous" est un peu excessif vu qu'on ne va pas gérer toutes les catégories avant un moment)

**Comment by overflorian** [comment]
ça me va. @PanierAvide ?

**Comment by PanierAvide** [comment]
OK pour ça
