### ISSUE TITLE
Lien cassé vers le logo dans la page principale

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#26]
<img width="300" alt="Liens cassé" src="https://user-images.githubusercontent.com/2158081/91129654-aa0c8f00-e6aa-11ea-91a3-fea137b3bdea.png">

J'ai cherché un moment avant de trouver son code 😄 
C'est [README.md](https://github.com/vdct/ProjetDuMois/blob/master/README.md) qui est inclus, mais du coup le lien vers le logo ne fonctionne plus depuis le site principal.

Ça serait peut-être plus clair de faire apparaitre ce texte avec un menu **À propos** ?

**Comment by PanierAvide** [comment]
Corrigé
