### ISSUE TITLE
tag pour les magasins de CBD

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#264]
Hello, suite à https://github.com/vdct/ProjetDuMois/issues/243, les [magasins qui vendent du CBD](https://wiki.openstreetmap.org/wiki/FR:Tag:shop%3Dcannabis) sont taggés shop=cannabis + cannabis:cbd=yes
Or je ne vois pas apparaitre ce POI https://www.openstreetmap.org/node/2522405259 sur la carte de ce projet https://commerces.openstreetmap.fr/projects/2022-01_cbd/map#map=14.82/48.81409/2.32124
Help !

**Comment by overflorian** [comment]
À bien y regarder, il n'y a pas non plus de points verts pour les stations-services ou les super-marchés non plus. Je vois que les stats ne font pas de mention de données OSM non plus. Bug ?

**Comment by overflorian** [comment]
Ok sorry je suis trop rapide !

**Comment by PanierAvide** [comment]
C'est bon les points sont opérationnels, un bug dans la mise à jour des données bloquait le tout.

**Comment by overflorian** [comment]
C'est bon, j'ai bien mon magasin de CBD à Montrouge, je suis content ;)
Merci
