### ISSUE TITLE
Champ de recherche trop réactif

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#27]
En cherchant "trifoulli", je n'ai pas le temp de saisir "-les-oies" que la carte a automatiquement été placée sur la première réponse.

Idem en copiant "geo:48.8500551,2.2863669", je n'ai pas le temps d'effacer le préfixe "geo:"

**Comment by PanierAvide** [comment]
J'ai modifié quelques éléments pour rendre la recherche moins "réactive".
