### ISSUE TITLE
Commerces : délais dans le rafraichissement des données

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#270]
Bonjour !

Des soucis de fraicheur sont constatés sur Banco.
Par exemple sur Marseille, cette boulangerie a été mise à jour il y a 12 heures et n'apparait toujours pas complétée sur l'éditeur carto.
https://www.openstreetmap.org/node/1485011637

![image](https://user-images.githubusercontent.com/5690599/179480087-b023c0be-a6b0-424e-aa41-ebdf328afb9d.png)

Quel est le délais de rafraichissement sur cette instance ?

**Comment by PanierAvide** [comment]
Bonjour François,

En théorie l'instance est actualisée toutes les heures pour la partie carte, et une fois par jour pour les stats. Je vais regarder d'où peut venir le souci.

**Comment by PanierAvide** [comment]
Le souci est en théorie réglé, j'ai passé le rafraîchissement à toutes les 3h car je pense que le traitement n'a pas toujours le temps de finir en 1h et pouvait donc être lancé plusieurs fois. Il y avait aussi des fichiers qui n'étaient pas écrasés la fois suivante s'il y avait eu des erreurs au précédent traitement. En tout cas la boulangerie en question est bien à jour : https://commerces.openstreetmap.fr/projects/2022-01_shop/map#map=18.33/43.360611/5.31443&sidebar=

Merci encore pour le retour :wink:

**Comment by flacombe** [comment]
Merci d'avoir fait le nécessaire !
