### ISSUE TITLE
Nombre de contributeurs revu à la baisse en cours de projet

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#274]
Bonsoir,

Je constate un comportement étrange de pdm suite à plusieurs gros changeset hier soir.
Voici le déroulé des événements :

1. Situation initiale au 02/10 18h
Contributeurs : 841

2. Changeset sur ~20 000 objets en cours de soirée, du nettoyage principalement d'objets existants, uniquement 150 ajouts.

3. Refresh du projet en cours de nuit.

4. Situation finale au 03/10 21h
Contributeurs : 640

J'ai l'impression qu'avoir édité beaucoup d'objets existants a masqué des contributions antérieures et fait baissé le nombre de contributeurs.
N'est-ce pas inattendu ?

Selon moi, un contributeur ayant contribué à un instant t doit être comptabilisé sur toute la durée du projet. Ajouter des tags sur ses contributions initiales ne doit pas lui retirer le mérite de sa première contribution.

**Comment by PanierAvide** [comment]
Bonjour,

Effectivement ce n'est pas le comportement souhaité, on veut bien que chaque contribution dans le temps reste associé à l'utilisateur, même si quelqu'un repasse plus tard sur l'objet.

La modification en question a entraîné l'exclusion d'objets qui étaient auparavant affichés dans ton projet du mois ? Est-ce que ce ne serait pas [cette commande](https://github.com/vdct/ProjetDuMois/blob/master/db/10_project_update.js#L282) qui zappe certains objets et qui donc entraîne les manques dans les statistiques suivantes ?

**Comment by flacombe** [comment]
Hello !

Étonnamment non, le décompte des objets est bon, la courbe n'a pas décru.
J'ai l'impression que c'est du coté de l'inventaire des changes que ça a sauté, pour une raison inconnue (et je n'ai pas l'état initial de la table pour comparer).

Ce qui devrait nous alerter, c'est qu'un traitement quotidien incrémental puisse altérer des changes passés, qui ne devraient disparaître que lors d'une refresh complet du projet.

**Comment by flacombe** [comment]
Il y a aussi ce point dont je viens de m'apercevoir : 1419 utilisateurs différents dans la table de changes, mais seulement 640 remontent sur l'interface.
Pourquoi ça ?

```
user=> select count(distinct userid) from pdm_changes where project='2021-01_poteaux';
 count 
-------
  1419
(1 ligne)
```

**Comment by flacombe** [comment]
Ce soir (donc traitement de ce matin), la situation a évoluée à 828 contributeurs impliqués.
Je n'ai absolument rien touché.

C'est vraiment louche non ?

Et toujours :
```
user=> select count(distinct userid) from pdm_changes where project='2021-01_poteaux';
 count 
-------
  1424
(1 ligne)
```

**Comment by flacombe** [comment]
Suite à #295 et #309, ces décalages ne sont plus observés.

J'ai constaté une différence entre les comptes d'utilisateurs de `pdm_changes` et `pdm_user_contribs` par le fait que toutes les contributions (en particulier delete) n'étaient pas valorisées dans `pdm_projects_points`. C'est donc normal.
