### ISSUE TITLE
Rendre les identifiants et les liens cliquables dans la liste d'attributs

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#28]
### Description
Mettre des liens sur les URLs, les images, les identifiants serait très utile 😃 
La liste des tags et des URL est disponible dans OSM Data ou Wikidata.
Certains clés OSM ont des valeurs multiples séparées par `;`

Voir aussi #24 

### Exemples
nœud [2556966391](https://www.openstreetmap.org/node/2556966391), sur [Projet du mois](https://projetdumois.fr/projects/2020-09_aed/map#18/48.850053/2.286369).
- name=Bibliothèque Beaugrenelle
- phone=+33 1 45 77 63 40
- source=cadastre-dgi-fr source : Direction Générale des Impôts - Cadastre. Mise à jour : 2013
- amenity=library
- website=[https://www.paris.fr/equipements/bibliotheque-andree-chedid-1734](https://www.paris.fr/equipements/bibliotheque-andree-chedid-1734)
- alt_name=Bibliothèque Andrée Chedid
- emergency=defibrillator
- wheelchair=no
- internet_access=wlan
- wikimedia_commons=[File:Bibliothèque Andrée Chedid, 36 Rue Emeriau, 75015 Paris.jpg](https://commons.wikimedia.org/wiki/File:Biblioth%C3%A8que_Andr%C3%A9e_Chedid,_36_Rue_Emeriau,_75015_Paris.jpg)
- internet_access:fee=no
- internet_access:operator=Mairie de Paris

nœud [7798797745](https://www.openstreetmap.org/node/7798797745), sur [Projet du mois](https://projetdumois.fr/projects/2020-09_aed/map#18/47.175017/-0.33798).
- access=yes
- indoor=yes
- source=Direction Générale de la Santé
- operator=Commune de Doue-en-anjou
- emergency=defibrillator
- mapillary=[UA8nxTt9iaeB8YgkSfEx-w](https://www.mapillary.com/app/?focus=photo&pKey=UA8nxTt9iaeB8YgkSfEx-w)
- ref:FR:SIREN=[200065225](https://entreprise.data.gouv.fr/sirene/200065225)
- surveillance=no
- ref:FR:GeoDAE=[8557](https://geodae.atlasante.fr/api?id=8557)
- security_desk=no
- reception_desk=no

noeud [4446530170](https://www.openstreetmap.org/node/4446530170), sur [Projet du mois](https://projetdumois.fr/projects/2020-09_aed/map#18/44.90368/4.155986)
- image=[https://i.imgur.com/3Uef2Ao.png](https://i.imgur.com/3Uef2Ao.png)
- access=yes
- indoor=no
- emergency=defibrillator
- defibrillator:location=sur la façade extérieure de la mairie côté rue de la traverse

**Comment by PanierAvide** [comment]
Il y a une bibliothèque JS qui serait susceptible de gérer ça automatiquement ?

**Comment by pyrog** [comment]
Pas à ma connaissance. Chaque projet doit réinventer la roue 😉 

Mais c'est une bonne idée 👍

**Comment by PanierAvide** [comment]
C'est sûrement de ça dont on a besoin https://github.com/JOSM/tag2link

**Comment by PanierAvide** [comment]
C'est fait, ce sera déployé d'ici quelques heures
