### ISSUE TITLE
Intégration Osmose KO sur certains types de "commerces"

### ISSUE THREAD

**Issue by nlehuby** [vdct/ProjetDuMois#281]
Dans l'éditeur commerces
Lorsque
- je clique sur un point rouge "commerce à localiser" d'un dentiste (et sachant que le type de commerce dentiste n'existe pas dans BANCO)
- quand je sélectionne "intégrer ce commerce"
alors j'ai un formulaire de commerce vide. 

Je m'attends à ce qu'il soit rempli avec les infos issues d'Osmose (d'autant qu'Osmose a les infos des tags pertinents)

images:
![Mon dentiste à intégrer](https://user-images.githubusercontent.com/919962/195568449-352841d1-3fb8-4e87-9c65-4ec431bc4442.png)
![Mon dentiste tout vide](https://user-images.githubusercontent.com/919962/195568465-ab3e9593-2169-4bd6-bd82-0c15169227c5.png)

**Comment by nlehuby** [comment]
Une solution de contournement serait d'ajouter dans l'éditeur tous les types de commerces gérés par Osmose (même si on trouve discutable de considérer les dentistes comme des commerces) ou de filtrer plus finement les analyses Osmose.

**Comment by PanierAvide** [comment]
Je suis parti sur un filtre plus fin des points ramenés par Osmose, intégré via https://github.com/PanierAvide/EditeurCommercesOSMFR/commit/3b0a226db98e6554975335798e723d5c6686bbb9 et en cours de déploiement :wink:
