### ISSUE TITLE
Rajouter un champ "horaires d'ouvertures"

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#282]
Demandé par un utilisateur, la possibilité d'afficher/modifier les horaires d'ouvertures.
Ce champ étant utilisable sur tous les types de commerces, je pense qu'il serait bon d'enfin s'en préoccuper.

# Solution 1 - quick & dirty
Ajouter un simple champ texte + lien vers YoHours

# Solution 2 - éditeur intégré
Développer un éditeur d'horaires d'ouverture. Temps estimé : infini !

Même si je suis réticent, en terme d'UX, à adopter la solution 1, je sens que nous n'aurons jamais la motivation pour la solution 2. Donc la mort dans l'âme, je propose d'implémenter la solution 1.

**Comment by PanierAvide** [comment]
Doublon de #212 :wink:
