### ISSUE TITLE
Afficher le fond de carte pour l'intégralité du territoire français

### ISSUE THREAD

**Issue by adrienandrem** [vdct/ProjetDuMois#283]
Les rues, bâtiments et toponymes n'[apparaissent pas sur le fond de carte](https://commerces.openstreetmap.fr/projects/2022-01_shop/map#map=12.44/-21.33644/55.57068).
Ils sont pourtant [visibles pour La Rochelle](https://commerces.openstreetmap.fr/projects/2022-01_shop/map#map=12.44/46.16676/-1.13018) par exemple.

**Comment by adrienandrem** [comment]
Éventuellement à rattacher à #76.

**Comment by PanierAvide** [comment]
Bonjour, effectivement c'est entièrement lié au sujet #76, et aussi à https://github.com/osm-fr/infrastructure/issues/399. Je ferme le ticket ici, mais la discussion continue dans les autres :wink:
