### ISSUE TITLE
Restauration du projet bornes de recharge

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#288]
Bonjour chers amis

Est-ce possible de ranimer le projet du mois des bornes de recharge s'il vous plaît ?

Je peux faire une pull request avec quelques modifs dans les textes sur la page du projet si nécessaire.
J'ai cru comprendre que les stats sont maintenant observées et actualisées tous les jours. C'est bien ça ?

Donc je n'aurais qu'à mettre à jour les textes, autre chose ?

Attention, pas de dev supplémentaire.

**Comment by cayenne17** [comment]
Bonjour @flacombe 
C'était moi qui avait MAJ les stats https://github.com/vdct/ProjetDuMois/pull/277

**Comment by PanierAvide** [comment]
Salut,

Oui possible de relancer le projet, c'est à dire le remettre en premier plan par rapport aux autres sur le site ?

Les statistiques de contribution (graphiques) sont effectivement actualisées en continu, contrairement à avant où ça s'arrêtait à la fin de la période prévue du projet.

**Comment by flacombe** [comment]
Merci pour vos réponses

J'ai proposé #290 pour les modifs nécessaires.

A vous lire là bas

**Comment by cayenne17** [comment]
> Merci pour vos réponses
> 
> J'ai proposé #290 pour les modifs nécessaires.
> 
> A vous lire là bas


"seuls 19 000 environ seraient décrits"

Avec une requête API Overpass, j'en trouve 9900 Nœud~
![image](https://user-images.githubusercontent.com/47927025/212475717-609bdae6-2b12-4c85-8398-c5532a06a15d.png)

```
[out:json][timeout:180];

({{geocodeArea:France}}; )->.searchArea;

(
	nw[amenity=charging_station](area.searchArea);

);
out body;
>;
out skel qt;```

a moins que tu ai multiplié par `capacity` ?

**Comment by flacombe** [comment]
Oui, parce que je parle des points de charge et non des bornes. C'est une subtilité que je cherche à préciser le plus souvent possible pour expliquer cette différence aux contributeurs.

**Comment by flacombe** [comment]
La documentation du wiki a été mise à jour.
https://wiki.openstreetmap.org/wiki/FR:Project_of_the_month/bornes_vehicules_electriques

Il doit rester quelques détails à affiner, j'en ai bien conscience

**Comment by nlehuby** [comment]
Si on relance un projet du mois, je pense que ça serait mieux de créer une nouvelle page de projet du mois: là, on a des liens morts, des trucs qui parlent de mars 2020, etc c'est confus et pas super engageant

**Comment by flacombe** [comment]
La page a été mise à jour @nlehuby, où sont les liens morts ?

**Comment by nlehuby** [comment]
il y a au moins le thème MapContrib et la page NoteReview qui ne sont plus fonctionnels

**Comment by flacombe** [comment]
Ok, je les ai supprimé

**Comment by PanierAvide** [comment]
Je viens de déployer la PR #290, le projet est caché en attente de démarrage (bug ?) https://projetdumois.fr/projects/2020-03_evcharging

**Comment by flacombe** [comment]
Ah oui !
J'ai mis un début en févirer 2023.

Je vais corriger et mettre début au 1er janvier plutot

**Comment by flacombe** [comment]
Bonjour

Dans la suite de ce fil, je constate que le 01/02 est désormais passé.
Regardes le graphe des stats du projet @PanierAvide : les courbes bornes à importer et bornes à compléter commencent au 01/02 alors qu'elles allaient jusqu'en 2020 avant.

Peut-être un soucis de filtre ? (Je peux ouvrir une issue dédiée si nécessaire)
