### ISSUE TITLE
Statistiques : Scores et badges

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#29]
**5** éditions dans les [statistiques](https://projetdumois.fr/projects/2020-09_aed/#statistics) et **3** participations dans la [page de l'utilisateur](https://projetdumois.fr/users/pyrog).
Contributeur | Editions | Participations
-- | -- | --
[pyrog](https://projetdumois.fr/users/pyrog) | 5 | 3
[PanierAvide](https://projetdumois.fr/users/PanierAvide) | 3 | 5
[marius851000](https://projetdumois.fr/users/marius851000) | 3 | 1
[Xavier Ulrich](https://projetdumois.fr/users/Xavier%20Ulrich) | 2 | 1

**Comment by PanierAvide** [comment]
C'est sûrement le libellé qui n'est pas clair (ouvert aux suggestions) :
- 5 éditions = nombre d'objets modifiés pendant ce projet du mois
- 3 participations = j'ai au moins fait une modification sur 3 projets du mois différents

**Comment by pyrog** [comment]
Tu pourrais afficher par exemple **3** éditions dans **5** projets du mois.

Et gérer les pluriels 😉
(Le code i18n le fait me semble-t-il).

**Comment by PanierAvide** [comment]
Donc un cumul du nombre de contributions à travers tous les projets du mois dans la page de statistiques ?

**Comment by pyrog** [comment]
Le badge "A participé au projet du mois" est inutile car si on est dans les statistiques, c'est forcément qu'on a participé 😄

Pour les **badges** dans la page du **contributeur**, il faudrait peut-être les regrouper :

- 1 badge par projet, avec un surimpression ou au dessous le classement.
- Le popup donne le nom du projet.

**Comment by pyrog** [comment]
> Donc un cumul du nombre de contributions à travers tous les projets du mois

Non, car ce sont les statistiques du projet en cours ?

Ou alors en afficher 2 : un pour le dernier projet, un pour tous les projets.

**Comment by PanierAvide** [comment]
Ben j'imaginais plutôt la page de statistiques personnelles comme transverse à tous les projets. Mais en soit un rappel de ses statistiques sur le projet en cours est également possible.

**Comment by pyrog** [comment]
Badges (pour les trois premiers) à distribuer à la fin du projet ?

**Comment by PanierAvide** [comment]
C'est déjà implémenté ça, par projet chaque jour les 3 premiers ont un badge.

**Comment by pyrog** [comment]
Je parlais du projet en cours : ces 4 badges n'ont pas vraiment de sens 😃

**Comment by PanierAvide** [comment]
J'ai sûrement pas compris où tu voulais en venir, car pour moi les badges distribués ont du sens. Je ne sais pas si c'est une histoire de présentation des badges, de temporalité de distribution des badges ou autre chose.

Le plus simple serait sûrement que tu proposes un maquette de présentation pour la page utilisateur et/ou le podium sur la page du projet. Un dessin vaut mieux qu'un long discours :wink:

**Comment by pyrog** [comment]
C'est bien une question de **temporalité** 😃
Le score évolue tout le temps, donc il faut attendre la fin du mois pour attribuer des badges.

A moins que tu attribues le badge "abc" pour avoir ajouté **10 DAE**, "def" pour en ajouter **50**…

Pour le podium en cours, afficher le badge de la participation au projet en cours est une forme de _lapalissade_ 😄
Par contre ça a du sens dans la page du contributeur 😃

**Comment by pyrog** [comment]
Tu as modifié les badges 🌞

**Comment by PanierAvide** [comment]
C'est vrai, je peux donc fermer ce ticket :partying_face:
