### ISSUE TITLE
Logos cassés

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#298]
Hey, les logos des toilettes et des arrêts de bus ne s'affichent plus sur la homepage :

![image](https://github.com/vdct/ProjetDuMois/assets/11553211/e1bb1086-1904-466d-a7e1-361fd99742fd)

Help !

**Comment by nlehuby** [comment]
sauf erreur de ma part, on n'a pas de logo pour ces projets du mois, ni de logo de projet du mois générique qui pourrait être utilisé à la place.

**Comment by overflorian** [comment]
Voici un oubli de corrigé :
![image](https://github.com/vdct/ProjetDuMois/assets/11553211/a2a80cab-3df0-4bfa-99aa-746ef22bda81)
![image](https://github.com/vdct/ProjetDuMois/assets/11553211/4440a41e-4c9f-47bf-98a7-61e26208ae2a)

Tous les fichiers SVG : https://nextcloud.junglebus.io/index.php/s/PWP6dY7AffeRAst

**Comment by overflorian** [comment]
Hello, je vois que les logos n'apparaissent toujours, le fix de @nlehuby n'a pas fonctionné ? Merciiii

**Comment by PanierAvide** [comment]
Les logos sont cassés, cf https://github.com/vdct/ProjetDuMois/pull/300#discussion_r1274470356

**Comment by PanierAvide** [comment]
De souvenir ça devait être les deux, et oui si tu répares les logos je pourrais les intégrer :wink:
