### ISSUE TITLE
Implémenter le logo

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#3]
J'ai mis dans le fichier la police d'écriture à utiliser pour le titre qui est https://www.dafont.com/fr/fetteegyptienne.font avec le logo et le favicon : 
[Logo projet du mois.zip](https://github.com/vdct/ProjetDuMois/files/4695864/Logo.projet.du.mois.zip)

**Comment by overflorian** [comment]
Pour la page d'accueil, @PanierAvide en fonction de ta motiv' tu peux :
- Intégrer juste le logo (dans le .zip ci-dessus) et rajouter le titre à sa droite
- Intégrer un bandeau de 1110px de large (largeur max du site) qui se rétrécit jusqu'au moment où il n'y a plus la place et on n'affiche plus que le logo. Je viens de te faire ça : [bandeau 1110px.zip](https://github.com/vdct/ProjetDuMois/files/4725181/bandeau.1110px.zip)
- Intégrer une animation de folie comme sur github https://github.com/vdct/ProjetDuMois/issues/6 ouiiiiiiii :P

**Comment by PanierAvide** [comment]
Implémenté via b5948ac
