### ISSUE TITLE
Statistiques : graphiques

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#30]
Je propose de mettre une échelle dynamique  car on a l'impression que le projet n'avance pas :

- Axe de gauche : de ? (valeur actuelle)  à 18 000 (nombre au début du projet) 
- Axe de droite : de [6 430](https://overpass-turbo.eu/s/XpZ) (au début du projet) jusqu'à [6 454](https://overpass-turbo.eu/s/Xq0) (à ce jour)
- Axe horizontal :
  - Localiser les date
  - Mettre un libellé par jour sur l'axe horizontal.

<img width="50%" alt="Avancement" src="https://user-images.githubusercontent.com/2158081/91328099-b8e86400-e7c6-11ea-84b6-d0e58f9a974c.png">

**Comment by PanierAvide** [comment]
J'ai modifié l'affichage des graphiques :
- Arrondi des valeurs en x à la journée
- Affichage forcé des jours comme étiquette en x
- Utilisation d'une échelle logarithmique de valeurs si moins de 30% des tâches Osmose ont été résolues

**Comment by pyrog** [comment]
> Utilisation d'une échelle logarithmique de valeurs si moins de 30% des tâches Osmose ont été résolues

La courbe reste désespérément plate : elle a besoin d'un choc électrique 😆 
<img width="30%" alt="Avancement" src="https://user-images.githubusercontent.com/2158081/91328099-b8e86400-e7c6-11ea-84b6-d0e58f9a974c.png"> <img width="30%" alt="ECG plat" src="https://user-images.githubusercontent.com/2158081/91399355-22f02000-e83e-11ea-8765-8433839c1c0b.png">

**Comment by PanierAvide** [comment]
Après ça devient compliqué d'afficher de gros changements là où il n'y en a encore que peu. Ceci dit il y a aussi un problème sur la génération des stats de comptage en prod, je suis en train de travailler dessus.

**Comment by pyrog** [comment]
L'échelle linéaire mais zoomée entre valeurs initiales et valeurs finales devraient fonctionner avec une échelle par axe 😉 

Il serait intéressant de générer des courbes pour les projets précédents pour avoir une idée du résultat.
(pour les tests, ça peut se faire avec un outil externe : tableur, ohsone…)

**Comment by PanierAvide** [comment]
Hmmm. Si tu as un exemple de configuration Chart.js qui fonctionne mieux que ce j'ai en l'état je suis preneur. Je t'avoue que là je vois mal comment aller plus loin sur Chart.js pour avoir mieux que ça.

Les projets précédents ont bien leur courbe générée, exemple : https://projetdumois.fr/projects/2020-03_evcharging#statistics

**Comment by pyrog** [comment]
La courbe des postes de transformation électrique à intégrer reste plate (même avec 10 000 postes intégrés) 😞
Avec une échelle logarithmique, il est difficile de voir la progression des ajouts dans OSM (+9 000~)
<img width="30%" alt="Capture d’écran 2020-08-27 à 08 37 04" src="https://user-images.githubusercontent.com/2158081/91402171-49fc2100-e841-11ea-99ff-553a803c6d56.png">

Je ne connais pas Chart.js. Si il est "limité", il est possible d'utiliser un autre script au de gérer ça côté serveur…

> Les projets précédents ont bien leur courbe générée

Merci, je n'avais pas assez fait défiler l'écran.

Le libellé "Avancement" n'est pas trop parlant.
Peut-être rappeler le nom du projet (ou mettre son icône pour cela) ?

**Comment by pyrog** [comment]
Pas directement lié au graphique mais relatif à la "motivation" :
<img width="25%" alt="Statistiques" src="https://user-images.githubusercontent.com/2158081/91400171-80d13780-e83f-11ea-8828-4060a41ef92b.png">

On pourrait indiquer le nombre de DAE intégrés (en plus du pourcentage) soit [132](https://overpass-turbo.eu/s/XqR) à ce jour.

**Note :** certains DAE existent probablement déjà dans OSM mais ils n'ont pas encore de tag `ref:FR:GeoDAE`

**Comment by pyrog** [comment]
https://www.chartjs.org/samples/latest/scales/linear/min-max.html
