### ISSUE TITLE
[BUG] Le PDM, sensible à la casse 🤔 

### ISSUE THREAD

**Issue by Darkham42** [vdct/ProjetDuMois#303]
Bonjour,

Tout d'abord merci pour la mise à disposition de cet outil fort pratique !

J'ai constaté un soucis que j'ai du mal à comprendre malgré le fait d'avoir énormément consulté le code et surtout les scripts sql. En effet, un identifiant entièrement en majuscule m'a empêché d'avancer...

Illustrons ce soucis par un exemple :
Créons un projet CINEMA, avec du coup l'identifiant `2023_CINEMA` et le title `CINEMA`, en consultant ma base de donnée, j'ai bien les tables suivantes :
```
 public | pdm_project_CINEMA                  | view              | postgres
 public | pdm_project_CINEMA_point        | table             | postgres
 ```
Toutefois lorsque je fais tourner les scripts (le [db/30_projects_update.js](https://github.com/vdct/ProjetDuMois/blob/0c323c2b4cfeac11eb9d54d4e92b1aaf3c9b0f87/db/30_projects_update.js) en particulier si je ne m'abuse), il me renvoie l'erreur suivante :
```
psql:/opt/pdm/db/33_changes_boundary.sql: 12: ERROR: relation "pdm_project_cinema" does not exist
LINE 3: FROM pdm_project_CINEMA
```
On peut constater dans l'erreur une différence de casse entre ce qu'il attend et ce qui est en base de donnée...

J'ai du coup mis en minuscule l'id du projet et depuis plus de soucis... Mais je ne vois rien dans le code qui ferait un lowerCase de cet id, donc je ne peux pas contribuer pour corriger ce soucis. Ou alors le soucis est tout autre, mais ça me semble peu probable. Je m'en remets donc à vous !

**Comment by PanierAvide** [comment]
Bonjour,

Merci pour ce retour détaillé. Il y a de grandes chances que ce problème de casse soit du côté de PostgreSQL, à savoir que si un nom de colonne ou de table est dans une requête SQL sans être entouré de double-guillemets `"`, il est automatiquement repassé en minuscules. Deux façons de corriger :

- Documenter que les noms de projets sont à toujours mettre en minuscules (ça prendra quelques minutes à faire)
- Modifier toutes les requêtes SQL pour entourer les noms de tables et colonnes de `"` (un peu plus long, et besoin d'être testé de fond en comble)
- 
Cordialement.

**Comment by Darkham42** [comment]
Super, du coup je pense que le plus simple sera de le mettre dans la documentation en effet.
