### ISSUE TITLE
[Enhancement] Fichiers projets

### ISSUE THREAD

**Issue by Darkham42** [vdct/ProjetDuMois#304]
Re-bonjour,

Je me suis tâté à faire une Pull-Request pour commencer ce travail, mais je ne sais pas trop comment m'y prendre et je n'ai pas autant de connaissance que vous. Mais il serait intéressant de documenter les fichiers `info.json` car certaines valeurs peuvent ne pas sembler utiles/importantes mais ne pas les mettre provoque des soucis sur l'interface web (typiquement je pense à `links.osmwiki` ou encore `editor.all.hashtags` par exemple).

Et pour reprendre le début de cette issue, je ne sais pas comment m'y prendre, mais peut-être faudrait t-il mettre toute la documentation dans le Wiki GitHub afin de tout rassembler et retravailler les md qui servent de documentation aujourd'hui ? Je veux bien donner un coup de main si besoin 😉

**Comment by PanierAvide** [comment]
Il y a en effet quelques trous dans la doc https://github.com/vdct/ProjetDuMois/blob/master/DEVELOP.md#project-configuration

Je n'ai jamais trop utilisé la doc wiki Github, j'ai l'impression que ça complique la portabilité du dépôt si l'on doit migrer sur une autre plateforme. Je préfèrerais que l'on reste sur la doc Markdown fichier (si ça semble raisonnable).

**Comment by Darkham42** [comment]
D'accord, pas de soucis je regarderais ce que je peux combler des trous que j'ai repéré directement dans le markdown.
