### ISSUE TITLE
Proposer une mise jour d'un DAE dans OSM sans ref:FR:GeoDAE

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#31]
Un POI vert est affiché. Projet du mois ne propose pas de compléter les données avec celles de l'ARS.

https://projetdumois.fr/projects/2020-09_aed/map#15.04/46.66416/5.54092
https://www.openstreetmap.org/node/5699800071

**Comment by PanierAvide** [comment]
En effet, l'analyse Osmose pour l'instant ne fait que la proposition d'intégration quand il n'y a pas de défibrillateurs aux alentours. Ce qui n'est probablement pas plus mal vu les questions qu'on a eu et pas encore résolues sur les identifiants de GéoDAE.

**Comment by pyrog** [comment]
On a les réponses 😉 
L'identifiant officiel est la colonne `gid` est pas `c_gid`.

Voici un extrait du fichier publié le 26 août à 19:30 :
```csv
gid,c_etat_valid,c_nom,c_x_coor2,c_y_coor2,c_lat_coor1,c_long_coor1,c_xy_precis,c_id_adr,c_adr_num,c_adr_voie,c_com_cp,c_com_insee,c_com_nom,c_acc,c_acc_lib,c_acc_pcsec,c_acc_acc,c_acc_etg,c_acc_complt,c_photo1,c_photo2,c_disp_j,c_disp_h,c_disp_complt,c_date_instal,c_etat_fonct,c_etat,c_application_provenance,c_doublon,c__edit_datemaj,c_srid_origin
1,validées,DAE G3 CARDIAC SCIENCE,,,47.7531,-3.38071,0.999993,56121_5562_00001,1,Boulevard Yves Demaine,56100,56121,Lorient,Intérieur,0,0,1,0,Dépôt de bus CTRL,,,{7j/7},"{""heures ouvrables""}",,,En fonctionnement,Actif,,0,2020/02/04 09:43:09.179,'EPSG:4326'::character varying
2,validées,DAE G5 CARDIAC SCIENCE,,,47.7552,-3.36392,1,56121_0990_00009,9,Cours Louis de Chazelles,56100,56121,Lorient,Intérieur,0,0,1,0,Boutique Transports & Déplacements CTRL,,,"{lundi,mardi,mercredi,jeudi,vendredi,samedi}","{""heures ouvrables""}",,,En fonctionnement,Actif,,0,2020/02/04 09:47:09.206,'EPSG:4326'::character varying

```
<img width="25%" alt="GeoDAE 16305" src="https://user-images.githubusercontent.com/2158081/91445302-3b7c2c80-e876-11ea-89b4-6145f37e6651.png">

C'est un problème car le but de PdM est d'intégrer les DAE publiés officiellement.

Il y a aussi un risque de doublon 😞 

- [Carte PdM](https://projetdumois.fr/projects/2020-09_aed/map#21.97/47.28650744/4.79770749)
- Nœud [5001724490](https://www.openstreetmap.org/node/5001724490)
- `gid` = 16305
   - https://carto.atlasante.fr/IHM/cartes/ressources/dae/5f2c13294c9ac.jpeg
   - https://carto.atlasante.fr/IHM/cartes/ressources/dae/5f2c13294ebab.jpeg

**Comment by PanierAvide** [comment]
Points dans le désordre :
- Je suis en train de mettre à jour l'analyse Osmose pour basculer sur `gid`
- Pas de risque de doublon, c'est Osmose qui gère ça (vérification sur l'identifiant ou s'il y a un DAE dans un rayon de 50 mètres)
- J'ai pas trop d'explications de pourquoi le doublon s'est présenté, peut-être du fait qu'il manque la partie mise à jour d'un DAE existant ?

**Comment by pyrog** [comment]
Doublon dans les données GéoDAE (gid=1482 et 1580) et dans la base OSM ([node 2932971840 ](https://www.openstreetmap.org/node/2932971840)
Les deux premiers sont en attente de validation et décrivent le même DAE.

C'est à [Champagne-en-Valromey](https://projetdumois.fr/projects/2020-09_aed/map#sidebar&map=19.75/45.9045704/5.6785105) :
<img width="50%" alt="Capture d’écran 2020-08-28 à 19 26 35" src="https://user-images.githubusercontent.com/2158081/91595960-b28fee80-e964-11ea-9a4c-8450b2961dac.png">

**Comment by PanierAvide** [comment]
Je me pose la question de référencer ces problèmes de données autre part que sur le dépôt du projetdumois.fr. Peut-être qu'un pad à ouvrir et à partager sur le wiki et la liste de diffusions s'y prêterait bien ? Ça permettrait de partager les infos avec les autres contributeurs.

**Comment by nlehuby** [comment]
Je ne sais pas si c'est la meilleure option, mais on l'avait mis sur le wiki pour les gendarmeries : https://wiki.openstreetmap.org/wiki/FR:Project_of_the_month/Gendarmerie_nationale#Relev.C3.A9_des_erreurs.2Fincoh.C3.A9rences

**Comment by PanierAvide** [comment]
Sur le wiki ça peut, peut-être dans une sous-page pour pas rendre visible la complexité de ces échanges aux nouveaux contributeurs ? Avec un lieu dans la page principale aux endroits pertinents ça me semblerait bien. L'avantage vis à vis d'un pad c'est que ça reste dans le temps.

**Comment by pyrog** [comment]
Dans les issues ? ça reste dans le temps 😉

**Comment by PanierAvide** [comment]
Le problème c'est que le dépôt a vocation à contenir les tickets liés au _code_ du site. Là où les éléments de doublon de données etc. a plutôt vocation à être partagé par la communauté. Toutes les personnes qui contribuent n'ont pas de compte Github. On ne va donc pas les forcer à en créer pour partager ces problèmes dans les _données_ :wink:

**Comment by pyrog** [comment]
> les tickets liés au code du site

j'ai pigé 😃 

### Concernant les données
J'ai remonté le problème de doublon à l'ARS.
Je ne vois pas l'intérêt pour un contributeur de vérifier le wiki avant de modifier un POI.

On pourrait ajouter une option pour marquer un POI comme problématique :
1. ça évite de consulter le wiki et le contributeur est informé qu'il y a un blème.
1. l'animateur du projet sais qu'il y a un problème (via une page spéciale) : il peut contacter le fournisseur de données.

### Concernant le code
Si le problème est fréquent, bloquant… le code devra être adapté.
Si ce n'est pas nécessaire pour ce projet du mois, ça peut l'être pour un prochain thème.

**Comment by PanierAvide** [comment]
Suite aux problèmes avec les identifiants GéoDAE, on peut sans doute mettre de côté ce sujet. Le jour où les identifiants seront stables, on mettra en place l'analyse Osmose et ce qu'il faut pour permettre une intégration facilitée.

**Comment by overflorian** [comment]
Tu veux dire qu'ils ont répondu défavorablement à ta demande de rétablir les codes sur lesquels on travaillait auparavant ?

**Comment by PanierAvide** [comment]
Non pour l'instant pas de réponse, et je pense que ce ne sera pas possible de rétablir les codes tels qu'ils étaient puisque ça ressemble à une numérotation automatique export par export.
