### ISSUE TITLE
BANCO : la couche "Commerce dans OSM" ne s'affiche pas

### ISSUE THREAD

**Issue by cayenne17** [vdct/ProjetDuMois#311]
Bonjour,

Sur https://commerces.openstreetmap.fr/projects/2022-01_shop, la couche de **Commerce dans OSM** ne charge pas ou ne s'affichage pas.

J'ai aucun point vert

**Comment by PanierAvide** [comment]
Bonjour, c'est lié aux soucis répertoriés ici : https://github.com/osm-fr/infrastructure/issues/483

Je ferme le ticket ici pour éviter de multiplier les suivis :wink:
