### ISSUE TITLE
Fin de OAuth 1.0 sur osm.org

### ISSUE THREAD

**Issue by flacombe** [vdct/ProjetDuMois#312]
La team technique d'osm.org annonce la fin d'OAuth 1.0 sur l'authentification des utilisateurs
https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490

Peut-etre que cela impacte le projet, via l'utilisation du composant d'authentification.

**Comment by PanierAvide** [comment]
À priori, le fait de basculer sur la dernière version de osm-auth (que l'on utilise) devrait suffire à implémenter ça côté PdM : https://github.com/osmlab/osm-auth

À tester plus en détail ceci dit, pour être sûr qu'il n'y a pas eu de changements dans la façon d'utiliser cette bibliothèque.

**Comment by mmd-osm** [comment]
Linking to upstream issue for better visibility: https://github.com/openstreetmap/operations/issues/867

**Comment by PanierAvide** [comment]
La bascule a été faite sur Pic4Review, avec les modifications de code suivantes : https://framagit.org/Pic4Carto/Pic4Review/-/commit/8e30a62d5e93d400455fb6299d40c536dd76d03f

Si quelqu'un trouve le temps de s'en occuper avant moi, la PR sera bienvenue :wink:

**Comment by flacombe** [comment]
J'ai commencé à la regarder pour adapter, mais je sèche un peu.

Il y a le head.pug et aussi dans db/10_pbf_update.js où il faut revoir l'authentification pour récupérer les fichiers chez Geofabrik. C'est pas évident.

**Comment by flacombe** [comment]
Cela devient urgent désormais : 
https://forum.openstreetmap.fr/t/enedis-osm-fr-ex-projet-du-mois/25647

**Comment by flacombe** [comment]
C'est fix !

**Comment by cayenne17** [comment]
https://commerces.openstreetmap.fr n'a pas été encore migré.
