### ISSUE TITLE
Statistiques et "éditions de masse"

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#32]
Mon score passe de 9 à 151 suite à ce [groupe de changement](https://www.openstreetmap.org/changeset/90033563) !

Faut-il filtrer ces modifications ?
Si oui, comment ?
Faut-il compter les groupes de changements ou les DAE modifiés ?
Ou alors détecter ces changements (`bot=yes`) et si besoin les "marquer" manuellement ?

Un retour en arrière sur les [bornes de recharges pour VE](https://projetdumois.fr/projects/2020-03_evcharging) ou les [postes de transformation électrique](https://projetdumois.fr/projects/2018-07_substation) montre un potentiel import pour les premiers.

**Comment motiver les contributeurs débutants** qui font uniquement des ajouts manuels ?

**Comment by PanierAvide** [comment]
C'est une bien bonne question... Plusieurs pistes ou approches :
- Ne rien changer, car après tout ça reste du boulot qu'on peut vouloir valoriser de corriger des objets en masse
- Si on veut filtrer, pas simple de distinguer une contribution où on a modifié en masse vs une grosse contribution suite à des heures de terrain.
- Filtrer sur les tags pourrait être une piste, mais on va vite aller vers du cas par cas, intenable en terme de temps à y passer.
- Selon les projets du mois, l'objectif pourrait être de faire de la correction par lot à distance, donc essayer de les filtrer à un instant t pourra poser problème dans le futur...

**Comment by pyrog** [comment]
> Selon les projets du mois, l'objectif pourrait être de faire de la correction par lot à distance

Un réglage à mettre dans le projet ?

> ça me paraît tout aussi important de travailler sur l'acquisition des badges […] pour l'engagement

Oui, mais sur quels critères objectifs les attribuer ?

**Quels sont les objectifs de PdM ?**
- Inciter les nouveaux (et jeunes ?) contributeurs à participer ?

**Comment by PanierAvide** [comment]
Une façon simple de résoudre ce problème est peut-être de pondérer les contributions sous la forme de "points". Pour les DAE, la valeur ajoutée est de trouver des DAE sur le terrain, donc on pourrait dire :
- Un DAE créé dans OSM = 3 points
- Un DAE édité = 1 point

Ça permet de compter toutes les contributions, d'orienter les priorités sans empêcher toutes sortes de contributions.

**Comment by pyrog** [comment]
Est-ce que les données des graphiques, statistiques… sont facilement accessibles ?

On pourrait jouer avec dans son tableur pour essayer de trouver des solutions satisfaisantes ?
De plus c'est à la portée du plus grand nombre 😃

**Comment by PanierAvide** [comment]
Elles sont rapatriées côté client via un appel Ajax (pour tester rapidement l'authentification de l'utilisateur), voir dans la console l'URL qui a cette forme :
```
https://projetdumois.fr/projects/2020-09_aed/stats?osm_user=XYZ
```

C'est du JSON, représentant une combinaison des stats qui apparaissent sur la page. Un outil comme `jq` permettra de revenir sur une mise en forme plus classique de CSV.

**Comment by pyrog** [comment]
Ça fonctionne aussi pour le classement général.
Merci 😃

**Comment by pyrog** [comment]
Zut alors, mon score baisse 🤣
