### ISSUE TITLE
Trou dans les statistiques

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#33]
Pas de données le 10 novembre : timeout dans la requête ?

<img width="50%" alt="Avancement" src="https://user-images.githubusercontent.com/2158081/91528454-0b7d6980-e908-11ea-9467-b80bc91f3926.png">

**Comment by PanierAvide** [comment]
Ça vient d'Osmose, cf : http://osmose.openstreetmap.fr/fr/errors/graph.png?item=8190&start_date=2018-11-01&end_date=2018-12-01

Un timeout dans la requête ou autre problème du genre aurait causé l'absence totale d'affichage ;)
