### ISSUE TITLE
Chemins DAE pas affichés

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#34]
Exemple : [Centre Sportif Grange aux Belles](https://www.openstreetmap.org/way/26954018) voir sur [PdM](https://projetdumois.fr/projects/2020-09_aed/map#sidebar&map=17.03/48.877446/2.366974) et [MapComplete](https://pietervdvn.github.io/MapComplete/aed.html?z=19&lat=48.877&lon=2.3673).

Un POI orange est affiché ce qui risque de créer un doublon, et ne permet pas non plus de corriger le DAE existant.

Il y en a [74](https://overpass-turbo.eu/s/XtB) en France et de mémoire [246](https://overpass-turbo.eu/s/XtC) dans le monde.

**Comment by PanierAvide** [comment]
Et en même temps le wiki dit que les DAE sont forcément des noeuds. Donc plutôt à corriger dans OSM.

**Comment by nlehuby** [comment]
On peut créer des challenges maproulette pour ça (et ptet aussi d'autres trucs, comme les info du tag note qui pourraient être transférées vers des tags plus appropriées). 

C'est pas mal en milieu de mois pour redonner un petit élan et remotiver à contribuer ceux qui ont déjà fini leur quartier :wink:

**Comment by pyrog** [comment]
Le wiki est une chose…
Ce que les contributeurs OSM comprennent, ou les pressés font, en est un autre 😄 

La réalité c'est qu'il existe des DAE sur des `way`s.
Il y en a trop pour les nettoyer d'un coup, et quelqu'un va trouver le moyen d'utiliser des ways à l'avenir.

Donc il faudrait pouvoir gérer ces cas là : ok, ce n'est pas urgent 😃

**Comment by PanierAvide** [comment]
+1 pour le challenge MapRoulette, ça me semble plus raisonnable que d'aller au front avec la liste internationale pour faire modifier le wiki, et plus intéressant que de laisser les DAE sous forme d'emprise (faut le trouver sur 15 hectares le DAE après, pas simple !)

**Comment by pyrog** [comment]
> On peut créer des challenges maproulette pour ça

Bonne idée 😃 

On pourrait aussi avoir un paramètre du projet pour afficher les objets en "erreur".

> aller au front avec la liste internationale pour faire modifier le wiki

🤣

**Comment by PanierAvide** [comment]
Pour les objets en erreur, le mieux serait que ce soit remonté par Osmose : ça prendra 30 secondes à ajouter dans projetdumois.fr, et l'erreur s'affichera dans le futur pour tout le monde.

**Comment by pyrog** [comment]
je n'ai plus la syntaxe en tête, mais on peut facilement sélectionner un `way` avec le tag `emergency=defibrillator`

**Comment by PanierAvide** [comment]
Je ferme le ticket. Pour la suite, la règle pourrait être ajouté dans le fichier MapCSS France pour JOSM et Osmose : https://josm.openstreetmap.de/wiki/Rules/FranceSpecificRules

**Comment by nlehuby** [comment]
ça m'était sorti de la tête, désolée !
Le [challenge MapRoulette](https://maproulette.org/browse/challenges/14376) a fait un flop.

Je veux bien ajouter cette règle au fichier MapCSS France mais je ne suis pas trop familière de son fonctionnement : comment je choisis l'id d'item et de classe pour Osmose ? Où sont gérées les trads ? (

**Comment by PanierAvide** [comment]
Pour les ID d'item et de classes, je crois que la règle est de coller avec ce qui existe déjà, ici ce serait 9003/9003007 en regardant sur le site web. Comme il y a déjà un ensemble de règles qui correspondent bien à ce cas, tu pourrais modifier directement :
https://josm.openstreetmap.de/browser/josm/trunk/resources/data/validator/geometry.mapcss#L97

Ce qui permettra de réutiliser les traductions existantes.
