### ISSUE TITLE
Podium : suggestion de rendu

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#35]
Je propose :
* d'aligner le classement en bas (dans ou sous le rectangle coloré)
* de mettre les noms en haut
* de mettre un lien sur les noms/photos

Est-ce que chart.js peut faire ça avec une animation ? 😎 

<img width="50%" alt="Podium 2" src="https://user-images.githubusercontent.com/2158081/91609106-128f9080-e977-11ea-8749-19c9ddcd00a8.png">

**Comment by PanierAvide** [comment]
Chart.js fait vraiment uniquement les graphiques simples. Après je peux voir à créer une animation CSS, mais pas trop sûr de quel rendu faire... Sinon OK pour l'alignement des chiffres et les liens.

**Comment by PanierAvide** [comment]
Fait via 7b9b673

**Comment by pyrog** [comment]
> Fait

😉 
- [ ] d'aligner le classement en bas (dans ou sous le rectangle coloré)
- [ ] de mettre les noms en haut
- [x]  de mettre un lien sur les noms/photos

> Après je peux voir à créer une animation CSS, mais pas trop sûr de quel rendu faire

Je proposais les animations car Chart.js le fait (mais je n'ai pas trouvé de détails dans la doc).

J'imagine que les podiums vont sortir du sol les uns après les autres ?
Et les bonhommes tomber sur les marches (ça chart.js ne doit pas le faire 😆)

**Comment by PanierAvide** [comment]
À noter qu'il y a aussi l'effet d'apparition successive des marches (transition CSS sur l'opacité). Là on rentre dans les goûts et couleurs, mais je préfère avec l'alignement des chiffres et noms en haut (c'est assez courant). Bien sûr ça reste ouvert à améliorations diverses, mais en l'état c'est _pas si mal_.

**Comment by pyrog** [comment]
> en l'état c'est pas si mal.

👍
