### ISSUE TITLE
Classement : suggestion de rendu

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#36]
Je propose :
* d'aligner les nombre à droite
* de figer l'entête du tableau

<img width="30%" alt="Classement" src="https://user-images.githubusercontent.com/2158081/91609837-6babf400-e978-11ea-8343-7ebd744ffc8a.png">

**Comment by PanierAvide** [comment]
Celle là elle est facile à résoudre, n'as-tu pas envie de faire une proposition de code ? :wink:

**Comment by PanierAvide** [comment]
Fait
