### ISSUE TITLE
Gérer les horaires d'accès

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#37]
Gérer les cas "faciles tels que :
c_disp_j | c_disp_h | openting_hours
-- | -- | --
`{lundi,mardi,mercredi,jeudi,vendredi}` | `{"heures ouvrables"}` | `Mo-Fr "heures ouvrables"`

Ou à défaut, mettre un tag` note="lundi,mardi,mercredi,jeudi,vendredi - heures ouvrables"`

De plus, il y a un problème de données à remonter à l'ARS (la saisie libre génère des _"messy data"_)

**Comment by PanierAvide** [comment]
Pour le faire, c'est ici : https://github.com/osm-fr/osmose-backend/blob/master/analysers/analyser_merge_defibrillators_FR.py#L51

Les données sont trop _messy_ à mon goût pour vouloir y passer des heures. Mais le code est prévu déjà pour gérer plus de cas, il faut juste écrire les conditions :wink:

**Comment by PanierAvide** [comment]
Ça fait plus d'un mois et personne ne s'est emparé du sujet. Je ferme le ticket.
