### ISSUE TITLE
Lieu potentiels vérifiés

### ISSUE THREAD

**Issue by darkhamaus** [vdct/ProjetDuMois#38]
Est ce qu'il y aurait moyen d'ajouter une sorte d'overlay pour indiquer qu'un lieu potentiel pour DAE a été vérifié de manière à plus facilement suivre l'avancement d'une zone ?

**Comment by PanierAvide** [comment]
Pour l'instant les lieux potentiels sont masqués au fur et à mesure des ajouts dans OSM. Lorsqu'un DAE est ajouté à moins de 50 mètres d'un lieu potentiel, celui-ci disparaît. Comme les mises à jours sont toutes les heures, je ne sais pas si ça vaut le coup de rajouter un tel mécanisme.

**Comment by darkhamaus** [comment]
Pardon j'aurais du être plus clair, je pensais surtout au cas où il n'y a pas de DAE. Actuellement rien ne permet clairement d'indiquer à un autre utilisateur qu'un tel lieu a été visité de manière à voir s'il y avait effectivement un DAE et qu'il n'y en avait pas sur place.

**Comment by pyrog** [comment]
Cette couche peut-être masquée maintenant (encore merci Adrien 😃 ), il est peut-être moins tentant de visiter tous ces lieux.

Une solution consisterait à décrire (quelque part) une "procédure" :

- Si on connait un DAE qui n'est pas sur la carte, alors afficher cette couche pour faciliter la saisie (car le lieu où se trouve le défibrillateur est probablement affiché)
- Et surtout pas l'inverse : visiter tous ces lieux pour voir si éventuellement un DAE s'y trouve 😉

**Comment by PanierAvide** [comment]
@darkhamaus effectivement la question se pose davantage pour les lieux où l'on sait qu'il n'y a pas de DAE. Niveau interface, ça pourrait être très similaire au bouton "rien ici" proposé pour les signalements Osmose. Niveau technique, il faut que j'enregistre les identifiants des lieux visités pour les filtrer à l'affichage.

@pyrog L'idée (peut-être à affiner) c'est quand même de donner des pistes de lieux où pourraient se trouver des DAE, notamment quand les bases actuellement ouvertes ne proposent rien dans le secteur. J'aimerais autant trouver une méthode pour améliorer la pertinence des suggestions. Si on sait déjà où un DAE se trouve, le fond de carte se suffit à lui même pour localiser :wink:

**Comment by pyrog** [comment]
> le fond de carte se suffit à lui même pour localiser 😉

Je me répète (technique du disque rayé 😉) : c'est "pour faciliter la saisie".

Par contre un point me gène (et mériterait un ticket) :
En cliquant sur un "Lieu pouvant disposer d'un DAE" on affiche tous les tags de cet objet OSM.

Je propose de ne montrer que les tags pouvant être recopiés dans le DAE :

- `name`
- `opening_hours`
- d'autres ?

**Comment by PanierAvide** [comment]
C'est en ligne : les points orange peuvent être masqués en faisant "rien ici" en bas de leur description. C'est masqué directement pour les autres utilisateurs.
