### ISSUE TITLE
Ajout de notes

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#39]
Ça serait très pratique de pouvoir ajouter une note directement dans PdM.

Ainsi des contributions pourraient être faites par des personnes ne connaissant pas OSM, ou quand les informations ne sont pas assez détaillées.
Exemple : note [2331201](https://www.openstreetmap.org/note/2331201)

La note serait pré-remplie avec un mot-clé utilisé par le projet en cours (#DAE par exemple).

**Comment by PanierAvide** [comment]
On peut déjà créer des notes quand on est pas authentifié : ça se fait de la même manière que la création d'un point classique, sauf qu'à la fin une note est envoyée. Ça couvre le cas des personnes ne connaissant pas OSM.

Par contre effectivement quand on est authentifié, un ajout de point se fait en édition directe. Pas de moyen de mettre une info partielle ou à détailler. Je ne suis pas certain de la manière dont on peut proposer l'ajout d'une note en tant qu'alternative à la création d'un POI sans que ce soit clicodrome.

**Comment by pyrog** [comment]
> manière dont on peut proposer l'ajout d'une note

Comme pour l'ajout, en choisissant l'éditeur : iD, JOSM, Note… 😉

**Comment by PanierAvide** [comment]
_C'est pas faux_ comme dirait l'autre :stuck_out_tongue:

**Comment by PanierAvide** [comment]
Comme ça m'a fait défaut aussi ce matin sur le terrain (l'ajout de note via osm.org est infernal sur mobile...), je viens de le rajouter via 2347310. Donc sur le bouton "ajouter un défibrillateur", on a une entrée "via une note de carte" où on peut rentrer un commentaire sous forme de texte libre.

**Comment by pyrog** [comment]
👍 je l'attendais pour saisir un DAE qui sera installé prochainement : note [2333911](https://www.openstreetmap.org/note/2333911).
Elle est visible sur [NotesReview](https://ent8r.github.io/NotesReview/?map=18%2F46.6691%2F5.5538) et sur [PdM](https://projetdumois.fr/projects/2020-09_aed/map#sidebar&map=19.44/46.668705/5.5535998).

Merci 😎

PS: mettre éventuellement l'URL complète de PdM ainsi même le site web d'OSM 😃
