### ISSUE TITLE
Délivrer des badges aux contributeurs #Gamification

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#4]
Délivrer des badges publics aux contributeurs augmente la contribution.
Créer une page /contributeur liée à un pseudo OSM.

Idées en vrac :
- Contributeur débutant (dès la première contribution) : c'est le MVP de cette fonctionalité
- Contributeur récurrent (participe à plusieurs projets du mois)
- Gagnant du concours / leader du projet (1er en volume de contribution sur un mois)
- Top qualité (aucune modif à posteriori sur la totalité des données contribuées)
S'inspirer des badges de missing maps : http://www.missingmaps.org/users/#/overflorian/badges 

Sur la page /contributeur on peut imaginer :
- des stats de contribution comme sur https://hdyc.neis-one.org/?overflorian
- une heatmap de la contribution comme sur https://yosmhm.neis-one.org/?overflorian#
- L'image du profil d'OSM devrait être utilisée pour personnaliser l'expérience
- Dans quelle mesure peut-on utiliser la fonctionnalité "amis" d'OSM pour créer un leaderboard "toi VS tes amis" ?

Autres idées :
- Page leaderboard pour mettre en avant les "meilleurs" contributeurs (peut-être tout simplement les premiers contributeurs en volume pour commencer)
- leaderboard / carte pour comparer les différentes régions ? inspiré de https://transport.data.gouv.fr/stats

Il faudra discuter du wording : est-ce que chaque projet du mois est une mission ? une quête ? Un concours ? ou tout simplement un projet ?

**Comment by overflorian** [comment]
Je vais faire les premiers badges :
- J'ai contribué
- J'ai contribué à 100 POI
- Je suis premier de la quête
- J'ai contribué à la quête COVID

en png 32x32px et svg

**Comment by vinber** [comment]
discussion à avoir avec Charles, il y a une histoire d'openbadge dans l'air qui pourrait être intéressant

**Comment by overflorian** [comment]
@vinber ok merci je lui ai envoyé cette discussion.

Voici un premier exemple avec le badge COVID-19.
Il y a bien 2 versions avec un graphisme différent : une grande pour la page "contributeur" et une petite pour le leaderboard (nommée mini) avec largeur 32px (mais hauteur variable, ici 35px) :
![badge-covid-19-mini](https://user-images.githubusercontent.com/11553211/83643083-e8b11280-a5af-11ea-9683-ed1e924d2c9b.png)
![badge-covid-19](https://user-images.githubusercontent.com/11553211/83643098-ecdd3000-a5af-11ea-8709-0a3fe26952e0.png)

Tous les fichiers : 
[badge-covid-19.zip](https://github.com/vdct/ProjetDuMois/files/4723649/badge-covid-19.zip)

@PanierAvide on est bons pour lancer la suite ?

**Comment by overflorian** [comment]
Ma proposition pour les premiers badges :
![badges-proposition](https://user-images.githubusercontent.com/11553211/83761232-5293ef80-a676-11ea-8caf-ad13d8b49dd5.png)

PS : je n'ai pas encore d'autorisation écrite de l'équipe de #MissingMaps pour réutiliser leurs badges à partir desquels je me suis basé, mais je pense qu'il n'y aura pas de soucis.

**Comment by overflorian** [comment]
OK j'ai exporté les badges en SVG dans le dossier https://github.com/vdct/ProjetDuMois/tree/master/website/images
J'ai également mis le fichier source badges-projet-du-mois.svg à modifier sous Inkscape si besoin.
Je n'ai pas fait le plus gros contributeur du monde pour l'instant, à voir si on en a vraiment besoin par la suite.

**Comment by overflorian** [comment]
up

**Comment by overflorian** [comment]
Ok je me suis un peu renseigné sur le projet "open badge passport" et je pense que ça vaut le coup d'étudier si on peut utiliser ça pour _le projet du mois_.
C'est porté par Mozilla cf. https://openbadgepassport.com/faq, c'est open source (basé sur http://salava.org) et c'est instanciable au besoin donc je pense que l'on ne peut pas trouver plus propre.

En France [la Fabrique des Mobilités l'utilise déjà](https://wiki.lafabriquedesmobilites.fr/wiki/Produire_des_Badges). Ils nous proposent d'ailleurs de reconnaître la compétence "contributeur à OSM" pour leurs membres. Concrètement les membres de la fabrique qui contribuent au projet du mois auraient un badge "J'ai contribué à OSM" qui apparaît sur leur profil de la fabrique. A nous de voir plus tard si on veut leur faire reconnaître plus de badges (du type "je suis un gros contributeur OSM").

Pour moi cela constitue la base de ce que l'on pourrait faire par la suite : mutualiser les badges avec d'autres projets, comme par exemple des outils de contributions OSM type Osmose / Street Complete ou plus largement avec d'autres acteurs.

A vous de voir si l'on préfère d'abord construire notre système de badges dans notre coin puis s'ouvrir plus tard ou s'il vaut mieux commencer sur de bonnes bases pour ne pas redévelopper tout un système par la suite.
On pourrait utiliser l'instance publique d'_open badge passport_ dans un premier temps et voir, plus tard, pourquoi pas, si l'on a besoin d'installer notre propre instance OSM-fr.

Qu'en pensez-vous @PanierAvide @vdct @nlehuby ?
@vinber @charlesmillet je vous garde dans la boucle, ça pourrait aussi vous donner des idées ;)

**Comment by nlehuby** [comment]
Le sujet me semble pertinent pour OpenStreetMap en général, mais j'avoue être plus sceptique sur le cas particulier des projets du mois.
Ça serait par exemple assez chouette que les bénévoles et les professionnels qui font des initiations et des formations puissent délivrer des badges "je sais faire une carte Umap", "je parle couramment Overpass", "je sais modifier mon quartier avec ID", "j'ai compris où il fallait cliquer dans Osmose" :stuck_out_tongue_closed_eyes: , etc. À raccrocher aussi peut-être avec le projet un peu dormant de MOOC OSM ou les sujets de contribution au lycée.

Je me trompe peut-être mais je vois plus l'intérêt pour les débutants qui découvrent le projet OSM que pour les contributeurs qui participent aux projets du mois (il y a aussi des débutants, mais ce n'est pas le coeur de cible)
À l'inverse, je pense que nos badges de projet du mois se comparent plus avec un leaderboard : il ne s'agit pas vraiment de "certifier" une compétence mais plutôt de créer de l'émulation positive en distinguant les contributeurs les plus efficaces et les plus réguliers.

Dans tous les cas, la première chose qu'on a à régler est de pouvoir scruter les contributions et les contributeurs pour déterminer quand délivrer un badge par rapport au projet en cours, et OpenBadges ne nous y aidera pas donc je pense qu'à court terme, on a plutôt intérêt à rester concentrés sur l'essentiel.

Bref, mon avis :
- pourquoi pas : discussion plus générale à lancer avec la communauté et l'association.
- Dans le cadre du projet du mois, ça me semble prématuré. Définissons déjà et implémentons le fait de pouvoir en attribuer sur les projets du mois à venir et on verra ensuite si et comment rendre ça interopérable

**Comment by overflorian** [comment]
ok, merci pour ta réponse. ça me va, mettons cela de coté pour l'instant sur ce projet en particulier et avançons sur les badges indépendamment.

**Comment by PanierAvide** [comment]
Première passe de badges implémentés.

**Comment by PanierAvide** [comment]
Ça tourne bien, je ferme le ticket.

**Comment by overflorian** [comment]
Voici les nouveaux badges que je propose pour les projets du mois précédents : gendarmerie, bornes de recharge électrique, postes électriques, panneaux d'affichage électoraux :
![badges-projet-du-mois](https://user-images.githubusercontent.com/11553211/89779421-9c360600-db0f-11ea-904d-494c7b540b2a.png)


[badges.zip](https://github.com/vdct/ProjetDuMois/files/5050603/badges.zip)

**Comment by PanierAvide** [comment]
Badges intégrés
