### ISSUE TITLE
Afficher les POIs avec un tag fixme

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#40]
Des DAEs sont ajoutés avec une position approximative.

Une couche supplémentaire permettrait de localiser les POIs à contrôler.

**Comment by PanierAvide** [comment]
J'imagine que tu veux dire quand un tag `fixme` est renseigné ? Ça a du sens.

**Comment by pyrog** [comment]
c'est exactement ça 😃

**Comment by gendy54** [comment]
Voir même `note`

**Comment by overflorian** [comment]
je suis favorable à l'implémentation de cette idée, même pour `note`, bien que cela ne me paraisse pas prioritaire.

**Comment by PanierAvide** [comment]
Code pour coloration sur la carte

```
map.setPaintProperty('osm_0','circle-color',['case',['get',"needs_check"],'red','white'])
```

**Comment by PanierAvide** [comment]
Sûrement à traiter en même temps que #178, je ferme ce ticket.
