### ISSUE TITLE
Afficher les POIs avec au moins une photo

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#41]
Visualiser d'un coup d'œil les POIs avec photo serait pratique, voir indispensable suivant le projet.
Le POI pourrait par exemple être entouré d'un cercle (cf. [EWP](https://europeanwaterproject.org)).
<img width="30%" alt="Capture d’écran" src="https://user-images.githubusercontent.com/2158081/91846159-67265a80-ec5a-11ea-8175-ff5e587544ec.png">

Un filtre (une couche) pourrait le compléter pour n'afficher que les POI avec ou sans photo.

Voir aussi #24

**Comment by PanierAvide** [comment]
C'est un peu en doublon de #24 effectivement, je ferme ce ticket mais n'hésite pas à préciser dans le ticket #24 si besoin.

**Comment by pyrog** [comment]
Ce n'est pas en doublon car ça concerne le style des POIs affichés 😉 
#24 concerne l'ajout de photos et leur affichage (en cliquant ou en survolant le POI)

**Comment by PanierAvide** [comment]
Si c'est un doublon, puisque tu en parles déjà dans ton dernier commentaire du ticker #24 avec photo du rendu suggéré.

> Au passage, ça serait pratique si les POIs avec photos pouvaient être mis en évidence.
> (Comme dans EWP avec un contour plus épais ?)
> <img width="353" alt="EWP" src="https://user-images.githubusercontent.com/2158081/91019687-b5e84a80-e5f1-11ea-98be-285acf6bcb06.png">

**Comment by pyrog** [comment]
Bien vu 😄 

Je pourrais aussi effacer cette partie du ticket #24 car c'est en fait 2 choses complémentaires mais différentes.

**Comment by PanierAvide** [comment]
Comme ça risque d'être implémenté en même temps, autant garder un seul ticket quitte à le détailler si besoin.
