### ISSUE TITLE
Pas de choix d'éditeur en ajoutant un POI depuis la carte 

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#43]
En cliquant sur l'icône Ajouter ne propose pas le menu pour choisir son éditeur favori ou la création de note.
<img width="62" alt="Ajouter" src="https://user-images.githubusercontent.com/2158081/92324136-04103b80-f03f-11ea-9d0f-b5ea9eb9cf0b.png">

**Comment by PanierAvide** [comment]
En même temps ce serait pas hyper ergonomique un menu déroulant à cet endroit là... Le menu complet est accessible en appuyant sur le bouton "sandwich" juste au-dessus puis le bouton bleu habituel en dessous de la légende.

**Comment by pyrog** [comment]
Je ne suggère pas de mettre un menu ici 😉 

Je suggère de faire un mécanisme homogène quand on appuie sur le bouton ou l'icône Ajouter :
- soit une boite demande quel éditeur utiliser
- soit l'éditeur favori est mémorisé

Reste le choix de ajouter/éditer un POI ou ajouter une note 🤔

**Comment by overflorian** [comment]
Hello, je ne suis pas favorable à cette idée : il me semble que cela rajouterait trop de complexité pour un intérêt limité.
Autant je peux comprendre que l'on veuille choisir son éditeur OSM, autant la création d'une note devrait rester le plus simple possible.

**Comment by pyrog** [comment]
D'un coté tu as un choix (gros bouton bleu), de l'autre aucun.
Si on te demande un seule fois quel éditeur tu préfères, où se trouve la complexité ?

De toute façon il y a 2 cliques de souris :
<img width="50%" alt="Avant" src="https://user-images.githubusercontent.com/2158081/92402405-c808d380-f12f-11ea-869f-b6e4bcb316c0.png">

On pourrais mettre ça (bricolage quick'n'dirty depuis le navigateur) :
<img width="50%" alt="Après" src="https://user-images.githubusercontent.com/2158081/92402733-5715eb80-f130-11ea-9da3-74a21cf8be98.png">

**Comment by PanierAvide** [comment]
La complexité vient du fait même de demander quel éditeur choisir : une personne qui débute voudra aller au plus simple. Et le plus simple c'est de rester sur le site. Idem sur mobile. Pas besoin de demander dans ce cas là :wink: 

En soit la solution avec le bouton et son menu contextuel me semble déjà un bon compromis : c'est facile quand on veut aller à l'essentiel, et pour les personnes qui veulent aller plus loin, les outils ne sont pas très loin.

**Comment by overflorian** [comment]
Je suis d'accord avec l'analyse d'Adrien. Les boutons actuels me paraissent très bien adaptés.

**Comment by pyrog** [comment]
Je reformule : Comment ajouter simplement et rapidement une note depuis la carte ?

Sur mobile il faut :
1. Appuyer sur le menu
1. Appuyer sur la flèche pour ouvrir la liste des éditeurs
1. Appuyer sur "Via une note de carte"

Avec le double bouton on gagne deux appuis (et c'est simple à comprendre) 😃 

<img width="25%" alt="Etape 1" src="https://user-images.githubusercontent.com/2158081/92405157-50d63e00-f135-11ea-8a5b-7d3683467c0e.jpg"> <img width="25%" alt="Etape 2" src="https://user-images.githubusercontent.com/2158081/92405155-4fa51100-f135-11ea-9e37-249b1cb59495.jpg">

Une variante au double boutons lors de la validation :
Un bouton "**Ajouter une note**" (ici avec l'icône `fa-edit`) en plus du bouton "**Ajouter un objet**"

<img width="213" alt="Capture d’écran 2020-09-07 à 18 24 01" src="https://user-images.githubusercontent.com/2158081/92406077-6482a400-f137-11ea-8957-a0c3b76321ea.png">

Dans les 2 cas, c'est plus rapide et plus simple pour ajouter une note depuis l'éditeur intégré 😉

**Comment by overflorian** [comment]
Merci pour ton explication plus détaillée.
En effet, ta proposition répond bien au besoin "comment créer rapidement un note".

Néanmoins il me semble que le besoin auquel nous souhaitons répondre est "comment créer un POI rapidement". Pour cela, un bouton unique est la solution la plus efficace.
L'interface devrait 1. proposer un choix par défaut qui répond bien au besoin de la majorité des utilisateurs 2. laisser la possibilité de choisir soi-même pour la minorité des autres utilisateurs. Il me semble que l'outil parvient bien à couvrir ce besoin actuellement.
