### ISSUE TITLE
Proposer une liste de fond de carte par projet

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#45]
Pour le moment c'est codé en dur : https://github.com/vdct/ProjetDuMois/blob/633a8df7092e85b4b4ee823fe24ce1af5dd0768f/website/utils.js#L38

On pourrait rajouter un paramètre supplémentaire dans le fichier de config du projet `info.json` :
```json
"background": [
  {"name": "OSM", "tiles": "https://tile.openstreetmap.org/{z}/{x}/{y}.png"},
  {"name": "Satellite", "tiles": "https://proxy-ign.openstreetmap.fr/94GjiyqD/bdortho/{zoom}/{x}/{y}.jpg"}
]
```
Si le paramètres est vide ou absent, on utilise la config par défaut du serveur.

**Notes :**
- Actuellement PdM ne permet pas de choisir le fond de carte, mais ça sera le cas avec la résolution de #19
- Il y a aussi d'autres paramètres non mentionnés dans l'exemple pour faire simple (attributions, zoom min, max…)

**Comment by PanierAvide** [comment]
C'est intégré, on peut choisir depuis le panneau latéral de la carte entre plan ou image satellite.

**Comment by pyrog** [comment]
Merci 😃 

Je voyais plutôt une liste paramétrable car selon le projet (ou le pays), on peut avoir besoin de plusieurs fonds…

**Comment by PanierAvide** [comment]
On verra quand on aura le besoin, là pour l'instant c'est simple et efficace comme ça :wink:

**Comment by overflorian** [comment]
Je suis d'accord : surtout, simplifions au maximum. Ce qui est en place me paraît très efficace.
