### ISSUE TITLE
Ajouter "ça reste ouvert" comme projet du mois

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#46]
je propose d'ajouter CRO en tant que projet du mois de mai-juillet 2020.
Je vais vous faire les badges si l'idée vous plaît.

**Comment by PanierAvide** [comment]
Oui c'est une bonne idée :+1:

**Comment by PanierAvide** [comment]
C'est dispo, j'ai repris le badge que tu avais créé il y a quelques temps : https://projetdumois.fr/projects/2020-04_covid19

**Comment by overflorian** [comment]
Je vois que tu as utilisé le gros badge sur la homepage et la page projet. C'est un détail mais tu peux utiliser la version mini, ça sera plus cohérent avec les autres projets.

**Comment by PanierAvide** [comment]
Les autres icônes utilisent bien la grande version, est-ce que c'est la grande version du badge covid qu'il faut éditer ?

**Comment by overflorian** [comment]
au temps pour moi, tu as bien utilisé la bonne version.
Le problème venait donc du fichier source, et voici la version corrigée :

[badge-covid-19.zip](https://github.com/vdct/ProjetDuMois/files/5216505/badge-covid-19.zip)

**Comment by PanierAvide** [comment]
Fait

**Comment by overflorian** [comment]
nice
