### ISSUE TITLE
Défibrillateurs supprimés toujours visibles sur la carte

### ISSUE THREAD

**Issue by Stefal** [vdct/ProjetDuMois#47]
Salut,
J'ai supprimé des DAE qui étaient en doublon, mais on les voit toujours sur la carte.
Exemple : https://projetdumois.fr/projects/2020-09_aed/map#sidebar&map=18.86/47.0831537/-1.3372996
supprimé dans ce changeset : https://www.openstreetmap.org/changeset/90442820

**Comment by PanierAvide** [comment]
Bonjour,

Bien vu, il y a dû y avoir une mise à jour qui ne s'est pas correctement appliquée. Je tente un rechargement complet de la base pour éviter les incohérences. À suivre.

Cordialement.

**Comment by PanierAvide** [comment]
C'était dû à la commande `osmium extract` pour filtrer géographiquement les fichiers de modifications OsmChange : les suppressions de nœuds ne sont pas conservées à la sortie. Il faut donc appliquer le fichier OsmChange monde dans son ensemble, puis filtrer le fichier osm.pbf en sortie pour ne conserver que la France. Réimport en cours...

**Comment by PanierAvide** [comment]
C'est opérationnel, merci du retour ! :smiley:
