### ISSUE TITLE
Ajouter un champ de saisie fixme

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#49]
L'éditeur intégré ne permet pas l'ajout d'un tag `fixme` cf #40
 
Sur mobile ou pour les débutants, l'éditeur intégré est indispensable.

Ajouter éventuellement un tag `note` ?

**Comment by PanierAvide** [comment]
Après en avoir discuté avec Florian, je suis parti sur un champ "autres informations" qui remplit le tag `note`.
