### ISSUE TITLE
Analyse Osmose : nettoyage des tags *:covid19

### ISSUE THREAD

**Issue by nlehuby** [vdct/ProjetDuMois#5]
Hello,

je vous propose de se mettre d'accord sur le périmètre et surtout le wording (en anglais) de notre première analyse Osmose de projet du mois avant de l'implémenter.

Il y a quelques petites questions non triviales à se poser :

https://mensuel.framapad.org/p/cro_clean_up_projet_du_mois

**Comment by PanierAvide** [comment]
Merci, des commentaires ont été ajoutés sur le document :wink:

**Comment by nlehuby** [comment]
Premier batch, pour voir si on peut convertir / persister certains info temporaires : https://github.com/osm-fr/osmose-backend/pull/892

**Comment by PanierAvide** [comment]
Ça a été intégré sur le dépôt d'Osmose, quand l'analyse aura tourné ce sera normalement dispo sur ce lien : http://osmose.openstreetmap.fr/fr/errors/?item=4010&class=202004&useDevItem=all

**Comment by nlehuby** [comment]
Le timing est probablement trop juste pour lancer ça, mais je pense que cette analyse Osmose pourrait faire une bonne quête StreetComplete :thinking:

**Comment by PanierAvide** [comment]
Pour un projet mi-juin -> mi-août ça passe :grin:

**Comment by nlehuby** [comment]
Les premières données sont dispo sur Osmose.
