### ISSUE TITLE
Ajouter le projet du mois de juin 2020 : les cinémas

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#50]
entre mai et août on a bien bossé sur les cinémas cf. https://wiki.openstreetmap.org/wiki/FR:Key:ref:FR:CNC
on n'a pas encore terminé mais avec @pyrog on pense qu'on est à environ 95% du taff déjà fait.

si vous êtes ok, je vous ponds un petit badge aux oignons

**Comment by PanierAvide** [comment]
Hmm en soit c'était pas vraiment un projet du mois dans le sens où ça s'est fait de manière plus ou moins confidentielle. Ça n'en reste pas moins un travail intéressant, mais je sais pas si projetdumois.fr est le bon vecteur pour valoriser ça. Peut-être un article sur OSM-FR ?

**Comment by overflorian** [comment]
oui en effet c'était un trip assez confidentiel. Néanmoins le suivi des stats me paraît intéressant sur un projet qui passe de environ 30% de cinémas mappés à 95%. Je pense que cela s'applique à tout sujet pour lequel un changement rapide intervient.
L'article sur talk-fr est prévu by the way ;)

**Comment by PanierAvide** [comment]
Le problème ça va être la maintenance aussi de tout ça, un nouveau projet est plus simple à déployer mais ce n'est pas instantané non plus :
- Création du fichier de configuration JSON+SQL
- Écriture d'un texte explicatif
- Création du badge
- Actualisation de la base en prod

On va dire en gros 2h/projet. Donc si on ouvre trop, on va se retrouver à multiplier ces temps de configuration. En plus, comme la communication initiale sur ces changements est restée assez limitée, on peut avoir l'impression que ça sort de nulle part ("tiens si j'avais su pour ce projet j'y aurais participé, pourquoi ça n'a pas été diffusé ??"). Je suis moyennement convaincu.

**Comment by pyrog** [comment]
On pourrait ajouter un statut aux projets : publié, non publiés (brouillon)

Comme ça le projet (pas du mois) cinémas peut bénéficier des stats... de
l'outil PdM.

Ça permet aussi de le tester un peu plus et qui sait, ça deviendra un PdM 😀

__
Yves

Le lun. 14 sept. 2020 à 08:50, Overflorian <notifications@github.com> a
écrit :

**Comment by PanierAvide** [comment]
Comme il n'y a pas d'interface d'administration, le statut "non publié" existe déjà : c'est une branche séparée de master sur le dépôt où chacun peut faire ses tests en local :wink:

**Comment by pyrog** [comment]
>
>  le statut "non publié" existe déjà : c'est une branche séparée de master
> sur le dépôt où chacun peut faire ses tests en local 😉
>
Est-ce que les non geeks peuvent tester ces projets en test ?
(geek : ceux qui savent utiliser github et faire tourner le code en local)

**Comment by PanierAvide** [comment]
Pour l'instant non, mais combien de non-geeks voudront effectivement faire cela ?

**Comment by pyrog** [comment]
Je pensais à des geek qui créent le projet, puis a des testeurs qui
l'utilisent à partir du lien diffusé de manière "restreinte"

Le lun. 14 sept. 2020 à 12:07, Adrien Pavie <notifications@github.com> a
écrit :

**Comment by overflorian** [comment]
Je pense qu'il y a vraiment peu d'usage pour cette fonctionnalité et qu'on devrait choisir binairement de mettre en prod / ou pas;
je n'avais pas conscience qu'il fallait 2h de config Adrien, et je suis convaincu par tes arguments de la non-existence "réelle" du PdM. Du coup, pour moi on n'ajoute pas les cinés et le sujet est clôt.

**Comment by PanierAvide** [comment]
Merci de ta compréhension :wink:
