### ISSUE TITLE
Créer un gros bouton +

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#52]
D'après moi, on a une "action principale recherchée" sur l'outil de contribution : créer un nouveau POI. C'est l'action que l'on devrait mettre en avant devant toutes les autres.

D'après moi cela s'applique pour tout type de projet du mois.

Si vous partagez mon analyse, alors que pensez-vous d'ajouter un gros bouton pour réaliser cette action ?
Comme celui en bas à droite sur https://gribrouillon.fr mais avec le logo "+"
Pour info ce type de bouton s'appelle "floating action button" en material design cf. https://material.io/components/buttons-floating-action-button : c'est le seul en couleur, sa taille est bien plus grande que les autres boutons

**Comment by PanierAvide** [comment]
C'est fait, le bouton est visible sur les écrans mobiles/tablettes, sur PC l'ancien bouton est conservé

**Comment by overflorian** [comment]
OK, pourquoi pas.

Je rouvre ce ticket pour te signaler que ton bouton est recouvert en zoom large :
![Screenshot_20200914-121524](https://user-images.githubusercontent.com/11553211/93076036-0732a980-f687-11ea-85c8-d4d848f9da66.jpg)

En soit ce n'est pas grave, ça nous arrange même sûrement : on devrait interdire l'édition si on n'est pas au moins au niveau de zoom 15 (ou 16 ?). Comment on fait ça intelligemment ?

**Comment by PanierAvide** [comment]
À minima j'ai ajouté une bascule de visibilité pour les widgets d'export KML et d'ajout de POI en fonction du zoom. J'imagine que c'est suffisant en l'état.

**Comment by overflorian** [comment]
On va dire que oui :) Merci
