### ISSUE TITLE
Réintégrer le bouton menu dans la barre supérieure

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#53]
hey,
il me semble assez opportun d'intégrer le bouton "sandwich" qui ouvre le menu en haut à gauche de l'interface, dans le barre supérieure. En conséquence, le logo PdM dans le bandeau supérieur n'est plus cliquable et ne renvoi plus vers la homepage.

Je propose de faire comme sur https://gribrouillon.fr : le bandeau de gauche vient au dessus de l'interface, le reste de l'interface se grise. 
Ma proposition de menu à terme :
![menu](https://user-images.githubusercontent.com/11553211/93054874-59b19d00-f66a-11ea-8140-24bab78c8d92.png)

**Comment by PanierAvide** [comment]
Autant sur mobile c'est assez clair (le bandeau latéral recouvre la carte), autant sur PC ce n'est pas encore complètement clair :
- Au clic sur un POI, le bandeau apparaît mais ne doit pas griser la carte ?
- Au clic sur le bouton sandwich via la barre d'en-tête, le bandeau apparaît et grise la carte ?

Ou le fonctionnement du bandeau actuel n'est pas modifié, c'est juste le bouton sandwich qui est déplacé ?

**Comment by overflorian** [comment]
Bonne question !
Mon avis : sur desktop, le comportement ne change pas :
- au clic sur un POI le bandeau s'ouvre et ne grise pas la carte
- au clic sur le bouton sandwich (déplacé), le bandeau apparaît et ne grise pas la carte

**Comment by PanierAvide** [comment]
Fait

**Comment by overflorian** [comment]
OK c'est niquel. Dernier comportement, optionnel mais assez standard sur mobile : swiper depuis la gauche de l'écran ouvre ou ferme le menu.
Décidément, je ne fais que rouvrir des bugs en ayant oublié de spécifié des détails : désolé !

**Comment by PanierAvide** [comment]
J'ai essayé de faire un menu qui s'affiche sur le côté aux petits oignons, j'espère que ça correspondra aux attentes :wink:

**Comment by overflorian** [comment]
Yes yes je trouve ça très classe et beau.
Que penses-tu de l'afficher si l'on clique sur le logo en haut à gauche ? C'est une suggestion pour éviter que l'utilisateur sorte trop facilement de la carte, mais honnêtement ça se discute.

**Comment by PanierAvide** [comment]
Je sais pas, d'un côté ça fait doublon avec le bouton/slider, de l'autre c'est pas déconnant non plus...

**Comment by overflorian** [comment]
J'ai dormi dessus et ce matin j'en suis convaincu : on ne devrait pas laisser l'utilisateur sortir de l'appli si facilement. 
Si cliquer sur le logo = afficher le menu te paraît bizarre, alors rajoutons un bouton sandwich.

**Comment by PanierAvide** [comment]
Il y avait de base un bouton sandwich sur mobile à la place du logo. On aurait le comportement suivant du coup ?
- Sur écran très petit + petit (mobile) : logo = ouverture menu de gauche
- Sur écran moyen + grand (tablette + PC) : sandwich = ouverture menu de gauche + logo (petit ou avec texte) = accueil

Ou bien sur mobile je ne mets que le bouton sandwich et pas le logo ?

**Comment by overflorian** [comment]
Niquel pour le desktop.
Je pense qu'on devrait choisir entre le logo et le bouton sandwich sur mobile pour ne pas surcharger l'interface. Ma préférence irait au bouton sandwich comme pour gribrouillon : l'apparition du menu est la suite logique de cliquer sur un bouton sandwich.
Franchement ça se discute, je te laisse faire le choix final.

**Comment by PanierAvide** [comment]
C'est sûr que sur mobile on pourra pas mettre logo + sandwich. J'aimais bien l'affichage du logo sur mobile dans le sens où ça rappelle l'identité visuelle. Après le bouton sandwich suggère mieux ce à quoi ça sert... La réponse est peut-être ailleurs ? Que font les autres applis dans leur bandeau ?

**Comment by overflorian** [comment]
OK la question elle est vite répondue ! 
les boutons en haut à gauche de l'interface dans les applis installées sur mon smartphone :

Ratp : ni l'un ni l'autre

toutes les applis intégrées Android (calendrier, notes, Gmail, play store. ..) : sandwich

Google maps  : icône dans la barre de recherche, qui une fois cliquée, ouvre le clavier

Geovélo, uber, Nextcloud, tapscanner, Mozilla stumbler, météo France, zenbus: sandwich

A noter aussi des applis avec plutôt l'icône "menu détails" : BNP, gallerie photo, agenda

YouTube, Netflix : logo mais aucune action lorsque cliqué.


En résumé, je pense que les ergonomes ont déjà tranché en faveur du bouton sandwich depuis longtemps. 
Banco bongo

**Comment by PanierAvide** [comment]
C'est fait
