### ISSUE TITLE
Changer la police du logo ?

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#54]
Hey,
Ossiann a proposé une police d'écriture un peu mieux que celle existante : c'est celle qui sera sur les stickers :
![image](https://user-images.githubusercontent.com/11553211/93055269-ed836900-f66a-11ea-8e33-b460d8b88200.png)

Que diriez-vous d'abandonner celle qui est actuellement sur le site ?
La nouvelle est Suez One Regular :
[SuezOne-Regular.zip](https://github.com/vdct/ProjetDuMois/files/5216723/SuezOne-Regular.zip)

et la couleur utilisée pour le titre est le bleu #1562ac

**Comment by PanierAvide** [comment]
Ça me va, il faut juste modifier les images concernées (principalement l'en-tête et l'image de la page d'erreur) : https://projetdumois.fr/error/404 Tu peux les modifier et les renvoyer ici ou directement sur le dépôt ? :smile:

**Comment by overflorian** [comment]
je vais faire ça yes

**Comment by overflorian** [comment]
OK j'ai fait les nouveaux fichiers : [Logos-projet-du-mois-nouveau.zip](https://github.com/vdct/ProjetDuMois/files/5219380/Logos-projet-du-mois-nouveau.zip)

à noter une nouveauté : logos-projet-du-mois-texte-mini.svg
Je pense que ça sera mieux de mettre ça sur la carte depuis un PC. En effet aujourd'hui on peut voir que le titre est peu visible :
![image](https://user-images.githubusercontent.com/11553211/93104326-fc3f3f80-f6ad-11ea-8eb0-2652044d914e.png)
Je t'ai fait un bel export de 44px de haut pour logo-projet-du-mois-texte-mini.png kiss kiss love :
![logo-projet-du-mois-texte-mini](https://user-images.githubusercontent.com/11553211/93104864-ad45da00-f6ae-11ea-8011-9045b875855c.png)

J'ai aussi fait le changement sur https://twitter.com/projetdumois

**Comment by overflorian** [comment]
Quel nul ! J'ai tout écrit en minuscule alors qu'Ossiann a mis ça en majuscule ... je vais tout recommencer grrrrr ...

**Comment by overflorian** [comment]
Voilà bonne version :
[logo-nouveau-projet-du-mois.zip](https://github.com/vdct/ProjetDuMois/files/5219710/logo-nouveau-projet-du-mois.zip)

**Comment by PanierAvide** [comment]
C'est intégré, merci d'avoir modifié les logos ;-)
