### ISSUE TITLE
Lien vers création de compte OSM

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#55]
Dans la section "podium" sur la homepage, en dessous du bouton "Se connecter" je propose d'ajouter la mention "[Créez un compte OpenStreetMap](https://www.openstreetmap.org/user/new)"

je propose aussi de rajouter un petit logo OSM dans le bouton "se connecter" pour qu'il soit clair et net que l'identification se fait via OSM. Adrien tu me dis si tu as besoin d'un petit logo.

**Comment by PanierAvide** [comment]
J'ai modifié le bouton en conséquence "S'inscrire / se connecter". En fait c'est mieux techniquement de garder le même bouton pour assurer une bonne redirection à la fin de l'inscription. Si on met un bouton séparé, pas sûr qu'on puisse faire le lien et avoir le retour en fin de création de compte.

**Comment by overflorian** [comment]
ok, ça me va, merci
