### ISSUE TITLE
Lisibilité du menu

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#56]
Hey,
Il me semble que le menu général indiquant "Participer Stats Données" manque de lisibilité.

Solution simple :
1. Ajouter une icône pour chaque rubrique
2. Définir des couleurs lorsque chaque élément est highlighté, comme sur https://www.openstreetmap.fr
Je propose texte blanc sur fond bleu "PdM" #1562ac

**Comment by PanierAvide** [comment]
Je veux bien améliorer ça, mais il me faut une proposition précise car le menu en l'état est déjà limite niveau longueur sur mobile. Ajouter des icônes ne va pas améliorer la chose. Est-ce qu'il faut du coup réduire la taille des textes ? Changer le mode d'affichage du menu ? N'afficher que les icônes ? Preneur de tes éclairages sur la question :smile:

**Comment by overflorian** [comment]
Tu es dur en affaires !
OK, c'est normal, voici déjà quelques exemples :
- un top menu chez facebook :
![image](https://user-images.githubusercontent.com/11553211/93581138-02306b80-f9a1-11ea-8efb-851f33c59546.png)

- un top menu chez instagram :
![image](https://user-images.githubusercontent.com/11553211/93581230-2429ee00-f9a1-11ea-96bd-3d61d030380c.png)

- un top menu chez youtube :
![image](https://user-images.githubusercontent.com/11553211/93581288-3c017200-f9a1-11ea-9b94-08cac2d3ed96.png)

Du coup, voici mon avis :
1. On ne devrait pas diminuer la taille du texte, question de lisibilité
2. Ajouter un séparateur est sûrement une bonne idée
3. Vue qu'on est en responsive, on peut se permettre de faire un truc top, du type :
- par défaut : ICONE Participer | ICONE Statistiques | ICONE Données
- si manque de place :  ICONE Participer | ICONE Stats | ICONE Données
- si encore manque de place :  ICONE | ICONE | ICONE (les icônes seraient plus grosses dans ce cas)

Mais on peut aussi se dire que ça serait y consacrer trop de temps, que ce n'est qu'un menu, qu'un y a d'autres problèmes plus importants sur terre comme la déforestation, le piètre état de l'open data en France ou encore la côte de popularité de Marine Le Pen et que le problème à résoudre n'est que la lisibilité.
Dans ce cas, on ne fait que rajouter un séparateur et basta.
You decide cowboy.

Question subsidiaire : sur la page des badges, unique pour chaque utilisateur, le menu change pour "En ce moment / Stats / Données". Qu'est ce qui justifie cet étonnant changement ?

PS : je ne sais plus où tu vas chercher tes icônes, tu peux me redonner l'URL stp ? Je peux faire des suggestions si besoin

**Comment by overflorian** [comment]
Ce ticket rejoint un peu celui-là également https://github.com/vdct/ProjetDuMois/issues/13

**Comment by PanierAvide** [comment]
La solution _simple et pas chère_ ce sera de passer sur des icônes seules en mobile (il n'y aura pas la place autrement), et au-delà du mobile icônes + libellé.

Les icônes sont sur https://fontawesome.com/icons?d=gallery (uniquement les icônes de base, pas les pro).

**Comment by overflorian** [comment]
Je n'aime pas trop différencier mobile et desktop. La taille d'écran a plus de sens si tu veux faire une distinction. On devrait afficher le menu standard si possible, et la version mini si l'écran est trop petit.
C'est une bonne pratique du responsive design.

Ceci dit, ok pour 2 versions.
Je propose les icônes :
- Participer https://fontawesome.com/icons/pen?style=solid
- Statistiques https://fontawesome.com/icons/chart-bar?style=solid
- Données https://fontawesome.com/icons/file-download?style=solid

**Comment by PanierAvide** [comment]
Oui je dis mobile/PC mais c'est bien rapport à la taille d'écran, cf les dimensions précisées ici https://getbootstrap.com/docs/4.5/layout/overview/#containers

OK pour les icônes

**Comment by overflorian** [comment]
OK cool, on est bien d'accord.

Sur le même principe que https://github.com/vdct/ProjetDuMois/issues/51 je pense que les icônes mobiles devraient être TRÈS grosses.
Je propose 54 px, basé sur une petite comparaison rapide :

![screen](https://user-images.githubusercontent.com/11553211/93585764-943b7280-f9a7-11ea-9442-570cbc157d83.png)

**Comment by PanierAvide** [comment]
C'est fait :wink:

**Comment by overflorian** [comment]
Merci.
Petit détail : le placement des ancres dans la page pourrait être un peu ajusté :
![Screenshot_20200919-190129.jpg](https://user-images.githubusercontent.com/11553211/93672436-195b8000-faab-11ea-8e2c-61072b4ef3a5.jpg)
Contribuer : il manque le titre

![Screenshot_20200919-190133.jpg](https://user-images.githubusercontent.com/11553211/93672447-2d9f7d00-faab-11ea-9d36-be0103755aca.jpg)
Stats : il manque le titre

![Screenshot_20200919-190138.jpg](https://user-images.githubusercontent.com/11553211/93672454-3abc6c00-faab-11ea-90ef-a53499b99867.jpg)
Données : le titre est coupé ( il ne manque que quelques pixels !)

Merci

**Comment by PanierAvide** [comment]
Fait

**Comment by overflorian** [comment]
C'est niquel, merci
