### ISSUE TITLE
Rendre plus visible l'accès à la carte

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#57]
Dans la rubrique "participer", le seul moyen d'accéder à la carte est de cliquer sur "commencer à contribuer" qui est sur fond de carte.
Je pense qu'on pourrait le rendre plus visible.

3 propositions :
- passer le texte "commencer à contribuer" en bouton d'action principal : c'est à dire garder la carte en fond et rajouter un bouton bleu avec le texte en blanc dessus
- Rajouter un bouton d'action principal (bleu) "contribuer" et passer les boutons "documentation complète" et "article de blog" en boutons secondaires (tous les 2 en gris)
- combiner ces deux options ;)

**Comment by PanierAvide** [comment]
Fait

**Comment by overflorian** [comment]
Désolé, je suis tatillons mais pourrais-tu stp changer "commencer à contribuer" par "Contribuer" ? Les verbes d'action seuls sont préconisés sur les boutons d'action.
Désolé je n'ai pas été assez précis auparavant.

**Comment by PanierAvide** [comment]
Fait
