### ISSUE TITLE
Ajouter lien vers GeoDataMine

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#58]
Dans la section "données", il y a un lien vers la page exacte de data.gouv.fr
Je suggère de :
1. Rajouter le logo pour que ça soit plus clair en précisant "site open data du gouvernement
![data gouv](https://user-images.githubusercontent.com/11553211/93704905-8b1de300-fb18-11ea-8397-54f43024b39a.png)

2. Rajouter la possibilité de télécharger par commune, via à un lien vers GeoDataMine
(ça ne fonctionne que s'il y a une catégorie existante dans GeoDataMine, en l’occurrence pour les DAE, elle existe)

on n'a pas besoin de se limiter à de simples boutons d'action pour ces différentes possibilités de téléchargement : on peut être un peu plus créatif en faisant des blocs dédiés du type https://material.io/components/cards#anatomy
Dis moi si tu veux plus de précisions mais peut-être as-tu l'inspiration de ton coté.

ça me paraît être l'évol la moins urgente du monde ;)

**Comment by PanierAvide** [comment]
Yes
