### ISSUE TITLE
Faire la plus belle page 404 de l'univers

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#6]
Il paraît primordial de construire une page 404 au plus vite :rofl: 

Je propose que cette page soit constituée d'une superbe animation au déplacement de la souris avec des layers différents en s'inspirant du code de la page https://github.com/404

J'ai décomposé l'image en layers, normalement les formats sont corrects pour faire un bandeau de la même taille que sur Github.
[404.zip](https://github.com/vdct/ProjetDuMois/files/4690633/404.zip)

Vous en dites quoi ? :D

PS : on pourra réutiliser cette animation sur des pages plus fréquentées genre /about

**Comment by overflorian** [comment]
J'ai l'impression que certains URL incorrects du site ne renvoient pas vers la 404. Par exemple https://projetdumois.fr/projects/2020-09_aeffdd

**Comment by PanierAvide** [comment]
Bien vu, c'est corrigé

**Comment by pyrog** [comment]
https://projetdumois.fr/404 affiche encore une erreur 😉 
```
502 Bad Gateway
nginx/1.14.2
```
