### ISSUE TITLE
Notification de badges

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#62]
Pour motiver les contributeurs à obtenir de nouveaux badges, on devrait rajouter une notif pour les informer qu'ils en ont obtenu un nouveau, le cas échéant.
L’icône du compte utilisateur en haut à droite pourrait alors temporairement être remplacée par l’icône animée "cloche" http://potlabicons.com/files/icon-notification.html pour attirer l'attention.
Ensuite, la notif en question pourrait venir se mettre au dessus des autres éléments existants du menu, à savoir "mes badges" et "se déconnecter".
Idée de wording : "vous obtenez un nouveau badge ! [Nom du badge]"
et peut-être rajouter l'icone-mini dans cette notif cliquable qui renverrai vers la page "badges de l'utilisateur".

Dans l'idée, ce système de notif pourrait être également utilisé comme incentive par la suite.
Par exemple : "Y a-t-il un DAE dans le Franprix juste à coté de vous ?"

Inspirations possibles pour définir plus précisément le système de notif : facebook, wikipédia

**Comment by PanierAvide** [comment]
Il y a déjà un affichage des badges obtenus et à venir lorsque l'on contribue : après l'envoi les badges concernés apparaissent. Dans quelle mesure ce mécanisme de notification complète / remplace l'existant ?

**Comment by overflorian** [comment]
Les notifications sont un mécanisme efficace de récompense pour les utilisateurs et entrent dans une optique plus large de gamification.
A vrai dire c'est l'étape suivante qui me paraît logique pour la gamification mais comme tu n'as pas l'air convaincu je te propose d'en discuter avant d'avancer. 
De mon côté je vais traîner sur des blogs de marketeux pour mieux comprendre les dynamiques de gamification que je maîtrise encore mal

**Comment by PanierAvide** [comment]
Je suis convaincu de la nécessité d'une boucle de retour rapide. Ce qui me laisse perplexe c'est plutôt que notification + affichage à l'envoi d'une contribution pour moi font doublon. Je vois par exemple le client Telegram web qui bugue et nécessite de cliquer après la lecture en plus sur le contact pour faire disparaître la notification : c'est chiant.

Donc favorable à ce que les récompenses soient plus visibles, mais vigilant sur ce que l'information soit affichée de la manière la plus pertinente possible :wink:

**Comment by overflorian** [comment]
OK j'ai un peu réfléchit au sujet et voici ce qu'il en ressort :
1. Notre persona:
Mickaël a 25 ans, il est étudiant en sociologie. Il a un PC sous Windows et l'essentiel de ses interactions sociales numériques se déroulent sur son smartphone Android, notamment via Whatsapp, Instagram et Tinder. Il a une utilisation basique de l'informatique, sauf le pack MS Office qu'il maîtrise bien.
Il connaît un peu OSM et sympathise à la cause mais il n'a jamais contribué.
Un contributeur avancé lui conseille de commencer à contribuer via PdM. Ce mois-ci ce sont les DAE. Mickaël en a repéré certains à la Fac et il aimerait les rajouter sur la carte. Le lundi matin, avant son cours, il a 5 min, prends son smartphone, se rend sur pdm.fr pour la première fois. Il comprends qu'il doit créer un compte OSM, le créé, puis arrive sur la carte.

(il y a pas mal d'implications intéressantes induites par ce persona, il faudra qu'on en parle, mais pour l'instant, restons focalisés sur les notifs ...)

2. Le système de notif devrait être pensé pour Mickaël.
Je pense que les tops contributeurs sont tous nos potes, on n'a absolument pas besoin de les pinger pour qu'ils contribuent. Ils se tirent la bourre en regardant le leaderboard. (ça fonctionne déjà : Donat présentait PdM à Ossiann la dernière soirée en lui montrant le leaderboard #fierté)
Ces gens ne sont PAS la cible de notre système d'incentive. Donc les badges "top contributeurs" ne provoqueront pas de notif.

3. Fonctionnement du système de notif tel que je l'imagine actuellement :
- activer une notif en ouvrant l'outil pour la première fois est une erreur : on devrait laisser l'utilisateur se concentrer sur la découverte de l'interface à ce moment-là

- envoyer une première notif lors de la première modif me paraît une bonne idée, même si ça fait doublon comme tu le dis.
On **indique à l'utilisateur l'existence du système de notif** (on l'habitue donc à ce nouveau mécanisme qu'il a l'habitude de voir sur les autres sites "sociaux") et on lui **présente l'existence des badges** et de **sa page utilisateur**.

Cette première notif pourrait être l'occasion d'introduire une fonction sociale, par exemple : "1ère contribution : vous gagnez votre premier badge ! Partager avec vos amis FACEBOOK / TWITTER / INSTAGRAM" (pourquoi pas aussi créer des badges à ajouter sur son profil OSM ? Idée à creuser)

- pour que ça ne soit pas invasif, la cloche arrête de clignoter dès que l'on clique sur l’icône. A ce moment-là, la notif apparaît et on considère qu'elle est lue, même si on sait que certains utilisateurs ne la liront pas.

- Voici la répartition des contributions pour le projet DAE :
![Capture du 2020-09-27 20-35-21](https://user-images.githubusercontent.com/11553211/94372859-80a7ae80-0101-11eb-9fa4-f675e24dfd00.png)

"Il y a 23 pers qui ont fait une seule contrib et 61 personnes qui en ont fait 3."
Conclu : il faut pinger les utilisateurs aux contributions n° 1, 3 et 6 pour leur offrir un badge (et non pas 1/10/20/50/100 comme je l'envisageait au départ).

- lorsqu'aucune notif n'est active, la cloche disparaît au profit de l’icône "utilisateur".

- les 3 dernières notifs restent visibles dans la popup qui s'ouvre en cliquant sur le bouton "utilisateur". Les autres disparaissent définitivement.

Par la suite on pourrait réfléchir à comment utiliser ce système encore mieux mais pour ça, il va me falloir des stats (matomo bonjouuuuur). Par exemple avec des notifs envoyées par mail (reliées au système de newsletter ? ou pas / reliées au mail d'osm ? possible de le récupérer ? sinon avec un formulaire ad-hoc).

**Comment by overflorian** [comment]
Pour info les services qui pourraient être intéressant pour mieux gérer les notifs dans le futur https://www.codeur.com/blog/outils-notifications-push-web/

**Comment by PanierAvide** [comment]
C'est implémenté : lors de l'envoi d'une contribution, une notification est créée si un badge a été obtenu. Celle-ci est visible dans le menu, et un symbole de cloche apparaît tant que le menu n'est pas cliqué ou qu'on ne change pas de page.

**Comment by overflorian** [comment]
Très cool, merci. On pourrait avoir un screenshot stp ?
@nlehuby m'a fait remarqué que ceux qui ont 3 points ont sûrement contribué une seule fois.
Auront-ils 2 badges qui s'affichent à ce moment là ? (1 point + 3 points ?). ça serait un peu bizarre.

Dans ce cas, on voudrait peut-être créer un badge "1ère contribution" plutôt que de compter en points ?
Le prochain badge pourrait arriver lorsque l'utilisateur atteint 6 points.

**Comment by PanierAvide** [comment]
![Capture d’écran 2020-09-30 à 11 19 18](https://user-images.githubusercontent.com/1349014/94667307-f339a980-030e-11eb-9647-f7deaa900763.png)

![Capture d’écran 2020-09-30 à 11 20 11](https://user-images.githubusercontent.com/1349014/94667296-efa62280-030e-11eb-939e-8bf59c691f47.png)

Pour les points, ça dépend du type de contribution (et aussi du projet du mois...), exemple sur les DAE si on modifie un DAE existant on gagne 1 point, si on en créé un on gagne 3 points. On ne peut pas savoir à l'avance quelle sera la contribution réalisée. Par contre il n'y aura jamais deux badges 1 point et 3 points gagnés en même temps (c'est filtré en base de données).

**Comment by overflorian** [comment]
Merci, ça déchire. Je vois que tu as mis la cloche à côté du picto "utilisateur". Mon idée était qu'il le remplace, ça prend moins de place sur l'écran. Qu'en penses-tu ?

**Comment by PanierAvide** [comment]
Question de facilité d'implémentation, puis j'aimais bien l'aspect "badge"... :sweat_smile:

**Comment by overflorian** [comment]
Je ne suis pas très convaincu mais c'est un détail donc laissons comme ça ;)
