### ISSUE TITLE
Statistiques de base - 1er round

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#63]
A la fin du pdm DAE, ça serait bien de connaître :
1. le nombre de visiteurs uniques sur la homepage
2. le nombre de visiteurs uniques sur la carte
3. le nombre de contributeurs uniques aux données OSM
4. le nombre de contributeurs uniques aux notes OSM

**Comment by overflorian** [comment]
Sur proposition de @nlehuby pourrait-on SVP également connaître la proportion de contributeurs au pdm qui l'on fait via l'éditeur en ligne que nous avons créé ? Pour savoir si on doit plutôt miser dessus dans le futur ou plutôt favoriser les outils conventionnels.

**Comment by PanierAvide** [comment]
Au 29 septembre :
- 195 contributeurs uniques aux données (page du projet sur pdm.fr)
- 22% des contributeurs ont utilisé ProjetDuMois.fr (via [OsmCha](https://osmcha.org/?filters=%7B%22date__gte%22%3A%5B%7B%22label%22%3A%222020-08-23%22%2C%22value%22%3A%222020-08-23%22%7D%5D%2C%22editor%22%3A%5B%7B%22label%22%3A%22ProjetDuMois.fr%22%2C%22value%22%3A%22ProjetDuMois.fr%22%7D%5D%7D))
- 21 contributeurs uniques OSM authentifiés aux notes + 49 notes créées par des utilisateurs anonymes (via [NotesReview](https://ent8r.github.io/NotesReview/?query=%23deficoeur&limit=10000&closed=true&from=2020-08-24&map=3%2F18.4796%2F25.4883))

**Comment by overflorian** [comment]
Merci.
- 200 contributeurs, c'est un score honorable pour une premier test. Il va falloir réfléchir aux moyens d'augmenter ce chiffre.

- 22% qui utilisent l'éditeur, c'est moins que ce que je pensais mais il me semble que c'est suffisant pour nous pousser à continuer à développer l'outil de contribution intégré.
à moins que .... j'ai l'impression que l'on veut pousser à la dissociation "contributeurs qui résolvent les notes VS ceux qui les crééent". Pour moi ça revient à dire qu'on devrait organiser la contribution entre les contributeurs identifiés VS ceux qui n'ont pas de compte. Dans ce scénario, seuls les contributeurs avancés utiliseraient l'outil pour contribuer directement à OSM, ce qui pousse dans la direction de ne pas investir trop dans l'éditeur intégré.
Quel est votre avis @PanierAvide @nlehuby @vdct et les autres ?

**Comment by PanierAvide** [comment]
À noter que les 22% de contributeurs via l'éditeur intégré ne prennent pas en compte les contributions non authentifiées. On a aujourd'hui 50 notes anonymes créées via l'éditeur de pdm.fr, soit 95% des notes anonymes créées durant le projet du mois.

Mon retour perso c'est que l'éditeur intégré pdm.fr offre une expérience d'édition sur mobile :
- Plus simple que Vespucci
- Plus orientée thématique avec les points Osmose comparé à MapContrib
- Permet de créer des notes textes de manière _largement_ plus simple que OSM.org
- Mais pas encore aussi agréable que StreetComplete

Le seul défaut c'est quand on perd la connexion Internet :sweat_smile:

**Comment by pyrog** [comment]
Perso je n'utilisais pas l'éditeur intégré car il manque principalement l'affichage et la publication de **photos** et quelques champs.

Par contre pour les notes c'est bien plus pratique qu'avec JOSM. Avec les photos à la NotesReview ça serait parfait.

**Comment by overflorian** [comment]
Oui, il y a clairement un truc à faire qui ressemble à NotesReview pour simplifier encore la création et le traitement des notes en intégrant des photos.
Je creuse la possibilité de création de notes OSM depuis Twitter et Instagram en ce moment.

**Comment by nlehuby** [comment]
concernant la création de notes via Twitter, il y avait [ce bot twitter](https://twitter.com/osmthis) qui n'a plus l'air actif qui faisait bien le job dans mon souvenir ([code source](https://github.com/alexandrz/osmthis))

J'aimais bien l'idée d'un projet du mois qui te fait progresser dans ta pratique individuelle d'OSM en te faisant découvrir des outils différents de ton utilisation quotidienne (MapRoulette, Osmose, MapComplete, StreetComplete, MapComplete, Pic4Review, NotesReview, etc en fonction du sujet). Je trouve qu'on perd un peu ce côté stimulation et apprentissage en cherchant à faire un outil unique pour couvrir tous les besoins du projet du mois.

En tout cas, on a l'air d'avoir une tendance nette à l'utilisation de notes, y compris anonymes, et ça me semble être une piste très intéressante à creuser pour l'avenir. Donc je dirais qu'on devrait prioritairement investir dans l'éditeur intégré pour les personna noobs

**Comment by PanierAvide** [comment]
+1 pour les notes et un outil simple à destination des débutants. Si ça fonctionne bien pour un débutant, ça sera efficace également pour les contributeurs avancés.
