### ISSUE TITLE
Montrer les POIs superposés

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#65]
Plusieurs POI peuvent être superposés (cas de DAEs `gid = 5169, 5170 et 5171`).

En cliquant sur la position, montrer tous les POIs sous forme de liste (cf. Ça Reste Ouvert) ou "exploser" les points (cf. [GraveMap](http://graves.wiki/#/map/@48.86289,2.28437,18z)).

![Screenshot_2020-09-28 gravemap](https://user-images.githubusercontent.com/2158081/94416517-3e24b700-017f-11eb-832b-c317636d2560.png)

**Comment by PanierAvide** [comment]
C'est ajouté et en prod :wink:

**Comment by pyrog** [comment]
Fonctionne pour le [Grand frais du Puy en Velay](https://projetdumois.fr/projects/2020-09_aed/map#sidebar&map=14.41/45.05137/3.90437)
<img width="501" alt="Capture d’écran 2020-09-29 à 09 21 36" src="https://user-images.githubusercontent.com/2158081/94526031-332c5e00-0235-11eb-857f-9ff5e4c27000.png">

Mais pas pour les 20 défibrillateurs du [centre hospitalier Sainte-Marie](https://projetdumois.fr/projects/2020-09_aed/map#sidebar&map=16/45.051499/3.90093) (`gid=15753` et suivants).

Est-ce [Osmose](http://osmose.openstreetmap.fr/fr/map/#zoom=18&lat=45.052082&lon=3.901498&item=2100%2C8210%2C8211%2C8212%2C8370&level=1%2C2%2C3&tags=&fixable=) qui n'en affiche qu'un ?
Ou est-ce que ça fonctionne uniquement quand les POIs superposés sont dans des couches différentes ?

**Comment by PanierAvide** [comment]
À priori Osmose en renvoie bien plusieurs, c'est donc une histoire de gestion du clic sur les données. Je vais regarder.

**Comment by PanierAvide** [comment]
C'est corrigé, merci du retour :smiley:
