### ISSUE TITLE
Définir des personas

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#66]
Pour faire suite à https://github.com/vdct/ProjetDuMois/issues/62 écrivons les personas de nos utilisateurs : (à compléter)

### Mickaël
Mickaël a 25 ans, il est étudiant en sociologie. Il a un PC sous Windows et l'essentiel de ses interactions sociales numériques se déroulent sur son smartphone Android, notamment via Whatsapp, Instagram et Tinder. Il a une utilisation basique de l'informatique, sauf le pack MS Office qu'il maîtrise bien.
Il connaît un peu OSM et sympathise à la cause mais il n'a jamais contribué.
Un contributeur avancé lui conseille de commencer à contribuer via PdM. Ce mois-ci ce sont les DAE. Mickaël en a repéré certains à la Fac et il aimerait les rajouter sur la carte. Le lundi matin, avant son cours, il a 5 min, prends son smartphone, se rend sur pdm.fr pour la première fois. Il comprends qu'il doit créer un compte OSM, le créé, puis arrive sur la carte.

### Nathalie
Nathalie a 37 ans. Elle est ingénieur en agronomie. Après avoir bossé 10 ans dans la grande distribution, elle ouvre son petit commerce de proximité pour vendre des fruits et légumes bio en circuit court à Evry. Elle ne connaît pas grand chose à l'informatique, elle a bien un smartphone mais ne l'utilise pas beaucoup. Elle a très peu de temps à sa disposition. Elle aimerait promouvoir son commerce sur OSM en modifiant simplement ses informations. Elle ne compte pas faire d'autre contribution.

**Comment by PanierAvide** [comment]
### Ambroise

Ambroise a 51 ans, elle travaille à temps partiel dans la grande distribution. Elle dispose d'un ordinateur portable sous Windows qu'elle utilise pour le traitement de texte et les démarches en ligne. Elle utilise son smartphone pour rester en contact avec sa famille et ses amis via Facebook ou SMS. Elle connaît vaguement OSM de par son fils mais n'a jamais contribué directement. Elle a participé au projet du mois sur les défibrillateurs en envoyant à son fils des photos et descriptions de DAE par MMS. Elle n'a pas contribué via pdm.fr car a peur de casser des données, mais a utilisé la carte pour repérer les manques.

### Coralie

Coralie a 26 ans et travaille dans un service public. Elle dispose d'un PC portable sous Linux et d'un smartphone Android. Elle connaît et contribue ponctuellement à OpenStreetMap, notamment lors des cartoparties humanitaires depuis chez elle. Elle n'a pas ajouté de DAE sur le projet du mois car ceux qu'elles connaissaient étaient déjà renseignés, et n'a pas le temps de rechercher au-delà de ses trajets habituels. Elle participe aux projets du mois quand ceux-ci l'intéressent, elle avait par exemple contribué à Ça reste ouvert ou aux panneaux électoraux (qui se voient depuis le bus).

**Comment by overflorian** [comment]
@nlehuby peux-tu stp détailler les tiens ?

**Comment by overflorian** [comment]
### Jean
Jean a 28 ans, il est SIGiste à la ville de Vitré. Expert métier, il est également sympathisant et contributeur à OSM à la fois pour des raisons personnelles et professionnelles. Il a accès aux données complètes sur le périmètre de sa commune. Il n'est intéressé que pour contribuer sur ce périmètre.
La mairie, à son grand regret, n'a pas débloqué les budgets nécessaires pour une politique d'open data efficace. Il est néanmoins prêt à utiliser ces données pour améliorer OSM de manière officieuse.
Sur des sujets précis qui lui apportent un bénéfice personnel et/ou pro, il peut passer beaucoup de temps et mettre son expertise au service du pdm pour finir dans les tops contributeurs : https://projetdumois.fr/users/SIG%20Vitr%C3%A9%20Communaut%C3%A9
Avant tout, il manipule des bases de données. Il utilise les outils avancés de SIGiste et/ou de la communauté OSM : QGIS, JOSM.

### Olivier
Olivier a 35 ans. Il est employé de bureau mais la plupart de son temps libre est occupé par sa mission bénévole au sein de la croix rouge à Montrouge ; il a plusieurs formation de premier secours et au fil des ans, il est devenu responsable de sa mission locale. Il connaît très bien certains sujets comme les défibrillateurs : il ne contribuera que sur ces sujets précis qui couvrent ses "besoins métiers" : il aura l'usage dans son quotidien d'infos très précises comme "ce DAE appelle automatiquement le SAMU lorsqu'il est ouvert" ou "ce DAE est en état de fonctionnement" ou "ce DAE est accessible maintenant, en urgence, quand j'en ai besoin".
Il pourrait participer à une mapping party pour cartographier tous les DAE de la ville à condition que 1. l'outil de mapping soit simple à utiliser 2. il couvre totalement ses besoins métier 3. on arrive à réintégrer dans son appli de la croix rouge les données créées

### Donat
Donat est systématiquement dans le top 3 des contributeurs du pdm. Contributeur avancé, on le connaît bien. Il est mobilisable de manière régulière via talk-fr pour créer une grande quantité de données mais aussi pour résoudre des notes déjà créées et accompagner / guider des contributeurs moins expérimentés.
Il n'utilisera l'éditeur pdm seulement s'il le considère meilleur que ses outils habituels de contribution auxquels il est habitué. Il peut-être amené à utiliser plusieurs outils de contribution qu'il considère comme complémentaires : JOSM, iD, Street Complete, ... il lira/écrira la doc technique et participera au projet de manière proactive.

**Comment by overflorian** [comment]
OK j'ai l'impression que se dégagent **2 meta-personas principaux** que l'on devrait considérer indépendamment : les contributeurs avancés (que je nommerait **les geeks**) et les personnes qui ne connaissent pas OSM (que je nommerai **les noobs**).

## Noobs
Catégorie de persona | Persona concerné | Spécificité | Action à envisager
-- | -- | -- | --
Les mamans | Ambroise | Très faible appétence pour la technique, « envie d’aider », ne créera pas de compte OSM (« trop compliqué »). | Se passer d’un compte OSM pour contribuer, mettre en place un système de parrainage / accompagnement par un geek, déléguer au geek la contribution dans OSM
Les amis | Nathalie, Mickaël | Prêt à créer un compte OSM, mais bon, « c’est chiant », besoin de simplification extrême sinon ne contribuera pas. Utilise un ou plusieurs de ces réseaux sociaux : Facebook, Whatsapp, Instagram | Se passer d’un compte OSM et/ou la rassurer dans ses premières contributions OSM, mettre en place un système de parrainage / accompagnement par un geek, communiquer sur ses réseaux sociaux
Les connaissances | Coralie | Dispose déjà d’un compte OSM, besoin de simplicité mais prêt à apprendre. Utilise les mêmes réseaux sociaux que « les amis » | La stimuler pour augmenter sa fréquence de contribution, communiquer sur ses réseaux sociaux

## Geeks
Catégorie de persona | Persona concerné | Spécificité | Action à envisager
-- | -- | -- | --
Les experts métiers | Olivier | Centré sur son métier : il contribuera qu’à un seul pdm, peut éventuellement créer un compte OSM, besoin d’exhaustivité, ré-utilisateur des données produites, possible mainteneur long terme | Le contacter avant/pendant/après le pdm : il est exigeant mais il est important de l’inclure pour creuser un sujet jusqu’au bout. Publier les données sur data.gouv
Les sympathisants | Jean | Très technique, centré sur un territoire limité, fournisseur et/ou créateur de données | Lui fournir une doc technique complète, l’informer via talk-fr
Les potes d’osm-fr | Donat | Réalise 80 % des contribution, valorise la qualité et l’exhaustivité. Super-héro des temps modernes. | Créer et maintenir une dynamique de groupe durant 1 mois. Lui simplifier le travail massif. Lui confier la fermeture des notes / l’accompagnement des noobs

Mon idée du moment, c'est que projetdumois.fr pourrait se spécialiser encore plus pour répondre au besoin des geeks uniquement, et on créerait un autre outil/mécanisme plus spécifiquement adapté aux noobs.
Néanmoins avant d'aller plus loin, j'aimerai savoir si vous partagez mon analyse, s'il nous manque des personas, si mes regroupements sont pertinents.

**Comment by PanierAvide** [comment]
Ça me semble assez exhaustif au niveau des personas.

**Comment by PanierAvide** [comment]
Je ferme comme on a les personas en tête désormais

**Comment by pandark** [comment]
Je remarque que tous les personas « Noob » sont des femmes et tous les personas geeks sont des hommes. :confused:

**Comment by pandark** [comment]
Je remarque que tous les personas « Noob » sont des femmes et tous les personas « Geeks » sont des hommes. :confused:

**Comment by overflorian** [comment]
> Je remarque que tous les personas « Noob » sont des femmes et tous les personas « Geeks » sont des hommes. :confused:

Bonjour, en effet les personas sont très stéréotypés. Il est normal qu'il en soit ainsi : c'est le but même de cet outil de travail interne à l'équipe que de créer des personnages très polarisés et stéréotypés. C'est ce qui leur donne le plus de force et donc d'efficacité dans notre analyse.
Les personas n'ont pas vocation à corriger les stéréotypes mais au contraire à refléter l'inconscient collectif réel et non pas souhaité.

En marketing, il faut bien différencier les personas avec les cibles marketing qui, elles, ont vocation à prendre en compte -et je l'espère tout comme toi, corriger !- les biais (notamment sexistes).
