### ISSUE TITLE
Zoomer lorsque l'on rajoute un point

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#67]
Je pense que si l'on veut bien placer au bon endroit sur la carte des objets aussi petits que des DAE, il faut être au niveau de zoom 18 minimum.
D'où ma suggestion : lorsque l'on rajoute un POI (que ce soit une note ou un node OSM) c'est à dire au moment où s'affiche l'écran "Déplacer la carte pour positionner l'objet à créer", zoomer automatiquement au zoom 18

**Comment by PanierAvide** [comment]
C'est fait
