### ISSUE TITLE
Tuiles > vectoriel

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#68]
Et si on passait à un fond de carte vectoriel ?
Avec comme idée sous-jacente une éventuelle personnalisation du rendu en fonction du sujet traité. Sans oublier tous les avantages écrasants du vectoriel pour l'amélioration de l'UX, évidemment.

**Comment by PanierAvide** [comment]
Quand l'asso aura des tuiles vectorielles (ou les poules des dents) ? :smile: 

Sur le principe oui, mais pour l'instant on a pas d'autre choix que d'utiliser un fournisseur tiers, potentiellement à un moment payant. Comment on gère ça ?

**Comment by frodrigo** [comment]
Trouvez un serveur supportant du docker et je vous installe un Makina Maps, 100 Go de disque pour la France. 500 Go pour l’Europe.
https://github.com/makina-maps/makina-maps
Ça donne ça https://dev2-makinamaps.makina-corpus.net

**Comment by overflorian** [comment]
@PanierAvide on a ptét envie de viser l'Europe ? :D 
(dis le mec qui a déjà en tête projectofthemonth.com)

**Comment by PanierAvide** [comment]
France ce sera déjà bien je pense. C'est à discuter sur la liste tech pour avoir un serveur au niveau de l'asso. À part l'espace disque et le Docker, quelles sont les recommandations pour la machine ?

**Comment by frodrigo** [comment]
Comme un serveur de tuiles raster, du ssd et du cpu et de la bande passante.

**Comment by pyrog** [comment]
@frodrigo J'ai vu que tu avais mis le lien vers le [style](https://dev2-makinamaps.makina-corpus.net/styles/bright/style.json).

Peut-on l'éditer et lui passer en paramètre par exemple pour masquer ou mettre en évidence certains POIs ?

**Comment by PanierAvide** [comment]
@pyrog hors sujet pour ce ticket ?

@frodrigo merci pour les infos. Tu peux te charger de faire la demande sur la liste tech (ou mettre en place le serveur si tu as la main sur l'infra) ? Ou j'envoie la demande ?

**Comment by frodrigo** [comment]
@pyrog C'est un style de base pour OpenMapTiles https://github.com/openmaptiles/osm-bright-gl-style

C'est peut-être un sujet sensible. Il faut passer par une demande à l'asso ou au moins à la list tech.

**Comment by PanierAvide** [comment]
Effectivement ça vaut le coup d'en parler, les retours qu'il y avait eu sur talk-fr suite au sujet lancé par Florian étaient positifs. Une discussion sur Loomio ?

**Comment by pyrog** [comment]
Ok merci. En tout cas le résultat est nickel 😃 

On peut afficher un fond sans POI et rajouter une ou plusieurs couches avec les POI qui nous intéressent comme dans ProjetDuMois.

**Comment by frodrigo** [comment]
Je ne sais pas si même techniquement l'asso à quoi heberger ça @Marc-marc-marc

**Comment by frodrigo** [comment]
@PanierAvide peut être plutôt sur la liste de l'asso, plus ouvert et moins orienté décision.

**Comment by PanierAvide** [comment]
Sur la liste "osm-fr asso" ? Je sais pas si ça vaut le coup comme ça a déjà été discuté il y a quelques jours sur talk-fr, c'est peut-être le moment justement de décider et de passer sur un vote/échange Loomio ?

**Comment by frodrigo** [comment]
Sur talk-fr les fans du vecto ont juste dit "oui, c'est cool".

Héberger un service de tuiles supplémentaire au sein de l'asso, ce n'est pas anodin du tout.

**Comment by PanierAvide** [comment]
OK je comprends, donc d'abord un échange avec tech + liste asso ?

**Comment by frodrigo** [comment]
Oui, je te laisse faire, mais il y a deux questions la volonté "politique" de l'asso, et la faisabilité technique/humain.

**Comment by PanierAvide** [comment]
@overflorian tu gères le politique sur la liste asso ? Je lance le sujet sur tech pour la faisabilité technique/humaine.

**Comment by overflorian** [comment]
ok

**Comment by overflorian** [comment]
OK, maintenant qu'on a un serveur, quelles sont les étapes suivantes @frodrigo ?

**Comment by frodrigo** [comment]
Prépérer le serveur, pour l'instant il manque le ssd.

**Comment by overflorian** [comment]
Ok. Dis moi si tu as besoin de moi à un moment.

**Comment by frodrigo** [comment]
C'est en ligne http://tile-vect.openstreetmap.fr/

http://listes.openstreetmap.fr/wws/arc/association/2020-10/msg00016.html

**Comment by overflorian** [comment]
Super ! Je ne pensais pas que ça irait si vite.
Tu aurais des pistes pour accélérer le temps de chargement ? A moins que ma connexion ne soit particulièrement lente ce matin, j'ai l'impression qu'on peut faire mieux.

**Comment by pyrog** [comment]
C'est probablement que le cache est vide (il n'y a aucune tuile pré-calculée).
Affiche ce [lieu](http://tile-vect.openstreetmap.fr/#map=15.62/46.575155/5.749067) en cache pour voir si c'est rapide.

**Comment by PanierAvide** [comment]
@frodrigo Super, merci :smile: Je vois que l'accès en HTTPS est en erreur (certificat valide uniquement pour projetdumois.fr, osm14...), as-tu la main pour mettre à jour le certificat ?

Sinon, quels sont les points à lever avant de basculer projetdumois.fr sur ce service vectoriel ?

**Comment by frodrigo** [comment]
J'ai la main que sur le contenu, pas le contenant. Issue à jouter ici : https://github.com/osm-fr/infrastructure/issues

@overflorian c'es quoi que tu trouve lent ? le chargement initial (js), ou les tuiles ? Pour les deux il y a des effets de caches.

**Comment by frodrigo** [comment]
HTTPS dispo

**Comment by overflorian** [comment]
J'ai l'impression que c'est surtout le chargement des tuiles qui est lent. Parfois je dirai même très lent. 
Que peut-on faire pour palier à ça ?

@frodrigo quelles seraient les prochaines étapes si l'on voulait l'utiliser sur projetdumois.fr ?
@PanierAvide chaud pour tester ça ? On pourrait par exemple imaginer que la couche vecto s'affiche au 2ème clic sur le bouton LAYERS, après l'orthophoto.

**Comment by frodrigo** [comment]
On peut outiller un peu plus le serveur pour avoir une idée de ce qu'il se passe. Mais il faut aussi que ce soit utilisé pour avoir des info qui remontent.
Donc pour moi go pour le mettre déjà sur pdm.fr

**Comment by overflorian** [comment]
OK donc si je comprends bien tu veux un peu de trafic pour monitorer le truc ? Dans ce cas, utilisons-le par défaut sur pdm.fr

**Comment by frodrigo** [comment]
oui

**Comment by PanierAvide** [comment]
J'ai basculé sur la prod de projetdumois.fr sur le serveur de tuiles vectorielles.

**Comment by pyrog** [comment]
Super, merci à tous les deux 😃 
La tuile met quelques dixièmes de seconde à apparaitre, mais ça reste fluide.

Par contre il y a un petit bug : en cliquant sur la carte, PdM retourne les POIs du fond de carte vectoriel 
<img width="33%" alt="Sélection de POI" src="https://user-images.githubusercontent.com/2158081/96351465-be25a900-10bb-11eb-9998-b7c2fa11f439.png"> <img width="33%" alt="Sélection de Rennes" src="https://user-images.githubusercontent.com/2158081/96351479-d5649680-10bb-11eb-90df-1718dafe83b2.png">

**Comment by PanierAvide** [comment]
Bien vu, c'est corrigé, merci du signalement :wink:

**Comment by PanierAvide** [comment]
@frodrigo Est-ce qu'il y aurait possibilité d'afficher les POIs sur le rendu "basic" ? Ça fait défaut et le style "bright" qui les affiche n'est pas _beau_ à mon goût.

**Comment by frodrigo** [comment]
> @frodrigo Est-ce qu'il y aurait possibilité d'afficher les POIs (commerces, services) sur le rendu "basic" ? Ça fait défaut et le style "bright" qui les affiche n'est pas _beau_ à mon goût.

Techniquement pas de problème, mais il faut le faire. Il y a aussi d'autres style de dispo https://openmaptiles.org/styles/

Il y a aussi liberty https://github.com/maputnik/osm-liberty

**Comment by PanierAvide** [comment]
J'aime bien Liberty, quelles sont les étapes pour rendre le style disponible ?

**Comment by pyrog** [comment]
Tu peux éditer les styles depuis [cloud.maptiler.com/customize](https://cloud.maptiler.com/customize/?utm_source=qgis&utm_medium=product&utm_campaign=qgis-plugin#basic/1/0/0).

[Maputnik](https://openmaptiles.org/docs/style/maputnik/) fait ça aussi…
Et de mémoire Yohann Boniface a écrit un bon éditeur 😃

**Comment by pyrog** [comment]
> J'aime bien Liberty, quelles sont les étapes pour rendre le style disponible ?

Tu remplaces dans ton code  basic par le style que tu aimes 😄 https://github.com/vdct/ProjetDuMois/blob/603f4df27a0323c29bac41c13ce3e6a2da0fbb9b/website/utils.js#L36

**Comment by PanierAvide** [comment]
Ah bah oui en fait le style Liberty est déjà dispo https://tile-vect.openstreetmap.fr/styles/liberty/style.json :grin:

**Comment by PanierAvide** [comment]
(je n'étais pas sûr que la feuille de style soit dispo côté serveur de tuiles)

**Comment by frodrigo** [comment]
> J'aime bien Liberty, quelles sont les étapes pour rendre le style disponible ?

> (je n'étais pas sûr que la feuille de style soit dispo côté serveur de tuiles)

Je viens juste de l'ajouter.

**Comment by PanierAvide** [comment]
Trop d'efficacité, merci à toi :wink:

**Comment by PanierAvide** [comment]
Je l'ai changé sur pdm.fr

**Comment by frodrigo** [comment]
@PanierAvide J'ai ajouté un second style "hybride satellite" basé sur l'ortho IGN si tu veux l'utiliser.
http://tile-vect.openstreetmap.fr/#map=19.21/45.8479262/1.2806174&style=satellite-hybrid-bdortho

**Comment by PanierAvide** [comment]
Il est sympa, à tester :smile:

**Comment by frodrigo** [comment]
On a munin depuis hier http://munin.openstreetmap.fr/osm14.openstreetmap.fr/tile-vect.vm.openstreetmap.fr/index.html
Si besoin on peut ajouter des sous domaine a. b. c. pour faire plus de téléchargements en même temps. Mais ça a un peu moins de sens avec les tuiles vectorielles, elles sont 4x plus grandes.

**Comment by PanierAvide** [comment]
Je ferme le ticket comme les tuiles vectorielles tournent sans problème majeur.
