### ISSUE TITLE
Adhérer aux "principles for digital development"

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#69]
Je propose de montrer notre adhésion aux valeurs portées par "principles for digital development" qui me semblent en totale adéquation avec le projet :
- Design With the User
- Understand the Existing Ecosystem
- Design for Scale
- Build for Sustainability
- Be Data Driven
- Use Open Standards, Open Data, Open Source, and Open Innovation
- Reuse and Improve
- Address Privacy & Security
- Be Collaborative

Si vous êtes chauds, alors on peut tout simplement rajouter dans le footer ce petit logo https://digitalprinciples.org/wp-content/uploads/PDD-UpdatedLogo-1.png qui renvoit vers l'URL https://digitalprinciples.org

**Comment by PanierAvide** [comment]
Je ne connais pas du tout cette initiative, mais je vois que CartONG et HOT en font parti. Si on veut techniquement adhérer il y a plus de points que juste ajouter le logo : https://digitalprinciples.org/endorse/

Au-delà de l'affichage, qu'est-ce que cela nous apporte ?

**Comment by overflorian** [comment]
La gloire ;)
En vrai je pense que ça renforce le positionnement "communautaire" du projet. On a la tête dans le guidon et on maîtrise tous les concepts des digital principles mais pour un visiteur qui arrive sur le site et qui ne connaît pas OSM, il peut se poser des questions sur nos motivations, notre méthodo ... les digital principles me paraissent un bon moyen de transmettre nos valeur via un simple logo.

**Comment by PanierAvide** [comment]
OK pourquoi pas, il faut donc écrire la lettre en question, tu t'en charges ? :smile:

**Comment by overflorian** [comment]
c'est fait, je te tiens au jus de coco

**Comment by overflorian** [comment]
Je viens d'avoir une réponse positive :)

> Dear Florian,
Thank you for your email and endorsing the Principles for Digital Development! We are thrilled to add Projet du Mois as a formal endorser. We will add your logo to our website (with a link back to your website) by the end of the week and you can check on our [endorsers page](https://digitalprinciples.org/endorse/endorsers/) to ensure it’s posted.
I’m also assuming that you will be serving as our point of contact? If so, I’m looking forward to working closely with you. I am aware that this is likely a very busy time for everyone but would like to opportunities of engagement: we can set up a call if you are interested in writing a case study on Projet du Mois or host a Digital Principles training for your team. We also have a webinar + podcast series “[Pulse on the Principles](https://digitalprinciples.org/pulse-on-the-principles/)” and could explore future opportunities for collaboration or guest speaking opportunities! You can also follow us on [Twitter](https://twitter.com/digiprinciples), or help us test out our new resources, among other things.
You can access all our other logos and collateral on our [Advocacy Toolkit](https://digitalprinciples.org/advocacy-toolkit/). Please let me know if you have any questions, and I’m really looking forward to working with Projet du Mois to see how we can best partner and keep your team updated on new and upcoming Digital Principles resources.
Warmly,
Claudine Lim  |  Senior Associate, Principles for Digital Development

@PanierAvide puis-je te laisser rajouter leur logo en footer avec un lien vers leur site web stp ? Quand ça sera fait je tweeterai la nouvelle.

**Comment by PanierAvide** [comment]
Logo et liens ajoutés

**Comment by overflorian** [comment]
👍
