### ISSUE TITLE
Idées de projets du mois

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#70]
- ronds-points
- parkings 
(en intégrant les nouvelles "scènes" de mapillary ? Cf. https://blog.mapillary.com/update/2020/09/16/extending-object-detections-to-scene-classes.html)
- les lieux les plus communs dans les villages, où peu de contributions sont faites :
  - mairie
  - église
  - bureau de poste
  - supérette
  - bureau de tabac
  - bar
  - boulangerie

**Comment by pyrog** [comment]
> Les lieux les plus communs dans les villages

- associations
- salles des fêtes

**Comment by PanierAvide** [comment]
* Bornes incendies
* Bancs
* Accessibilité PMR commerces/lieux publics

**Comment by overflorian** [comment]
- Arrêts de bus
- nombre d'étages des bâtiments (utile pour un rendu 3D)
- équipements vélo

**Comment by MatthieuOSM** [comment]
- MSAP / France Services : c'est d'actualité mais peut-être à envisager pour plus tard (le gouvernement a annoncé un plan pour jusqu'à 2022), un début d'ébauche wiki pour plus d'infos https://wiki.openstreetmap.org/wiki/Msap
- Marchés plein air / couvert
- Gîte / Maison d'hôte
- Vente en direct / Circuit court (en général les shop=farm), ya un gros travail pour en avoir ajouté quelque uns pendant le confinement, c'est peu valorisé sur les cartes en général sauf par les chambres d'agriculture et autres sites spécialisés dont AMAP

**Comment by nlehuby** [comment]
+1 pour les services publics. Ça me semble assez prioritaire d'avoir ces éléments dans OSM
On a une [analyse Osmose](https://osmose.openstreetmap.fr/fr/errors/?country=france_local_db&item=8110&level=1%2C2%2C3) sur l'annuaire du Service Public qui nous compare les Mairies, Pôle Emploi, Tribunaux, Préfectures, CAF, CPAM et quelques autres. Les résultats de l'analyse restent à affiner mais ça donne déjà de la matière, surtout si on inclut les MSAP.

**Comment by PanierAvide** [comment]
* Aire de stationnement mini-van / camping cars (hauteurs autorisées, gratuit/payant, durée)
* Prise électriques / recharge USB téléphone en accès libre

**Comment by MatthieuOSM** [comment]
> 
> 
>     * Aire de stationnement mini-van / camping cars (hauteurs autorisées, gratuit/payant, durée)
> 
>     * Prise électriques / recharge USB téléphone en accès libre

On peut aussi ajouter les bornes de recharge en eau/électricité qui se trouve sur les parking, camping et éventuellement berges pour les bateaux (ça sert aussi aux camping-car du coup). Il y a peut-être d'autres équipements auxquels je ne pense pas mais c'est courant sans jeu de mots.

**Comment by MatthieuOSM** [comment]
Le gouvernement souhaite étendre les bornes de recharge électrique aux GMS #balancetaborne
https://www.lsa-conso.fr/la-grande-distribution-s-engage-a-deployer-des-milliers-de-bornes-de-recharge-electrique,361213

**Comment by PanierAvide** [comment]
* Les points d'eau

**Comment by pyrog** [comment]
Faire le nettoyage des marques et opérateurs dans [Name-Suggestion-Index](https://nsi.guide).

Compléter la carte et en profiter pour rajouter :
* le site web du magasin (pas le site national)
* le SIRET
* le numéro de téléphone, de fax
* l'adresse tél (du magasin)
* l'adresse Facebook (du magasin)
* …

**Comment by rouelibre1** [comment]
Quelques idées supplémentaires :

- le stationnement vélo en voirie (arceaux)
- les restaurants et magasins vegan ou végétariens
- les caméras de vidéosurveillance

**Comment by ad-sige** [comment]
- Photomatons
