### ISSUE TITLE
Optimiser la homepage

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#71]
Sur la suggestion de https://twitter.com/OSM_Pontarlier on pourrait améliorer la disposition de la homepage.

Ma préoccupation est de savoir si le CTA principal reste au dessus de la ligne de flottaison.
Regardons les stats : https://gs.statcounter.com/screen-resolution-stats
Il y a encore 8,5% des utilisateurs qui ont une résolution de 640px de haut. Essayons d'être universels et de prendre cette hauteur comme référence. Laissons 40px pour l'interface, on arrive à une ligne de flottaison de 600px.
Voici ce que cela donne avec le site actuel :

![image](https://user-images.githubusercontent.com/11553211/94909997-53ae1f80-04a4-11eb-9fb9-e2bea9617b12.png)
Le CTA principal n'apparaît pas : on n'est pas dans les clous ! L'utilisateur devra scroller, on diminue le taux de conversion.

D'où ma nouvelle proposition :
![ligne de flottaison](https://user-images.githubusercontent.com/11553211/94911166-0468ee80-04a6-11eb-8123-61a5d6a75420.png)

Qu'en pensez-vous ?

**Comment by PanierAvide** [comment]
Ça me va, c'est vrai que le scroll ou double clic pour acccéder à la carte est pénible une fois qu'on sait que c'est pas optimal :smile:

**Comment by pyrog** [comment]
**CTA**, késako ?

Ce qui me fatigue c'est de cliquer sur participer, puis contribuer… 
Il y a un click de trop (voir 2) quand on connais le projet en cours.

Et aussi de voir 3 fois de suite le terme **Participer** et 2 fois **Contribuer**😉

Une fois que l'on contribue à une projet, un cookie pourrait depuis l'accueil nous envoyer directement sur la carte du projet 😃 

<img width="572" alt="Capture d’écran 2020-10-02 à 12 06 45" src="https://user-images.githubusercontent.com/2158081/94912556-1e0b3580-04a8-11eb-8abd-0779e92b95bd.png">

**Comment by overflorian** [comment]
CTA = call to action, désolé pour le jargon. Le CTA principal est le gros bouton que l'on a mis en bleu pour le différencier des autres en gris. C'est LE bouton sur lequel on veut que l'utilisateur clique avant tout.

`Ce qui me fatigue c'est de cliquer sur participer, puis contribuer…`
ok, ma maquette propose de corriger ça.

`Une fois que l'on contribue à une projet, un cookie pourrait depuis l'accueil nous envoyer directement sur la carte du projet smiley`
Idée intéressante. Perso, j'approuve ! Quand on est authentifié et que l'on a au moins 1 point dans la quête **en cours**, alors on est redirigé direct vers la carte. Par contre cela nécessite également de créer un bandeau d'acceptation des cookies. Adrien dis moi si tu veux que j'écrive le wording.

**Comment by PanierAvide** [comment]
Pour le cookie je suis pas convaincu, l'accueil permet d'accéder aux statistiques et projets précédents. Si on court-circuite l'accueil, comment accéder à ces éléments ?

**Comment by overflorian** [comment]
En effet c'est pénible : il faut pour cela cliquer sur le bouton sandwich puis sur le logo pour revenir à la page d'accueil.
On a deux solutions : soit on change rien, soit on intègre un accès rapide dans l'éditeur en lui-même. J'aime bien cette dernière option, je vous fait une maquette de ce à quoi cela pourrait ressembler.

**Comment by pyrog** [comment]
Par le logo [Projet du mois](https://projetdumois.fr/images/logo_mini.png) 😉 
Une fois le menu ouvert, il y a de la place pour faire apparaitre un lien vers les statistiques.

Le terme données donne accès essentiellement aux anciens projets (ou alors il manque un lien Autres projets ?)

**Comment by overflorian** [comment]
Ma proposition (accompagnée de quelques petites retouches sympas pour améliorer le tout :) ) :

![nouveau menu](https://user-images.githubusercontent.com/11553211/94927265-4f90fa80-04c2-11eb-9d27-c61ffe3f415b.png)

**Comment by overflorian** [comment]
du coup je découvre la dernière nouveauté : le choix du fond de carte dans le menu. Cool. Je propose de virer son titre en complément.

**Comment by PanierAvide** [comment]
OK pour la barre latérale, les accès rapides sont intéressants.

Mais je suis toujours pas convaincu par la redirection directe vers la carte sur la page d'accueil : est-ce qu'on a des exemples de sites qui font ça ? Ça me semble complètement contre-intuitif, au-delà de poser des questions techniques tordues (redirections en boucle, délai d'attente de la vérification de connexion à OSM...)

**Comment by overflorian** [comment]
Je suis personnellement ouvert aux deux possibilités : rediriger ou ne pas le faire.

- Argument pour : j'ai pas mal d'exemples de services qui n'affichent plus jamais la page d'accueil : gmail et tous les services en ligne google d'une manière générale, facebook, mais aussi les dashboards d'analytics.

- Argument contre : dans notre cas, à y penser, on a envie que les utilisateurs partagent l'URL de la landing page du projet du mois (ce mois-ci https://projetdumois.fr/projects/2020-09_aed). Or, s'il accèdent direct à l'éditeur, ils auront tendance à partager ce lien là.

**Comment by PanierAvide** [comment]
Le bouton d'accès à la carte est visible directement sur mobile, et j'ai changé quelques éléments de boutons / titre pour alléger.

**Comment by PanierAvide** [comment]
Une partie des améliorations de la barre latérale sur la carte sont implémentées : bouton KML et d'imagerie inversés, moins de titres, bons symboles de légende.

**Comment by overflorian** [comment]
Ok à la base ce bug concerne la homepage donc j'ai créée une note liée à ce qu'il reste à faire dans la barre de menu : https://github.com/vdct/ProjetDuMois/issues/85
J'ai l'impression qu'à ce stade, on n'a pas envie de mettre "top contributeurs" ni "autres projets du mois" donc je ferme ce bug.
