### ISSUE TITLE
Statistiques : afficher aussi les notes ajoutées

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#72]
Les notes sont aussi des contributions 😃 

Je propose donc de mettre la boite "**xxx** notes ajoutées" :
<img width="50%" alt="Capture d’écran 2020-10-02 à 12 36 41" src="https://user-images.githubusercontent.com/2158081/94914837-0df55500-04ac-11eb-928f-88816c8d1e8f.png">

Et pour le graphiques des notes, d'utiliser la couleur bleu pour les notes ajoutées (ce n'est pas une "erreur", mais une contribution)

**Comment by PanierAvide** [comment]
C'est fait, dans le même bloc avec le nombre de notes ouvertes + % de notes résolues.
