### ISSUE TITLE
Menu de la homepage sur mobile

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#73]
Aujourd'hui on a un menu de la homepage sur mobile qui affiche des icônes pas très explicites :
![image](https://user-images.githubusercontent.com/11553211/94931103-a1884f00-04c7-11eb-9141-0f609f9be3b7.png)

Plusieurs solutions :
1. on laisse comme ça
2. on rajoute du texte explicatif dans des onglets cf. https://material.io/components/tabs#usage soit avec les icônes :
<img width="50%" src="https://user-images.githubusercontent.com/11553211/94931982-bdd8bb80-04c8-11eb-86e8-d5620a65dcb0.png">

soit (2.bis) sans icônes :
<img width="50%" src="https://user-images.githubusercontent.com/11553211/94931989-c16c4280-04c8-11eb-92e4-aa026b6f080c.png">

3. on regroupe tout ça dans un menu ouvrable via un bouton sandwich :
![image](https://user-images.githubusercontent.com/11553211/94931388-004dc880-04c8-11eb-9cc7-a4e9f2f82e06.png)
4. on le vire carrément :
![sans menu](https://user-images.githubusercontent.com/11553211/94932765-ce3d6600-04c9-11eb-951b-21bfdfccda12.png)

Ma préférence va à la solution 4 : on vire le menu complètement sur mobile : la page n'est pas si longue à scroller et puis le logo dans le header permet de remonter tout en haut rapidement.
Quand l'utilisateur scrolle, le bandeau suivant reste stické en haut :
![sans menu extended](https://user-images.githubusercontent.com/11553211/94932848-e7461700-04c9-11eb-8317-3fcc91c688c9.png)

**Comment by AntoninCurtit** [comment]
> Ma préférence va à la solution 4 : on vire le menu complètement sur mobile : la page n'est pas si longue à scroller et puis le logo dans le header permet de remonter tout en haut rapidement.

+1

**Comment by PanierAvide** [comment]
Si on part sur le 4, le menu sur écran large/PC reste identique ?

**Comment by overflorian** [comment]
Je pencherai plutôt pour cette solution oui, mais on peut aussi envisager de le virer comme sur mobile.

**Comment by PanierAvide** [comment]
C'est implémenté et en ligne :wink:

**Comment by overflorian** [comment]
niquel, tu déchires, merci
