### ISSUE TITLE
Faciliter la création de signalements à la géolocalisation imprécise

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#74]
Le formulaire de saisie impose de remplir la **Localisation précise**.
Dans cet [exemple](https://www.openstreetmap.org/note/2373044), je voulais saisir uniquement un lien vers un article de journal dans le champ **Autres informations** 😉 

Du coup, le lien n'est pas cliquable depuis [NotesReview](https://ent8r.github.io/NotesReview/expert/?query=https%3A%2F%2Fwww.vosgesmatin.fr%2Ffaits-divers-justice%2F2020%2F10%2F02%2Fun-defibrillateur-operationnel) et le message est moins lisible que sur une note manuelle :
<img width="33%" alt="Capture d’écran 2020-10-04 à 09 22 06" src="https://user-images.githubusercontent.com/2158081/95009548-305dae80-0623-11eb-9182-6c0ceef4f64b.png"> <img width="33%" alt="Capture d’écran 2020-10-04 à 09 29 17" src="https://user-images.githubusercontent.com/2158081/95009661-1cff1300-0624-11eb-90e3-bf8713bac189.png">

**Comment by PanierAvide** [comment]
C'est plutôt un problème du côté de NotesReview (ou l'API OSM qui renvoie le texte de note en HTML), l'URL devrait être reconnue comme telle dans la note structurée et affiché sous forme de lien.

**Comment by pyrog** [comment]
Pour le lien oui, mais ma remarque initiale est à propose de l'obligation de saisir la localisation précise 😉

**Comment by PanierAvide** [comment]
Ha d'accord. Oui ça me semble important que la localisation précise soit remplie, c'est ça qui va faire gagner du temps pour retrouver le DAE sur le terrain.

**Comment by pyrog** [comment]
J'ai bien compris, mais quand la seule info est un article de journal dont le contenu est masqué, c'est difficile de préciser ça.

**Comment by PanierAvide** [comment]
C'est que ça doit faire l'objet d'une note plus générale pour que quelqu'un vérifie sur le terrain.

**Comment by overflorian** [comment]
J'ai l'impression qu'il y a 2 problèmes bien distincts que nous essayons de résoudre :
1. Comment booster la **création** de signalements à la géolocalisation imprécise ?
2. Comment simplifier la **résolution** de ces signalements ?

Concentrons-nous sur le premier problème pour commencer :
### 1. Création
On a plusieurs situations :
- **signalements contextuels :** les seules méta-données disponibles sont contextuelles : par exemple un URL, un commentaire texte, une photo non-géolocalisée. On ne dispose pas de géoloc précise.

Mon avis est que l'on ne devrait pas créer de notes pour cela, mais imaginer un système nouveau : en passant par Osmose peut-être ? De toute manière le système de signalement devra être pensé de bout-en-bout jusqu'à la résolution des signalements.

_Exemple : on centralise des signalements de sources hétéroclites (sites web, tweets, photos instagram non-géolocalisées, SMS ...) dans une même interface qui permet aux geeks du projet du mois de les résoudre à la chaîne. L'interface serait également pensée pour permettre la création de signalements directement : les geeks qui font une veille sur le sujet précis pourraient créer des signalements contextuels._

- **signalements à la localisation approximative :** les méta-données récupérées incluent des indications géographiques structurées mais moins précises qu'une géoloc de puce GPS.

_Par exemple : il y a 2 nouveaux DAE sur cette commune, ce département ..._
Dans un premier temps, on peut les traiter comme des _signalements contextuels_ mais à terme, on peut imaginer un système plus précis de statistiques / outil de résolution associé. Je pense en particulier à un outil du type [Keskimanque](https://keskimanque.pavie.info)

- **signalements géolocalisés :** Les méta-données récupérées incluent des indications géographiques structurées précises : on continue à utiliser le système de notes actuel qui me semble bien répondre au besoin

**Comment by pyrog** [comment]
> Mon avis est que l'on ne devrait pas créer de notes pour cela, mais imaginer un système nouveau 

Pourquoi réinventer la roue ?

Les notes (avec des mots-clés PdM) vont très bien 😃
On peut effectivement développer une moulinette qui peut récupérer automatiquement des textos… pour les transformer en notes.

Osmose est beaucoup trop lourd les notes sont universelles :
On peut utiliser PdM, l'excellent NotesReview, OSM, JOSM… pour les voir et les traiter.

**Comment by PanierAvide** [comment]
Pareil, j'ai l'impression que le système de notes est suffisant pour traiter les signalements contextuels et à localisation approximative. Ce qui ne veut pas dire qu'il n'y a pas à améliorer l'ergonomie de la création de ces notes :stuck_out_tongue:

**Comment by pyrog** [comment]
> L'interface serait également pensée pour permettre la création de signalements directement : les geeks qui font une veille sur le sujet précis pourraient créer des signalements contextuels.

En gros le système de notifications à la [OSMcha](https://osmcha.org/about#setting-up-rss-feed---area-of-interest)
On pourra aussi suggérer ça pour NotesReview ou développer un filtre sur le flux [RSS de l'API OSM](https://wiki.openstreetmap.org/wiki/API_v0.6#RSS_Feed:_GET_.2Fapi.2F0.6.2Fnotes.2Ffeed).

**Comment by overflorian** [comment]
OK je vois que vous êtes unanimes ;)
Essayons donc de creuser l'idée d'utiliser les notes quoi qu'il arrive.

Je vais prendre des exemples concrets basé sur nos personas https://github.com/vdct/ProjetDuMois/issues/66 pour voir où ça nous mène (sans prendre en compte à ce stade les problématiques liées au développement des outils) :

_1. Olivier prend une photo géolocalisée d'un DAE et laisse des indications très précises concernant la localisation, les horaires d'ouverture, le fait que le DAE soit fonctionnel et que le SAMU est appelé automatiquement lorsque la boite du DAE est ouverte.
Le compte @signalements_projetdumois sur twitter est un bot qui permet de créer des notes automatiquement à partir de tweets. Olivier mentionne ce compte en tweetant sa photo. La photo étant géolocalisée, une note est créée dans OSM._

_Par le passé, Florian a déclaré sur pdm.fr vouloir être averti si une note pdm était créée à moins de 40km de chez lui. Il reçoit alors une notif par mail : il clique et découvre la note d'Olivier : une interface affiche directement la photo avec le texte du tweet et la carte indiquant la position. Il remplit le formulaire très précis avec toutes les informations demandées. Un objet OSM est créé. Néanmoins, aucun champ dans le formulaire n'existe pour indiquer que "le SAMU est appelé automatiquement lorsque la boite du DAE est ouverte". Florian le mentionne en commentaire texte à la fin du formulaire : la note précédemment créé n'est pas fermée. Elle indique le commentaire textuel de Florian mais aussi le fait que l'objet a été créé dans OSM (avec l'URL). Un autre contributeur expert viendra compléter les données plus tard sans passer par le formulaire incomplet du site pdm.fr.
Florian a la possibilité de remercier Olivier en un clic qui envoie un tweet prérédigé (modifiable) depuis le compte @signalements_projetdumois._

_2. Ambroise est la mère d'Adrien. Elle a accepté de l'aider à identifier des DAE, à l'occasion. Adrien a déclaré le numéro de téléphone d'Ambroise dans le backoffice de pdm. Ambroise envoie un MMS au numéro de tel de pdm. Adrien reçoit alors une notif par mail pour traiter le signalement. Il se connecte sur pdm.fr : une notification lui indique qu'il a une tâche assignée en cours. Il l'affiche et découvre une photo d'un DAE sans aucune géoloc dans la photo. De ce fait, aucune note n'a été créée dans OSM pour l'instant. Un message indique "ce défibrillateur est à l'entrée de la piscine. Bisou mon loulou".
Adrien géolocalise la note de par ses connaissances terrain : il sait de quelle piscine parle Ambroise. La note est alors rendue publique. Adrien ou un autre contributeur peut alors traiter la note avec les indications données. Adrien a la possibilité d'envoyer un texto de remerciement en un clic à Ambroise._

Dans ce dernier exemple on voit qu'on est obligés de rajouter une étape intermédiaire de géolocalisation de signalements. Cela ne fonctionne, sauf exception, que si l'on met en place un système de parrainage. Sinon, on va être floodés par des signalements intraitables en l'état. Je pense.

**Comment by PanierAvide** [comment]
Indépendamment des canaux et de la tuyauterie à mettre en place, le concept de parrainage me paraît tout à fait opportun : ce sera plus facile de mobiliser des personnes non-expertes à participer. La qualité des données restera au rendez-vous grâce à la vérification / validation par un contributeur OSM.

**Comment by overflorian** [comment]
Je crois qu'on est tous d'accord ;)
Maintenant discutons des prios et de la mise en place pratique.
- Quelles modalités pour le programme de parrainage ?
- Comment gérer cette "étape intermédiaire" durant laquelle le parrain géolocalise un signalement contextuel ?
- Est-ce qu'on commence par Twitter, Instagram ou les SMS ? Ces derniers touchent plus notre cœur de cibles : les noobs.

  - Twitter : si j'ai bien compris, il y a déjà un bot qui existe et qui créé des notes quand on le mentionne @nlehuby ? Où peut-on trouver cette merveille et son code source associé ?

  - SMS : quel service choisir ? j'en ai trouvé plusieurs dont certains ont une API et un numéro virtuel cf. https://coachme.fr/logiciels-envoyer-sms
Les coûts sont très différents selon les fournisseurs. Par exemple https://www.smsmode.com a un abonnement de 9€HT/mois pour moins de 6300 SMS et a une option whatsapp (pour plus tard). Demander 200 balles de budget à l'asso pour faire une expé me paraît envisageable.

  - Instagram : je n'ai pas compris dans quelle mesure on peut récupérer une photo depuis la plateforme. @PanierAvide tu pourrais regarder si c'est possible stp ? https://www.instagram.com/developer/
Ce que j'ai compris c'est qu'il n'est pas possible d'afficher des photos à l'extérieur de la plateforme : les posts embeddés sur des pages web sont de simples liens qui renvoient vers l'intérieur de la plateforme. Au moins, chaque post a un URL unique auquel on peut accéder, c'est déjà ça.

**Comment by PanierAvide** [comment]
Retour du persona des mamans :
- Contribution peu importe le canal (SMS, site web, Facebook), tant que le destinataire est le parrain ou une personne en laquelle le parrain a confiance
- Envie d'un retour suite à la contribution (le DAE était déjà renseigné, il n'y était pas, peux-tu me donner plus d'infos...)
- On doit pouvoir envoyer uniquement du texte, dans certains cas la prise de photos n'est pas possible (DAE face au comptoir d'une salle d'embarquement)
- Mais quand on peut envoyer la photo, idéalement celle-ci doit être visible dans les données au final

Retour du persona _ma conjointe_ :
- Pas sur les réseaux sociaux, et n'aurait pas confiance en l'utilisation d'un service SMS (on sait pas qui voit le numéro de téléphone, même si c'est parrainé)
- C'est aussi bien si c'est sur un site web, où on peut ne mettre que le texte et/ou la photo. Le mécanisme de parrain semble superflu.

Je pose ça là, je ne sais pas ce que on peut en déduire en terme de façon d'aborder le service :stuck_out_tongue:

**Comment by overflorian** [comment]
Moi j'en déduis qu'on a des utilisateurs hétéroclites et qu'on ne peut pas tous les toucher que via des canaux différents. Et donc il faut qu'on priorise. J'aime bien le persona _ta conjointe_ qui dit qu'un site web ça peut faire le taff. Ça, on sait faire.
Ça me laisse à penser qu'on pourrait créer une landing page dédiée aux noobs (la home de pdm.fr ?) qui soit dédiée à la création de note.

Pré-maquette d'une telle page :
- Titre : Projet du mois : trouvez un max de défibrillateurs !
- CTA : gros bouton APPAREIL PHOTO, wording : "j'en ai un !"
les gens envoient une photo
- Champs texte : "préciser où vous avez vu ce DAE / donnez plus d'info"
- Mini-map avec demande de géoloc de l'utilisateur pour indiquer la position de l'objet (optionnel)

Après validation, possibilité de renseigner son email pour qu'un contributeur donne une confirmation de création + remerciement
Opt-in pour abonnement à la newsletter spéciale NOOBS.
Des beaux visuels genre ambiance jeu un peu partout.

**Comment by PanierAvide** [comment]
Ça me plaît bien ça :smile:  Et niveau données si on prévoit une base assez souple on pourra venir alimenter par la suite avec d'autres sources type compte Twitter/FB/...

Et via cette page, comment se fait le lien avec un parrain ? Champ optionnel de recherche par pseudo ? Une URL que le parrain envoie qui contient un paramètre pour faire le lien automatiquement ? Ou rien de tout ça pour l'instant ?

**Comment by pyrog** [comment]
> Projet du mois : trouvez un max de défibrillateurs !
> j'en ai un !

Ça me plait moins : est-ce qu'on cherche à faire un jeu vidéos pour ados ou à faire de la cartographie de qualité ?

**Comment by PanierAvide** [comment]
L'un n'empêche pas l'autre ? J'ai commencé à contribuer à OSM quand j'étais lycéen, l'enseignement en 2nde propose d'aborder OSM, et des cartoparties ont été organisées avec des enfants par des enseignants au primaire pour les initier à la géographie... Le fait de rendre ludique une contribution n'en réduit pas automatiquement sa qualité :wink:

**Comment by overflorian** [comment]
@pyrog je comprend les raisons de ta remarque. Néanmoins garde en tête les personas : nous essayons d'aller sur le terrain des personnes qui ne sont pas contributeurs OSM, qui n'ont pas de compte OSM. Les ados ne sont pas (à ce stade) notre cœur de cible. La gamification est juste un outil pour amener plus de contributions, pas un artifice inutile.

@PanierAvide en effet, on pourra envisager de brancher l'outil par la suite sur Twitter/Facebook/SMS.

`Et via cette page, comment se fait le lien avec un parrain ? Champ optionnel de recherche par pseudo ? Une URL que le parrain envoie qui contient un paramètre pour faire le lien automatiquement ? Ou rien de tout ça pour l'instant ?`
Bonne idée oui. Je vois bien les 2 systèmes en parallèle.
Les pseudos OSM étant sensibles à la casse, il faut obligatoirement un système d'auto-complétion efficace. Celui-ci peut être limité aux contributeurs ayant eu des points PdM si c'est plus simple techniquement. Dans l'idée il faut que le parrain déclare son intérêt explicite d'être parrain.
On peut aussi imaginer qu'il soit possible de créer de nouveaux pseudos. ça nous permettrait de faire des landing pages du type https://projetdumois.fr/florian qui est plus humain que /overflorian

Pour le MVP, le système de parrainage n'est pas nécessaire. On se garde ça pour la V1.

En fait plus j'y pense et plus on devrait faire un outil dédié avec une URL noob-compatible.
Mes idées :

Nom de domaine | .fr dispo | .com dispo | Commentaire
-- | -- | -- | --
mieuxafaire | oui | oui | Par ce qu’on n’a pas « mieux à faire » dans notre vie que de contribuer à OSM ;)
maiscestou | oui | oui | Le parrain demande au filleul : « mais c’est où ? »
letrucestla | oui | oui | Le filleul dit au parrain « le truc est là »
tiensmaphoto | oui | oui | Le filleul dit au parrain « tiens, ma photo »

à creuser un soir avec de la vodka ...

J'imagine une partie backoffice pour le parrain : il configure ce qu'il demande à chercher à ses filleuls : "trouve-moi tous les DAE"
Le filleul accéde à https://letrucestla.com/florian et la landing page indique : Florian cherche des défibrillateurs / [PHOTO DU PARRAIN] / [PHOTO(S) ILLUSTRATIVE DE L'OBJET] / Formulaire
Il reste encore à définir comment ce système se goupille plus précisément avec pdm.fr

**Comment by overflorian** [comment]
(ça faisait VRAIMENT longtemps qu'on n'avait pas ouvert un nom de domaine :D :D :D :D)

**Comment by pyrog** [comment]
Je connais la "gamification" et son intérêt depuis longtemps 😃 
C'est la formulation qu'il faut revoir selon moi.

@overflorian CTA ? (j'ai déjà oublié ce que ça veut dire), MVP ??

**Parrainage**
Keep it simple 😉 
Il semble utile pour l'envoi de photos par SMS. C'est le parrain qui fournit le n° de téléphone à son filleul.

**Comment by PanierAvide** [comment]
CTA -> call to action, le bouton principal sur lequel on devrait cliquer
MVP -> minimum viable product, produit minimun viable, en gros le proto qui fait le boulot minimal

**Comment by overflorian** [comment]
` C'est la formulation qu'il faut revoir selon moi.`
OK. Peux-tu stp détailler ton idée ?

**Comment by overflorian** [comment]
Le nom de domaine tuveuxmaphoto.fr est dispo :smile:
TU VEUX MA PHOTO ?!

**Comment by PanierAvide** [comment]
Simple à retenir, pas d’ambiguïté sur l'écriture... on aime :smile:

**Comment by pyrog** [comment]
> trouvez un max de défibrillateurs !

Je comprends qu'il faut faire du chiffre 😔

> j'en ai un !

PdM devient Pokemon Go ??

Désolé, je doit être dans la case vieux con 😁

**Comment by overflorian** [comment]
Cette idée a abouti à https://github.com/vdct/ProjetDuMois/issues/81
