### ISSUE TITLE
Notes créées par MapsMe pas remontées

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#75]
Elles sont créées avec les mots clés **POI types: emergency-defibrillator**.
[NotesReview](https://ent8r.github.io/NotesReview/expert/?query=POI%20types%3A%20emergency-defibrillator&limit=1000&closed=true)

**Comment by pyrog** [comment]
Le mot clé [AED](https://ent8r.github.io/NotesReview/expert/?query=AED&limit=1000&closed=true) est souvent utilisé (à l'étranger).
Il est utilisé aussi par [StreetComplete](https://ent8r.github.io/NotesReview/expert/?query=AED%20StreetComplete&limit=1000&closed=true).

**Comment by PanierAvide** [comment]
C'est ajouté
