### ISSUE TITLE
Créer un outil d'envoi de signalements dédié aux filleuls

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#77]
Mes mockups :

![05-10-2020-14.51.46.jpg](https://user-images.githubusercontent.com/11553211/95081966-a1cc5880-071a-11eb-8305-1c4dc372f026.jpg)

![05-10-2020-14.52.21.jpg](https://user-images.githubusercontent.com/11553211/95081995-aee94780-071a-11eb-93dd-330c607dd60e.jpg)

![05-10-2020-14.50.13.jpg](https://user-images.githubusercontent.com/11553211/95082007-b3adfb80-071a-11eb-88c9-766438d32cfc.jpg)

![05-10-2020-14.52.53.jpg](https://user-images.githubusercontent.com/11553211/95082013-b6a8ec00-071a-11eb-9971-36b84421d98b.jpg)

**Comment by overflorian** [comment]
Essayons d'être neutre terme de singulier/pluriel dans la phrase d'intro : "Salut Magali, Florian demande de l'aide pour trouver des défibrillateurs."

**Comment by overflorian** [comment]
Dans le MVP, on demande au parrain son prénom + le prénom du filleul.
Il envoie l'URL qui respecte la structure https://url.fr/{numéro de relation parrain-filleul}/prénom-du-filleul
La phrase de bienvenue personnalisée s'affiche.

**Comment by pyrog** [comment]
`https://url.fr/{numéro de relation parrain-filleul}/prénom-du-filleul`

Je mettrais plutôt un hash pour éviter les "contournements"

**Comment by overflorian** [comment]
le bouton SUIVANT s'appelle PASSER tant qu'aucune photo n'est envoyée.
Bien préciser au parrain que la recherche d'objet change en fonction du pdm.
A la seconde étape, dans l'idéal, le texte exemple s'affiche en gris, le champ est ouvert avec le clavier, l'exemple en gris disparaît dès que l'on commence à tapper. Si l'on supprime tout le texte, l'exemple en gris réapparaît.

Après "Où est ce défibrillateur ?", ajouter une barre de recherche. Plus tard, il sera possible de maximiser la carte et d'avoir le choix de l'imagerie.
