### ISSUE TITLE
Créer un gestionnaire de notes

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#82]
Sur une suggestion de @nlehuby, on pourrait intégrer un système de gestion des notes liées au projet du mois en cours.
Il s'agit donc d'intégrer le mode expert de Notes Review https://ent8r.github.io/NotesReview/expert/

A terme le gestionnaire pourrait intégrer en plus des notes 1. les signalements issus de tuveuxmaphoto.fr 2. les signalements OSMOSE.

Fonctionnalités clef :
- notes filtrables (filtres à définir)
- on peut répondre direct aux notes (qui sont donc des fils de discussion à part entière)
- on peut rajouter des hashtags aux notes : par exemple #NécessiteUneVérifTerrain pourrait être ajouté en réponse dans une note, ce qui serait interprété par l'outil comme un type de note, potentiellement filtrable
- les URLs des photos dans les notes sont transformées directement en photo (et il faut que ça fonctionne pour mapillary, les URLs de photo direct et les autres services d'hébergement des photos)

**Comment by overflorian** [comment]
Les notes pourraient être triées de deux manières avec un bouton de filtre pour passer de l'un à l'autre (labels de ce bouton : PROXIMITÉ / IMPORTANCE), comme sur l'interface de filtre de l'appli Google Maps :
<img width="50%" src="https://user-images.githubusercontent.com/11553211/95501848-35b35400-09a9-11eb-8d07-449a0590cd1c.png">

On peut imaginer que ce filtre est activé par défaut :
- par proximité sur mobile
- par importance sur desktop

**Comment by overflorian** [comment]
Pour l'affichage du menu, il y plusieurs solutions :
1. des onglets classiques, comme sur l'exemple :
<img width="50%" src="https://user-images.githubusercontent.com/11553211/95499981-634ace00-09a6-11eb-9426-765f90c9dd93.png">

ça donne un truc comme ça sur desktop :
<img width="90%" src="https://user-images.githubusercontent.com/11553211/95500973-ef112a00-09a7-11eb-96ff-c47e5e665654.png">

Icônes utilisées :
- carte https://thenounproject.com/search/?q=map&i=3539543
- liste https://thenounproject.com/search/?q=list&i=3039533

Variante : le [menu de navigation en bas de l'écran](https://material.io/components/bottom-navigation#anatomy).
Je suis pas hyper convaincu.

2. Une [sticky bar en bas d'écran](https://material.io/components/sheets-bottom#behavior) qui apparaît par défaut recouvrant 20% de l'écran, maximisable au scroll.

Efficace sur mobile, beaucoup moins sur desktop. Or l'usage sur desktop est prédominant pour cette fonctionnalité donc je suis pas non plus convaincu.

3. Un bouton de filtre pour passer de l'un à l'autre, positionné dans le menu :
<img width="50%" src="https://user-images.githubusercontent.com/11553211/95503503-c1c67b00-09ab-11eb-8549-dc476d4299a1.png">
Ce menu est déjà affiché par défaut sur desktop mais pas sur mobile, ce qui est parfait.
C'est mon option préférée.

**Comment by overflorian** [comment]
La couleur de l'interface (top bar + barre du menu) pourrait changer selon le mode actif (Carte / Liste) pour bien marquer la différence. Ou pas.

**Comment by overflorian** [comment]
La disposition actuelles des notes dans NotesReview créé des blocs de hauteur homogène, qui est la disposition n°1 [(telle que définie par le material design)](https://material.io/components/image-lists#usage) :
![image](https://user-images.githubusercontent.com/11553211/95556027-ef92da80-0a12-11eb-94b8-c7dc1e454f9f.png)
Vu qu'on a des notes avec ou sans photo et que leur longueur est variable, je pense qu'on devrait plutôt opter pour la disposition n°4.

Le scroll infini sans avoir à cliquer sur un bouton me paraît une bonne idée. Etant donné qu'on est sur un projet du mois avec un nombre limité de notes, on peut charger la totalité des notes.
Par la suite, si on ajoute plus d'éléments (notamment issus d'osmose), on pourra limiter le chargement à quelques dizaines de notes, puis au scroll, charger automatiquement la suite.

Par ailleurs, NotesReview n'affiche que 3 colonne sur grand écran (le mien a une résolution de 1920x1080). Je crois qu'on peut en mettre au moins 4 sur un écran aussi large.

**Comment by overflorian** [comment]
Il faut une 404 : aucune note existante.

Je propose une belle photo avec la mention "On n'a rien pour vous pour l'instant. Repassez plus tard."
https://www.flickr.com/photos/francoispacaud/49963711171/in/photolist-2j885C4-2itPP7X-6dgnF-oqxEDQ-PkbTgL-wthVwj-9B4xxz-5wUsYz-k59d-q8vh-k5bx-2hhkjDA-23oqL-qYYnLh-23osj-23oua-bB4c-23ovD-bB5N-bB5d-bB4F-TYB8PA-29PEnFS-ryeTKD-LM9ni7-cMF5-rtVJ-2jmFGff-Kwap-rtUG-Kw8c-25DUvgq-nxnW7P-Kw76ic-2jovQVL-2i5wLhf-k5ESH5-29y6oeR-bd2neH-Kw9f-zwNcxA-q8wV-q8uD-4nCHzc-9Z9ngG-dkgA2-a6zCEc-2gMmy6F-chjLQU-Th64cF
Ne pas oublier de créditer l'auteur (licence CC BY-NC-ND)

**Comment by overflorian** [comment]
On n'en a pas parlé mais j'ai l'impression qu'on peut garder le CTA principal même sur la page des notes : le bouton (+) qui permet de créer une note. S'il est par dessus des notes existantes, je pense que c'est très bien comme ça.

**Comment by overflorian** [comment]
Sinon pour la 404 on peut aussi mettre un gif bien con ^^
https://giphy.com/gifs/nasa-nasareactions-Z9hZLKflOlXjo349De
https://giphy.com/gifs/sad-depressed-disappointed-33iqmp5ATXT5m
https://giphy.com/gifs/blackish-anthony-anderson-dre-johnson-d2lcHJTG5Tscg
https://giphy.com/gifs/sad-baby-upset-9Y5BbDSkSTiY8

**Comment by PanierAvide** [comment]
Une première version est à tester ici : https://projetdumois.fr/projects/2020-09_aed/issues

À noter que :
* L'accès depuis la carte n'est pas encore activé, ce le sera quand la page sera satisfaisante.
* Le bouton éditer renvoie vers la carte mais n'ouvre pas encore la note associée ou l'objet à éditer, ce sera fait sous peu
* Que si un objet dispose de plusieurs photos, ce sera probablement affiché sous la forme d'une galerie au niveau de la note

Preneur de retours au-delà de ces points là :wink:

**Comment by pyrog** [comment]
Pourquoi réinventer la roue ? 😉 
Je trouve que NoteReview est très lisible, facile d'utilisation 😃

**Comment by PanierAvide** [comment]
Parce qu'à terme on va aussi afficher dans cette page les signalements de tuveuxmaphoto.fr et les remontées Osmose (si ça s'y prête). Et aussi qu'on a plus facilement le lien avec l'éditeur intégré, et que ça filtre automatiquement sur les notes du projet du mois.

**Comment by pyrog** [comment]
L'alignement vertical des boites augment la lisibilité:
<img width="400px" alt="NotesReview" src="https://user-images.githubusercontent.com/2158081/95684445-2410bd00-0bf2-11eb-8a49-c203b61552fb.png"> <img width="400px" alt="PdM" src="https://user-images.githubusercontent.com/2158081/95684441-2115cc80-0bf2-11eb-8f82-2fba13f8cfae.png">

**Comment by pyrog** [comment]
> Parce qu'à terme on va aussi afficher dans cette page les signalements de tuveuxmaphoto.fr 

ça peut se faire aussi sous forme de notes (le stockage de photo de StreetComplete est disponible aussi pour PdM 😉 )

> et que ça filtre automatiquement sur les notes du projet du mois.

Ce [lien](https://ent8r.github.io/NotesReview/expert/?query=projetdumois) aussi 😜

**Comment by PanierAvide** [comment]
> ça peut se faire aussi sous forme de notes (le stockage de photo de StreetComplete est disponible aussi pour PdM wink )
Sauf si les signalements n'ont pas de géolocalisation. Ou que l'utilisateur de tuveuxmaphoto envoie une photo qui n'est pas à partager publiquement (uniquement à destination du contributeur OSM car on y voit des visages, des plaques d'immatriculation...).

**Comment by pyrog** [comment]
> Sauf si les signalements n'ont pas de géolocalisation.

Une ville c'est bien, à défaut la France.

> on y voit des visages, des plaques d'immatriculation…

Ce sont des notes avec des photos temporaires.
On pourrait imaginer autoriser l'accès aux photos uniquement aux contributeurs OSM.

**Comment by pyrog** [comment]
La barre latérale avec les filtres mange trop d'espace.
Une barre verticale serait plus économe, d'autant plus si elle disparait au défilement de l'écran.

**Comment by PanierAvide** [comment]
On peut la cacher la barre latérale, sur le même mode de fonctionnement que celle de la carte.

**Comment by pyrog** [comment]
**Ne pas réinventer la roue : bis.**

Le filtre par nom d'utilisateur manque.

Le titre de la note prends trop de place :
<img width="420" alt="NotesReview" src="https://user-images.githubusercontent.com/2158081/95685039-bebecb00-0bf5-11eb-954b-1a53129c83f1.png"> <img width="311" alt="PdM" src="https://user-images.githubusercontent.com/2158081/95685038-be263480-0bf5-11eb-840b-b6639472be9e.png">

Une note ne peut pas  être éditée :
<img width="425" alt="PdM" src="https://user-images.githubusercontent.com/2158081/95685016-9c2cb200-0bf5-11eb-82aa-9d94055f001e.png"> <img width="322" alt="NotesReview" src="https://user-images.githubusercontent.com/2158081/95685017-9cc54880-0bf5-11eb-88e1-c729e24a30c3.png">

**Comment by overflorian** [comment]
Je trouve que 4 colonnes c'est bien avec un grand écran. Lorsque l'écran devient plus petit, j'ai l'impression qu'on peut le faire disparaître s'il atteint 280px ou moins.

**Comment by overflorian** [comment]
La place que prend la barre latérale ne me choque pas. Mais si on n'y affiche que des filtres, ça peut valoir le coup de les mettre en haut, question d'ergonomie; je pense qu'on pourra voir un peu plus tard ce point précis.

**Comment by PanierAvide** [comment]
Le nombre de colonne se change uniquement en cas de rechargement de la page. Actuellement c'est :
* + de 1200px : 4 colonnes
* 992-1200px : 3 colonnes
* 768-992px : 2 colonnes
* Moins de 768 px : 1 colonne

**Comment by overflorian** [comment]
OK, ça va. J'avais testé de redimensionner la page pour voir si elle était full responsive, d'où mon retour. Mais ta solution convient bien également.

**Comment by PanierAvide** [comment]
En fait c'est géré comme ça pour avoir un affichage sur une logique ligne à ligne (et pas colonne par colonne, qui permettrait d'être full responsive), car ça me semble plus sensé d'avoir une progression des dates sur une logique de pseudo lignes que de colonnes.

**Comment by overflorian** [comment]
très bonne idée

**Comment by overflorian** [comment]
OK j'ai un peu joué avec les [cards](https://material.io/components/cards#anatomy) et voici ma proposition :
<img width="80%" src="https://user-images.githubusercontent.com/11553211/95761863-369bfc80-0cad-11eb-8de0-5c7450212a34.png">

0. Les cards en elles-mêmes ont une ombre légère
1. Un bouton permet d'afficher le feed de commentaires : la card s'expand vers le bas pour afficher les réponses
2. L'icône du contributeur s'affiche (mais pas son pseudo). Elle est cliquable et permet de ne filtrer que les notes de ce contributeur en particulier.
3. Le titre est la ville où est situé la note. Non cliquable. (à priori, cela nécessite un retraitement).
4. Le sous-titre est la date de création de la note, format "lisible par un humain" ;) Cliquer renvoi vers la note sur osm.org
5. La carte centrée sur la note s'affiche. Elle n'est ni cliquable ni scollable. Ça pourrait très bien être une photo bitmap.
A vrai dire, je suis à moitié convaincu par cette carte. A voir si c'est vraiment utile.
S'il y a une ou plusieurs photo(s), elle(s) s'affiche(nt) à la place de la carte. On peut scroller vers la droite pour faire défiler les photos :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95757172-18330280-0ca7-11eb-88a7-ac0fca981b36.png">

6. Les #hashtags utilisés dans les notes sont transformés en filtres cliquables directement dans le texte. De nouveaux sont ajoutés (comme par exemple "Prêt à intégrer")
Si ça se trouve, on a envie de laisser à l'utilisateur la possibilité de créer de nouveaux tags (de la même manière que les "Labels" dans une issue Github) : chaque nouveau tag serait tout simplement rajouté dans une note en réponse
La couleur secondaire est utilisée pour les tags extraits de la note, la variante sombre pour le hashtag du projet du mois en cours, la variante claire pour les autres tags
7. Le hashtags disparaissent du texte pour devenir des boutons de filtres. A terme, les tags structurés devraient également être affichés de manière différenciée
8. Le CTA principal est "éditer" : on peut soit cliquer direct et ça ouvre l'éditeur intégré, soit cliquer sur le petit triangle qui permet d'ouvrir avec l'éditeur de son choix. L'éditeur par défaut qui s'ouvre en cliquant sur "éditer" est toujours le dernier ouvert (il faut donc enregistrer ce paramètre).
9. Il est possible de répondre à la note. Ce bouton ouvre directement un champ de réponse qui apparaît en dessous de la card en ouvrant le clavier sur mobile.

Seul problème de ma proposition : sur mobile je pense que ça prendra une place verticale beaucoup trop importante. On pourra virer des trucs superflus à l'occaz' si besoin.

**Comment by PanierAvide** [comment]
Ça rend top comme ça :smile: 

Juste pour le 3, ça va nous apporter une complication technique pour une valeur ajoutée faible ? On y mettrait pas plutôt le nom du contributeur ?

Et pour le 5 la carte c'est _design_ mais ça risque d'être lourd à charger. À moins de se lancer dans un système qui charge la carte seulement si elle est visible à l'écran... Pas le plus simple.

**Comment by overflorian** [comment]
Ouais je m'attendais à un retour sur ces deux points lol. La différence entre le moment où tu design un beau truc et où il doit être implémenté.
J'avoue que :
3. le titre ça va être galère. Le nom du contributeur ne me paraît pas assez important pour mériter d'être un titre. Peut-être n'a-t-on tout simplement pas besoin de titre ?
5. ok sacrifions la carte (mais pas le système de défilement entre plusieurs photos qui est beaucoup trop stylé et qui sera surtout très utile pour _tuveuxmaphoto_

**Comment by PanierAvide** [comment]
Le titre pourrait être la nature du signalement : via tuveuxmaphoto, note OSM, Osmose...

OK pour le défilement photo.

**Comment by overflorian** [comment]
OK, essayons la nature du signalement pour voir ce que ça donne

**Comment by PanierAvide** [comment]
Les points 0 à 7 de ta proposition ont été traités, il reste encore des choses à implémenter. Toujours à tester ici https://projetdumois.fr/projects/2020-09_aed/issues

**Comment by overflorian** [comment]
Je crois que les points 2 et 7 ne sont pas encore intégrés.
Néanmoins ce sont des détails, je pense que l'outil est assez mature pour être passé en production dès à présent.

**Comment by PanierAvide** [comment]
Le point 2 c'est vrai j'ai zappé le côté filtre :sweat_smile:  Et le 7 est implémenté comme suit :
- Les hashtags dans le texte de la note sont retirés
- Tous les hashtags hormis ceux par défaut (projetdumois, projetdumoisfr, deficoeur) sont affichés sous forme d'un "badge" entre le texte de la note et le bouton éditer
- Ces hashtags sont aussi rendus visibles dans la barre de filtre du panneau de gauche

**Comment by overflorian** [comment]
OK niquel. Je te laisse mettre tout ça en prod et faire cocorico sur talk-fr ?

**Comment by pyrog** [comment]
Ce gestionnaire progresse 😃 

* Le libellé bmange de la place.
J'imagine que plus tard on pourra trouver des "Tu veux ma photo", des Tweet…
Mettre une petite icône en haut  ou un badge "source" en bas peu les différencier 😉 

* **4 colonnes** avec le volet de gauche ouvert c'est trop étroit.
Volet fermé, ça va mais à voir ce que ça donne avec des photos.

* Le **nom** de l'auteur de la note **n'est pas cliquable**.

* Ça **manque de couleur** (j'aime bien les petites boites : elles permettent de se repérer facilement)
<img width="33%" alt="Notes Review" src="https://user-images.githubusercontent.com/2158081/96741723-6a200a80-13c2-11eb-8b7f-656ad20812f8.png">

* Le bouton ~~**éditer**~~ commenter **est trop gros**
<img width="40%" alt="PdM" valign=top src="https://user-images.githubusercontent.com/2158081/96742749-8a9c9480-13c3-11eb-89e4-c43473b568d5.png"> <img width="40%" alt="PdM" valign=top src="https://user-images.githubusercontent.com/2158081/96742741-88d2d100-13c3-11eb-93fe-c254d59c7c9a.png">

* Le non **alignement vertical des boites** rend la lecture difficile
<img width="40%" alt="Notes Review" valign=top src="https://user-images.githubusercontent.com/2158081/96743277-1adad980-13c4-11eb-8587-429b325d063e.png"> <img width="40%" alt="Notes Review" valign=top src="https://user-images.githubusercontent.com/2158081/96743291-1e6e6080-13c4-11eb-9945-b043ceb99963.png">

**Comment by pyrog** [comment]
**Commentaires**

* L'affichage en dessous n'est pas très intuitif par rapport à la boite de NotesReview qui surgit.
* Le libellé Commentaire par inutile
* Les libellés Fermé par, Ouvert par sont trop verbeux

<img width="33%" valign=top alt="PdM" src="https://user-images.githubusercontent.com/2158081/96744444-55914180-13c5-11eb-8e34-f728ee6abb9c.png">  <img width="50%" valign=top  alt="Notes Review" src="https://user-images.githubusercontent.com/2158081/96744930-d6503d80-13c5-11eb-800f-313ae81b07cf.png">

**Comment by PanierAvide** [comment]
Je viens de pousser (toujours en test) les modifications suivantes :
- Le clic sur éditer ouvre automatiquement la note dans la carte
- Le nom d'utilisateur est cliquable et renvoie vers osm.org

Pour l'alignement vertical (espace vertical entre notes pour avoir des lignes cohérentes comme NoteReview) proposé par @pyrog, je veux bien ton avis @overflorian.

Pour l'affichage des commentaires en bas de note, ça ne me choque pas ainsi, pareil preneur d'un autre point de vue.

Pour les libellés "ouvert/fermé/commentaire par" ça reprend le vocabulaire d'osm.org, l'omettre risque de porter à confusion.

Pas de mise en prod pour l'instant, j'attends qu'on règle ces points d'ergonomie :wink:

**Comment by overflorian** [comment]
Je pense que l'on pinaille, on devrait mettre en prod dès maintenant.

- je suis d'accord avec @pyrog : les boutons "éditer" sont trop gros
- "L'affichage en dessous VS boite qui surgit"
Les 2 approches se discutent. Honnêtement j'aime bien les 2 et je trouve qu'elles ont chacune des avantages et des défauts.
Si on part sur une boite qui surgit, est ce que tu penses que cela réglerait aussi le fait que 4 colonnes ne permet pas de bien voir les photos @pyrog ? On peut aussi imaginer que la photo s'ouvre en grand quand on clique dessus, tout simplement.
- concernant l'alignement, je reste sur l'idée que la disposition actuelle est efficace et bien lisible. Et surtout, je pense que l'on créerait de gros trous dans les cas où une note serait très grande à côté de notes toutes petites. @PanierAvide à toi donc de trancher entre mon avis et celui de @pyrog 
- Pour les libellés "ouvert/fermé/commentaire par" je suis aussi d'avis de garder le même wording sur sur osm.org
- Si je voulais pinailler encore plus, je parlerai d'une meilleur manière de filtrer que des check-box, mais ça ne vaut peut-être pas le coup d'y passer trop de temps en s'inspirant de [nos réflexions antérieures](https://github.com/osmontrouge/caresteouvert/issues/225), n'est-ce pas ? ;)
Ma suggestion en passant : ne plus jamais utiliser de checkbox de notre vie, toujours utiliser un slider à la place.

**Comment by pyrog** [comment]
**Photos**

* La vignette n'est pas (encore ?) générée.
* Son format ne respecte pas celui de l'image.
* Les autres photos ne sont pas affichées

<img width="33%" valign=top alt="PdM" src="https://user-images.githubusercontent.com/2158081/96746801-d9e4c400-13c7-11eb-9e70-a7b255618bbf.png"> <img width="33%" valign=top alt="Notes Review" src="https://user-images.githubusercontent.com/2158081/96746811-dbae8780-13c7-11eb-8454-cbe901bceb60.png">

**Mots-dièse**

* Ceux qui font partie d'une phrase "disparaissent", la rendant incompréhensible.
`Note de test avec #photos et hashtags #DAE ` devient `Note de test avec et hashtags`
* Ils ne sont pas cliquable. Cela permettrait de filtrer (aussi) la liste de manière intuitive.
* Leur affichage dans le panneau de gauche n'est pas homogène
Je propose de les afficher sous forme de badge, sans # et classé par ordre alphabétique.
Un clique fait par exemple, changer leur couleur pour indiquer qu'il sont actif ou non.

<img width="33%" valign=top alt="Filtre avec badge" src="https://user-images.githubusercontent.com/2158081/96748673-24ffd680-13ca-11eb-9fbb-de0112a5af9b.png"> <img width="33%" valign=top alt="Filtre avec case à cocher" src="https://user-images.githubusercontent.com/2158081/96748662-2204e600-13ca-11eb-8dd1-45373767f1bc.png">

**Comment by overflorian** [comment]
PS : pour moi, le comportement attendu de cliquer sur le nom d'un utilisateur est de filtrer toutes les notes qu'il a créé, et pourquoi pas celles sur lesquelles il a répondu

**Comment by overflorian** [comment]
` Je propose de les afficher sous forme de badge, sans # et classé par ordre alphabétique.`
J'aime. Avec un séparateur au dessus

**Comment by pyrog** [comment]
> Ma suggestion en passant : ne plus jamais utiliser de checkbox […]utiliser un slider à la place.

👍 pour rester cohérent avec le filtrage des couches

**Comment by overflorian** [comment]
quand aux autres filtres, on peut leur mettre des icônes :
- Prêt à intégrer https://thenounproject.com/search/?q=check&i=1820655
- Avec photo https://thenounproject.com/search/?q=photo&i=2067906
- Anonymes https://thenounproject.com/search/?q=anonymous&i=1781608

**Comment by pyrog** [comment]
> Pour les libellés "ouvert/fermé/commentaire par" je suis aussi d'avis de garder le même wording sur sur osm.org

NoteReview le garde, mais comme c'est affiché dans une boite qui occupe presque tout l'écran, il y a de la place.
De plus c'est dans un badge coloré 😃 

Et ce que je trouve long c'est "… **par**" 😉

**Comment by pyrog** [comment]
> pour moi, le comportement attendu de cliquer sur le nom d'un utilisateur est de filtrer toutes les notes qu'il a créé…

👍

**Comment by pyrog** [comment]
Que signifie exactement **Prêt à intégrer** ?

**Comment by overflorian** [comment]
`Que signifie exactement Prêt à intégrer ?`
Si même toi, tu te poses la question, c'est que ce n'est pas clair et que nous devrions trouver un meilleur terme.
Cela signifie que la note a été créée sur pdm.fr et qu'en conséquence on a la bonne géoloc et les méta-données pour pré-remplir le formulaire qui ne demande qu'à être validé par l'utilisateur.
Quel terme utiliser pour cela ? "prêt à intégrer" me paraissait clair jusqu'à présent.

PS : après avoir cliqué sur "éditer" sur une note, quand la carte s'ouvre elle se recentre sur la position du GPS de l'utilisateur. 
Attendu : la carte reste centrée sur un POI lorsqu'il est en cours d'édition / création

**Comment by pyrog** [comment]
J'ai enfin compris la signification du bouton **Editer** que je voulais renommer en **Commenter**  🤣

**Editer** c'est pour ajouter un POI sur la carte à partir d'une note.
**Commenter**, c'est pour commenter une note.
PdM devrait permettre les deux, ou a défaut utiliser un terme plus parlant.
Pourquoi pas reprendre le bouton ⊕ de la carte ?

Il risque d'y avoir une confusion, en particulier pour les habitués des notes OSM, de Notes Review…
Mais aussi pour les débutants qui seront bientôt de futur utilisateurs des autres outils OSM 😉

**Comment by PanierAvide** [comment]
Pour les photos, c'est normal qu'elles ne s'affichent pas, ce ne sont pas les liens directs vers les fichiers images...
https://commons.wikimedia.org/wiki/File:DAE_Megarama_Lons_02.jpg -> https://upload.wikimedia.org/wikipedia/commons/1/1c/DAE_Megarama_Lons_02.jpg

**Comment by PanierAvide** [comment]
Mais bon j'imagine qu'il faut ajouter le bout de code pour deviner l'URL de la photo si c'est une image qui vient de Commons.

**Comment by pyrog** [comment]
> Pour les photos, c'est normal qu'elles ne s'affichent pas...

Et comment font les autres applications OSM ?
… dont Notes Review 😉 

Cf. [note de test](https://ent8r.github.io/NotesReview/expert/).

**Comment by PanierAvide** [comment]
Elles sont obligées de gérer un cas particulier avec du code spécifique :sweat:

**Comment by PanierAvide** [comment]
Il est même ici le code spécifique pour gérer ça https://github.com/ENT8R/NotesReview/blob/ef416315669d5aa7b6ed85816184cb61612ad654/js/linkify.js

**Comment by pyrog** [comment]
J'ai ouvert un [ticket](https://github.com/ENT8R/NotesReview/issues/63) pour qu'il affiche aussi les photos **Mapillary**.

**Comment by overflorian** [comment]
C'est cool @PanierAvide tu fais la discussion tout seul : tu poses le problème et trouves la solution; il ne manque plus que l'implémentation :D

**Comment by pyrog** [comment]
> pour moi, le comportement attendu de cliquer sur le nom d'un utilisateur est de filtrer toutes les notes qu'il a créé…

Je reviens sur ma position : survoler et cliquer sur le nom permet de savoir à qui on a affaire.
Le filtre par utilisateur peut se faire en mettant un champ dédié (cf. Notes Review)

**Comment by pyrog** [comment]
**Passage de la carte à la liste de notes ?**

Notes Review propose un bouton **Afficher la…** toujours visible.

<img width="33%" alt="Afficher la liste" src="https://user-images.githubusercontent.com/2158081/96756603-96dd1d80-13d4-11eb-8355-1cfc72dbee03.png"> <img width="33%" alt="Afficher la carte" src="https://user-images.githubusercontent.com/2158081/96756605-980e4a80-13d4-11eb-9dfb-b18e0e2b580e.png">


Je propose de reprendre le concept. Mais dans PdM, la liste sera établie en fonction des couches visibles.
- POIs à intégrer
- POIs à compléter
- Notes
- Lieux disposant potentiellement d'un POI

**Comment by overflorian** [comment]
Je ne suis pas certain de comprendre ta proposition @pyrog. Peux-tu stp la détailler ?

**Comment by PanierAvide** [comment]
@pyrog mais en fait le bouton sera le même que sur la liste des notes, c'est juste qu'il est caché pour l'instant vu que la fonctionnalité n'est pas rendue publique à cause des ajustements à réaliser...

**Comment by pyrog** [comment]
> J'ai ouvert un [ticket](https://github.com/ENT8R/NotesReview/issues/63) pour qu'il affiche aussi les photos **Mapillary**.

linkify.js affiche désormais les photos Mapillary 😃

**Comment by pyrog** [comment]
> Je ne suis pas certain de comprendre ta proposition @pyrog. Peux-tu stp la détailler ?

PdM va afficher une liste de notes quelque soit les couches visualisées sur la carte.
Il pourrait afficher sous forme de liste aussi les POI des autres couches.


> @pyrog mais en fait le bouton sera le même que sur la liste des notes…

Oui je m'en doute. Mais suivant sa position et son libellé, l'utilisateur va comprendre que c'est :
- soit la liste de **tous les POIs**
- soit **uniquement** la liste **des notes**

Peux-tu bricoler stp une "copie" d'écran ?

**Comment by pyrog** [comment]
> >Que signifie exactement Prêt à intégrer ?`
>
> Cela signifie que la note a été créée sur pdm.fr et qu'en conséquence on a la **bonne géoloc** et les **méta-données** pour pré-remplir le formulaire qui ne demande qu'à être validé par l'utilisateur.

J'ai créé des notes depuis PdM à partir d'articles de presse. Bien souvent j'ai mis une position approximative (le centre du village…)

Il y a donc dans la note des paires clés/valeurs (des tags).

Est-ce que ce filtre détecte toutes les notes contenant des tags ? (quelquefois l'éditeur utilisé)
Ou uniquement les notes créées avec PdM ?

Dans le second cas, le texte _"Plus d'infos sur la résolution de cette note…"_ n'est pas très utile.
La note pourrait être remise en forme pour faciliter sa lecture :
<img width="33%" valign=top alt="Note créée avec PdM" src="https://user-images.githubusercontent.com/2158081/96836284-08ed4b00-1445-11eb-9b59-532cfd9d3e32.png"> <img width="33%" valign=top alt="Note reformatted" src="https://user-images.githubusercontent.com/2158081/96838334-0f30f680-1448-11eb-902f-3d7507416de3.png">



> Quel terme utiliser pour cela ? "prêt à intégrer" me paraissait clair jusqu'à présent.

**Comment by PanierAvide** [comment]
Je viens de faire une mise à jour, toujours en test donc pas de lien depuis la carte :
- Affichage des notes avec un alignement par le haut ligne par ligne
- Gestion des photos qui viennent de Wikimedia Commons et Mapillary (uniquement si leur adresse ressemble à un lien)
- Les filtres de la barre latérale sont affichés sur le même modèle que les badges
- Le texte de la note est raccourci des "via projet du mois" et autres, les hashtags sont affichés s'ils sont dans le texte de la note elle-même
- Les notes sont triées par date du commentaire le plus récent

**Comment by PanierAvide** [comment]
Pas de nouvelles = bonne nouvelle ? En tout cas c'est désormais en prod :grin:

**Comment by pyrog** [comment]
Premier retours 

La paire de boutons Carte/Liste est clair 😃 

Le filtrage géographique l'est moins  😞 

1. Depuis la carte je visualise par exemple 7 POIs
  * La couche orange est masquée
  * Localisation à [Lons-le-Saunier<br /><img width="33%" alt="Capture d’écran 2020-10-24 à 11 19 08" src="https://user-images.githubusercontent.com/2158081/97078216-c82f3680-15ea-11eb-9477-cb3b1f4f1fea.png">](https://projetdumois.fr/projects/2020-09_aed/map#map=14.75/46.67325/5.52672) 
2. J'affiche la liste :
  * L'intégralité des notes est affiché (pas de filtre géographique)
  * Les autres couches visibles ne sont pas affichées
  * Note : afficher le nombre de POIs listé serait utile 😃 
3. Je repasse en carte
  * La position et le zoom sont perdus  (la carte se positionne sur ma position GPS)
  * Le filtrage est perdu (affiche à nouveau la couche orange alors quelle était masquée)
