### ISSUE TITLE
Changer le libellé de validation du formulaire

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#86]
Actuellement, il est écrit "éditer" en bas du formulaire :
![image](https://user-images.githubusercontent.com/11553211/95559667-68e0fc00-0a18-11eb-994f-9c97bd13b21e.png)

J'ai l'impression que ce n'est pas le bon verbe d'action.
Je propose de changer pour "valider" avec la même icône que pour le bouton "valider" lorsque l'on change la position d'un POI.
Ou alors sinon : "envoyer"

**Comment by overflorian** [comment]
Concernant le positionnement des boutons, j'ai l'impression que l'action principale (ou l'action "active") est toujours placé à droite.
Peut-être voudrions-nous toujours placer le bouton ANNULER à gauche ?

Je n'ai pas trouvé confirmation ([même pas sur cette page](https://material.io/design/communication/confirmation-acknowledgement.html#usage)) de cette intuition donc c'est plutôt une question ouverte : qu'en pensez-vous ?

**Comment by PanierAvide** [comment]
Justement ça m'a toujours perturbé sur les interfaces Material design que le bouton d'action soit à gauche, historiquement c'est plutôt le contraire, exemple https://www.askvg.com/how-to-enable-disable-new-xp-style-welcome-screen-log-off-and-shutdown-dialog-box-in-windows-xp/ (#référenceDatée)

**Comment by PanierAvide** [comment]
Le bouton éditer a été changé, si on ne modifie pas l'ordre des boutons le ticket peut être fermé.

**Comment by overflorian** [comment]
ok
