### ISSUE TITLE
Logo "tu veux ma photo"

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#88]
OK j'ai fait quelques essais de logo pour _tu veux ma photo_.
Je suis déçu par toutes mes tentatives jusqu'à présent, mais je vous les envoie tout de même, ça vous donnera peut-être des idées pour m'aider dans mes prochains essais ...

![tuveuxmaphoto-logo-v1](https://user-images.githubusercontent.com/11553211/95678815-4d6c2180-0bcf-11eb-8b0b-a38e2ea2e07a.png)

![tuveuxmaphoto-logo-v5](https://user-images.githubusercontent.com/11553211/95678842-6b398680-0bcf-11eb-8a86-5ff72258a379.png)

![tuveuxmaphoto-logo-v2](https://user-images.githubusercontent.com/11553211/95678823-50ffa880-0bcf-11eb-96ba-191bafb252a8.png)

![tuveuxmaphoto-logo-v3](https://user-images.githubusercontent.com/11553211/95678827-52c96c00-0bcf-11eb-85c2-d01b782a7ba0.png)

![tuveuxmaphoto-logo-v4](https://user-images.githubusercontent.com/11553211/95678828-53fa9900-0bcf-11eb-8de4-5c80ba9d0937.png)

Fichier source édité sous Inkscape : [tuveuxmaphoto-logo.zip](https://github.com/vdct/ProjetDuMois/files/5361069/tuveuxmaphoto-logo.zip)

**Comment by PanierAvide** [comment]
Pourquoi pas quelque chose à base d'emojis ? Inspiration : :stuck_out_tongue_winking_eye: :camera:  :world_map:

**Comment by PanierAvide** [comment]
:earth_africa: :selfie: :smile:

**Comment by overflorian** [comment]
Toujours pas convaincu ^^
![tuveuxmaphoto-logo-v6](https://user-images.githubusercontent.com/11553211/95685764-2840d880-0bfa-11eb-96b3-7d2c3b1e814d.png)

**Comment by PanierAvide** [comment]
On me souffle à l'oreille l'idée du bonhomme du badge déficoeur qui tient un appareil photo.

**Comment by overflorian** [comment]
Bonne idée de garder une filiation graphique avec pdm. Je vais essayer ça

**Comment by overflorian** [comment]
ah ouais pas mal avec la fille :
![tuveuxmaphoto-logo-v7](https://user-images.githubusercontent.com/11553211/95687511-41e71d80-0c04-11eb-80a3-f5e24af01896.png)

**Comment by PanierAvide** [comment]
C'est sympa en effet :smile:

**Comment by overflorian** [comment]
Content que ça te plaise.
Dans ce cas partons sur la couleur majeure #7254a3 et la mineure #f16b86 https://material.io/resources/color/#!/?view.left=0&view.right=0&primary.color=7254a3&secondary.color=f16b86

**Comment by overflorian** [comment]
Je propose d'utiliser la même police d'écriture que pdm, c'est à dire "Suez One" :
![tuveuxmaphoto-logo](https://user-images.githubusercontent.com/11553211/95717648-878c0080-0c6d-11eb-8c55-dfa894d7fb46.png)
Tous les fichiers : [tuveuxmaphoto-logo.zip](https://github.com/vdct/ProjetDuMois/files/5363582/tuveuxmaphoto-logo.zip)

**Comment by gendy54** [comment]
J'aime ce logo mais ca fait un peu selfie d'ado, non?

**Comment by overflorian** [comment]
Alors c'est parfait. C'est notre cœur de cible cf. les personas https://github.com/vdct/ProjetDuMois/issues/66
