### ISSUE TITLE
La recherche par coordonnées n'est pas centrée

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#89]
Recherche de 48.8251317, 2.6090915…

<img width="50%" alt="Ecran décalé" src="https://user-images.githubusercontent.com/2158081/95710149-65d84c80-0c60-11eb-900c-3e475ffaf1ac.png">

… ne centre pas la carte sur les [coordonnées](https://projetdumois.fr/projects/2020-09_aed/map#map=18.1/48.825132/2.609092) saisis.

<img width="50%" alt="Ecran centré sur le POI" src="https://user-images.githubusercontent.com/2158081/95710152-67a21000-0c60-11eb-8d85-150a305c45cc.png">

**Comment by PanierAvide** [comment]
C'est un comportement lié à l'utilisation de Nominatim, qui recherche en pratique l'objet OSM le plus proche et centre sur lui.

**Comment by pyrog** [comment]
La solution est peut-être simple : ne pas faire de demande à Nominatim dans ce cas.

Concrètement si on détecte des coordonnées géographiques (avec une expression rationnelle) on modifie directement l'URL.
En plus ça permettrait de répondre quelque soit le séparateur : [48.825132 / 2.609092](https://projetdumois.fr/projects/2020-09_aed/map#map=18.1/48.825132/2.609092) ou [48.825132 , 2.609092](https://projetdumois.fr/projects/2020-09_aed/map#map=18.1/48.825132/2.609092)…
…voir même [&lat=48.825132&lon=2.609092](https://projetdumois.fr/projects/2020-09_aed/map#map=18.1/48.825132/2.609092).

Pour info, j'utilise ça très souvent en copiant collant des URL depuis d'autres site web.

**Comment by overflorian** [comment]
Je comprends la demande mais je pense qu'il y a vraiment peu de monde qui copie-colle des coordonnées géographiques. @pyrog tu peux directement modifier l'URL, ça marche bien.

**Comment by overflorian** [comment]
Pas d'update depuis octobre, je ferme ce ticket
