### ISSUE TITLE
Suggestions d'amélioration des données à l'utilisateur

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#9]
Après avoir un peu bossé sur les cinémas en particulier, voici une liste non-exhaustive des warnings que le projet du mois pourrait afficher aux utilisateurs pour un projet du type "mise en qualité des cinémas" :
- Les tags utilisés ne respectent pas les formatages de chaque marque définis dans https://nsi.guide (avec @gendy54 on y a spécifié de nombreuses chaînes de cinémas ces derniers temps)
_D'ailleurs, on pourrait imaginer des stats du type "32 cinémas UGC mappés dans OSM" sur cette base._
- Les tags sont similaires mais pas identiques à https://nsi.guide
_Par exemple brand=Pathe (au lieu de "Pathé")_
- Le "name" est manquant
- Le "name" contient le mot "cinéma" : 80% de chance que ça soit mal nommé
- Le code CNC n'est pas un nombre entier positif ou "no". Pareil pour les tags "screen" et "capacity".
- Il n'y a aucun code CNC (car on a décidé de rajouter ref:FR:CNC=no sur tous les cinémas non référencés par le CNC donc si un cinéma n'a pas la clef CNC alors il faut lui en rajouter une).
Dans l'idéal il y a une suggestion automatique et si ça matche, les valeurs du fichier CNC sont ajoutées : capacity, screen
- L'URL contient "UGC", alors "brand" a des chances d'être UGC. Pareil pour les autres marques.
Sur cette base on pourrait suggérer des tags à partir d'autres tags. C'est à réfléchir pour chaque projet du mois, et potentiellement, ce sont des règles à écrire DURANT le projet du mois car on les découvre au fur-et-à-mesure.
- wheelchair n'est pas limited/no/yes, 90% de chance que ça soit une erreur
- opening_hours est mal formaté (ça arrive tout le temps !) suggérer le bon formatage ou à défaut renvoyer vers Yo hours.
- Le numéro de téléphone est mal formaté
- L'URL est mal formaté
- L'URL de la page facebook est mal formaté (par exemple s'il est à l'ancien format cf. https://github.com/osm-fr/osmose-backend/issues/901)
- wikidata n'est pas un nombre entier positif précédé de "Q"
- Le SIRET n'est pas un nombre entier positif de 14 caractères
- open_air n'est pas no ou yes. Pareil pour drive_in, cinema3d

J'imagine que Osmose est le bon endroit pour coder la plupart de ces idées. D'après vous, y en aurait-il néanmoins pour lesquels Osmose ne soit pas adapté ?
Maintenant il faut aussi réfléchir aux alertes spécifiques aux cinés et celles qui seraient réutilisables pour d'autres sujets.

**Comment by overflorian** [comment]
J'ai aussi :
- fee n'est pas de la valeur "yes", "no" ou un horaire d'ouverture conforme à opening_hours
Use case : les personnes qui se trompent en utilisant "fee" à la place de "charge"
- charge n'est pas un chiffre positif avec ou sans "€" à la fin (ou au début, ce n'est pas spécifié dans la doc du wiki bizarrement)

**Comment by nlehuby** [comment]
Je dirais qu'Osmose se prête assez bien à ce genre de chose mais je vois quand même une difficulté pour les erreurs génériques (par exemple le format du tag wikidata ou les valeurs possibles de wheelchair) :
On peut facilement récupérer d'Osmose tous les objets avec un numéro de tel mal formaté, mais récupérer tous les cinémas avec un numéro de tel mal formaté est plus chiant (ou bien on récupère toutes les erreurs d'Osmose et on filtre ensuite pour ne garder que les cinémas, ou bien on récupère d'abord tous les cinémas via une autre source type Overpass puis on appelle ensuite Osmose sur chaque cinéma pour avoir ses erreurs)

Mais beaucoup de ces erreurs peuvent être détectées avec Overpass et pourraient aussi (plutôt ?) faire de bons challenges MapRoulette (plus jetable, mais plus rapide à mettre en place)

**Comment by overflorian** [comment]
OK merci pour les précisions techniques, j'ai l'impression que ce n'est rien d'insurmontable pour les machines que vous êtes ;)

Ta réflexion est bonne et dépasse le cadre de ce bug : on a plusieurs outils : MapRoulette, Osmose, mix-n-match, ... utiles que l'on ne souhaite pas redévelopper. Comment faire pour les goupiller au mieux et avoir une vison d'ensemble depuis le site du projet du mois.

**Comment by PanierAvide** [comment]
Je ferme le ticket, le sujet mérite réflexion mais ce sera plus simple à décliner avec un prochain projet du mois orienté montée en qualité de données existantes. Pas mal des points pourraient être résolus par des analyses MapCSS dans Osmose ou requêtes SQL à décliner côté PDM.fr.
