### ISSUE TITLE
Leçon de gamificiation de Pokemon Go

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#90]
J'ai testé Pokemon Go pour vous, et j'ai écumé les articles qui décryptent son mécanisme de gamification.
Je pense qu'on peut l'utiliser pour gamifier _tu veux ma photo_, sûrement pour une V2 ou V3.
![image](https://user-images.githubusercontent.com/11553211/95723295-47c91700-0c75-11eb-8cfd-65aad8899c38.png)

Voici ce qui en ressort :

# Retour sur expérience
Le but du jeu est de capturer des Pokémons qui apparaissent de manière aléatoire sur la carte, puis de les faire s'affronter dans un arène contre une IA ou un autre utilisateur. Le but est de collectionner un max de pokémon : le jeu n'est jamais "fini".
Le jeu est avant tout centré sur la carte mais de très très nombreux sous-menus permettent de gérer les personnages, les items et les relations entre joueurs.

1. A tout moment il est possible d'interrompre l'expérience pour qu'un personnage EXPLIQUE ce qui est en train de se passer :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95729115-ae056800-0c7c-11eb-9d46-987d59ddd5c2.jpg">
Les phrases sont très courtes. Un clic/tap sur l'écran fait apparaître la phrase suivante.

2. Quand on atteint un objectif principal (attraper un pokémon), on peut chopper des points en ayant atteint plusieurs sous-objectifs :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95729202-d4c39e80-0c7c-11eb-880d-b2ea6034855f.jpg">

3. On peut rajouter des amis (réels) ou des amis Pokémon. Le niveau d'interaction définit un "niveau d'amitié" noté de 1 à 4 cœurs :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95730000-f709ec00-0c7d-11eb-86f1-3d8f6965240c.jpg"> <img width="30%" src="https://user-images.githubusercontent.com/11553211/95740708-4efc1f00-0c8d-11eb-8bab-23c3248d8de2.jpg">
L'interaction avec les amis peut bénéficier de "bonus" qui augmente la vitesse à laquelle la relation "passe des niveaux".

4. Sur la carte, un utilisateur peut laisser un "check-point" photographique _(user generated content)_ :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95730257-4c45fd80-0c7e-11eb-8a71-3c8baeda23e9.jpg"> <img width="30%" src="https://user-images.githubusercontent.com/11553211/95730451-8e6f3f00-0c7e-11eb-90be-ffb3d66d7a29.jpg">
Ici par exemple une plaque commémorative peut-être "visitée" par un autre utilisateur qui choppe par ce fait des points.
Il n'est possible de rajouter des "checkpoints" que si l'on a atteint un certain niveau (ce n'est donc pas ouvert aux débutants). 

5. Une liste de checkpoints / POIs à checker aux alentours est dispo :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95730522-a5ae2c80-0c7e-11eb-8d8d-08ef6f352bd0.jpg">
Un clic sur un checkpoint l'affiche sur la carte

6. Une fonctionnalité "suivi de l'exploration" active un mode "tracking en permanence" qui autorise l'appli à suivre l'utilisateur même quand l'appli est active en fond de tâche. ça consomme sûrement beaucoup de batterie mais ça permet de gagner des points liés à la distance parcourue :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95739237-d09e7d80-0c8a-11eb-80d6-2ee87baedfc6.jpg"> <img width="30%" src="https://user-images.githubusercontent.com/11553211/95730704-e9089b00-0c7e-11eb-91c3-85e4bb5633e8.jpg">

7. Des fonctionnalités spéciales sont débloquées selon la météo :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95730767-ffaef200-0c7e-11eb-9480-d389022d41b0.jpg">

8. Des POI spéciaux apparaissent sur la carte : les arènes :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95737192-95e71600-0c87-11eb-8d4a-7b6eda7fac37.jpg">
On peut y faire des combats de pokémon. Le gagnant peut changer la couleur du POI : s'il est dans l'équipe bleue, le POI change pour cette couleur. C'est le même fonctionnement qu'un mode "capture de flag" dans Counter Strike.

9. L'avancement vers la quête finale et des sous-quêtes intermédiaires est transparente pour l'utilisateur dans un menu dédié :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95739871-c8930d80-0c8b-11eb-9862-d0e62918de66.jpg">

10. L'utilisateur a des explications TOUT LE TEMPS : ce qu'il a gagné, ce qu'il peut gagner, ce que gagner des points peut débloquer ...
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95739979-fd06c980-0c8b-11eb-89a4-498a602ebacb.jpg">

11. L'écran affichant les récompenses est en 2 sous-écrans : celui par défaut affiche 3 cœurs (résultats du jour) et l'autre les points totaux (cumul). C'est un moyen simple cacher la complexité tout ayant tout de même accès :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95740498-ec0a8800-0c8c-11eb-9bd0-63a5594327f7.gif">

# Articles
- https://elearningindustry.com/gamification-of-learning-learn-pokemon-go
1. la gamification, c'est très puissant pour impliquer les utilisateurs, mais ça ne plaît pas à tout le monde : on va perdre des utilisateurs dans l'histoire
2. l'effet "fun" ne fonctionne qu'un temps (2 semaines pour Pokemon Go)
Fidéliser l'utilisateur repose donc vraiment sur le long terme sur la relation parrain/filleul
3. la gamification, c'est marrant pour l'utilisateur, mais il faut faire attention à ce que ça ne parasite pas le mécanisme d'apprentissage : dans notre cas, l'objectif de le transformer à moyen terme en "vrai" contributeur OSM

- https://medium.com/@selfdrvn/powerful-gamification-lessons-from-pokemon-go-61950b49fe08
les rewards peuvent s'appliquer à l'objectif principal (créer des photos) mais aussi à des objectifs secondaires : distance parcourue (nécessite d'avoir accès au podomètre), profondeur des méta-données ajoutée sur une photo (un sticker utile rapporte plus de point qu'un sticker "fun")

Tous les mécanismes utilisés visent à inciter l'utilisateur au plus vite et le plus souvent possible : il doit penser que c'est "urgent et important" :
![image](https://user-images.githubusercontent.com/11553211/95730882-253bfb80-0c7f-11eb-8d50-a02bdb98e5c5.png)

# Mes propositions pour gamifier _tu veux ma photo_
1. Toute action positive de l'utilisateur doit lui rapporter des points.

1. bis. Le nombre de points gagnés est très élevé, et ce, dès le début. Par exemple :
  - Une action majeure (prendre une photo) rapporte 500 pts
  - Un action mineure (rajouter un sticker, commenter une photo, ...) rapporte 100 pts
  - Des sous-quêtes mineures (ouvrir l'outil 3 fois dans la même journée, ...) rapportent 200 points
  - Votre parrain qui créé de la donnée dans OSM grâce à votre photo : 400 points
  - Un autre utilisateur qui like une de vos photo rapporte 300 points

2. Les points permettent de passer des "niveaux".
Chaque niveau a un nom (flatteur pour l'utilisateur), par exemple 
  - niveau 1 : photographe averti
  - niveau 2 : collecteur appliqué
  - niveau 3 : cartographe de terrain
  - niveau 4 : enquêteur de talent
  - niveau 5 : sportif accompli
  - niveau 6 : reporter aguerri
  - niveau 7 : agent spécialiste
  - niveau 8 : explorateur sans peur et sans reproches
  - niveau 9 : expert total
  - niveau 10 : super-picturien

2. bis. Les récompenses sont directement indexées sur le passage des niveaux.

3. Il faut définir une "quête ultime" atteignable dans les 2 semaines pour un utilisateur assez impliqué : devenir un "super-picturien" de niveau 10.
La "quête ultime" est annoncée dès les premières utilisations pour fixer un objectif à l'utilisateur. Elle est accessible dans le profil utilisateur, que l'on pourrait appeler "carnet de terrain".

4. Cindy apparaît parfois pour donner des infos type "voici la quête ultime" ou "voici la prochaine quête mineure" ou "la prochaine fois, active la géoloc". Pour ça, on fait des variantes du logo avec Cindy :
![image](https://user-images.githubusercontent.com/11553211/95736837-122d2980-0c87-11eb-8499-0e67c1c33105.png)
Quand on gagne un sticker, il n'est pas accessible via une notif mais directement via un interstitiel qui disparaît en un clic.
Un peu comme ça :
<img width="30%" src="https://user-images.githubusercontent.com/11553211/95741193-20cb0f00-0c8e-11eb-8fc8-b27ccec62d99.jpg">
Cindy apparaît aussi pour détaillé l'usage qui sera fait avec les photos envoyées, présenter OSM, et inciter à devenir contributeur.

5. Il est important de gagner plus de points au début. Passer le niveau 1 est hyper facile mais passer du niveau 9 à 10 est très difficile. La relation entre points gagnés et niveaux passés pourrait par exemple être définie par une fonction [racine cubique](https://fr.wikipedia.org/wiki/Racine_cubique).
<img width="50%" src="https://user-images.githubusercontent.com/11553211/95732689-5fa69800-0c81-11eb-8e5c-d621c4e3d3fb.png">

6. Les passages de niveaux débloquent des cadeaux : 
  - stickers (qui apparaissent grisés tant qu'ils ne sont pas débloqués)
  - possibilité de choisir une team au niveau 5 (j'imagine simplement une importance symbolique, mais on peut envisager une fonctionnalité "capture the flag" _à la Pokémon Go_ dans le futur)
  - Autre (à réfléchir ...) : possibilité d'avoir soi-même des filleuls ? Possibilité d'avoir des quêtes pas uniquement liées au projets du mois en cours ou déjà réalisés ? Possibilité de créer des POIs sur une carte, visitables par d'autres utilisateurs ?
On devrait réfléchir à comment on transforme un simple photographe en vrai contributeur OSM à travers un cheminement initiatique fléché.

7. La gamification coté pdm peut être :
  - abandonnée, partant du principe qu'elle s'adresse aux noobs avant tout
  - renforcée, avec des points attribués grâce aux contributions des filleuls et éventuellement des points d'équipe

--
Je pense qu'avec tout ça, on est sur une bonne voie vers le respect des [règles de base de la gamification](https://blog.trello.com/fr/gamification-exemple), c'est à dire :
  -    Indiquer l’avancement de la tâche (barres de niveaux)
  -    Multiplier les objectifs de court et long terme (quête ultime et missions)
  -    Récompenser les efforts (or, butin et expérience)
  -    Donner du feedback de manière rapide, fréquente et claire (détails de l’activité sur l’écran: “Mission Accomplie!”)
  -    Créer de l’incertitude (butin et or difficiles à trouver)
  -    Interagir avec d’autres personnes (jeux multi-joueurs)

**Comment by gendy54** [comment]
P.tain t'es un gros malade!!!
Et du coup, on se rapprocherait plus d'une appli type Street Complete mais gamifié à mort, non?
Je ne sais pas si ca existe dans Pokemon Go, mais la possibilité de voir qui choppe des Pokemon autour de chez soi pour faire se rencontrer les contributeurs?

**Comment by overflorian** [comment]
Street complete est un éditeur OSM alors que tvmp est un outil de collecte photo. C'est assez différent. Néanmoins, tu as raison, on a eu la réflexion "quels sont les freins à la contribution dans street complete" et une grande conclusion est que la carte en elle-même est compliquée.
D'où l'idée d'avoir certaines personnes (les filleuls) qui prennent des photos et d'autres (les parrains) qui créent de la donnée propre dans OSM. 

Sinon, en effet dans Pokémon Go on peut rencontrer des utilisateurs à proximité, soit en les affrontant dans une arène, soit par plein d'autres moyens.
Pour tvmp, on peut envisager de booster la création de relations horizontales entre contributeurs, mais je pense que ça serait dans un second temps, si l'outil fonctionne bien pour remplir son premier objectif : créer une relation forte entre un filleul et son parrain.
Tout est pensé pour renforcer cette relation dans la première version : le parrain crée lui-même une invitation personnelle pour son filleul, il a des notifs quand le filleul contribue,...

**Comment by rouelibre1** [comment]
Géniale cette analyse ! 

Il peut être intéressant de regarder le replay du talk [Gamifying POI Data Colletion](https://www.youtube.com/watch?v=Vzb7w9UgKcQ) du State of the Map US 2019. 24 minutes de retour d'expérience qui valent le détour.

**Comment by overflorian** [comment]
Merci pour cette vidéo, elle est super !
Je note ici les points clefs que j'ai retenu de leur dispositif :
- c'est important de faire des applis mobiles Android/iOS
- leur challenge est limité dans le temps et focalisée sur une ville précise
- ils demandent de collecter un type de donnée / POI précis
- les rétributions sont importantes (plusieurs dizaines de milliers d'€) pour chaque challenge, payés en bitcoin
- il y a un nombre limité de "gagnants" : entre 50 et 100
- le système exige que le contributeur soit sur le terrain : à moins de 100m du POI pour créer la donnée, et exige également de prendre une photo
- le contributeur gagne des points _seulement_ si la donnée a été confirmée par 2 contributeurs (!)
- pour 1 POI, les détails sont toujours les mêmes : localisation, nom, catégorie, photo
- valider des données rapporte aussi des points
- il est important que les points délivrés le soient _en live_ : le leaderboard est en temps réel
- l'interaction par équipes, ça fonctionne bien
- ne pas trop se focaliser sur la protection de la vie privée, les gens veulent publier les résultats largement, utiliser les réseaux sociaux
- il est possible de télécharger ses propres données contribuées en tant qu'utilisateur
- il y a plein de badges cf. les screenshots https://play.google.com/store/apps/details?id=com.streetcred.mapnyc&hl=en_US

exemple : https://events.streetcred.co/mapaustin/
Quand la vidéo est sortie en 2019, ils envisageaient d'étendre le dispositif au Monde entier de manière permanente. A ce jour, l'appli n'est pas accessible sur le Play Store français.
