### ISSUE TITLE
Remerciements à la clôture du projet du mois

### ISSUE THREAD

**Issue by PanierAvide** [vdct/ProjetDuMois#92]
Ce serait bien d'avoir un affichage de remerciements / liste des contributeurs en nuage de mots / ... qui soit sympa à voir en juste retour au travail de la communauté pendant le projet du mois. Des idées @overflorian ?

**Comment by overflorian** [comment]
Aleeerte RGPD de mon coté ! De la même manière qu'on n'affiche les stats que pour les personnes loguées, on ne pourra afficher celles-là que pour les personnes loguées.
Mais sinon, je n'ai pas d'idée plus précise qu'un nuage de tag. Un nuage de tag c'est très bien, il y a plein de frameworks pour faire ça en plus.
La taille du pseudo serait proportionnelle au nombre de points peut-être ?

**Comment by overflorian** [comment]
A vrai dire, le mieux serait de faire un message personnalisé. Via la messagerie OSM peut-être ?

**Comment by pyrog** [comment]
> liste des contributeurs en nuage de mots

👍 

<img width="573" alt="Nuage pouce levé" src="https://user-images.githubusercontent.com/2158081/96234644-0056c980-0f9a-11eb-8c35-68b189d021cd.png">


Et aussi un nuage de mots avec les villes, départements où ont été faites les contributions

**Comment by pyrog** [comment]
Je n'ai pas trouvé de nuage animé 😢 

Ici j'ai supprimé les espaces, augmenté le poids des 4 premiers (de façon non linéaire) et utilisé https://github.com/jasondavies/d3-cloud
<img width="939" alt="Nuage" src="https://user-images.githubusercontent.com/2158081/96236209-05b51380-0f9c-11eb-925b-d63414a4a628.png">

**Comment by PanierAvide** [comment]
Je pense qu'il ne faut pas mettre autant en avant les contributeurs ayant le plus de points (on a déjà le podium pour ça). On pourrait même mettre tout le monde à la même taille, c'est tout autant intéressant de mettre en avant les petits/nouveaux contributeurs que les autres.

**Comment by pyrog** [comment]
👍  C'était seulement un essai à l'arrache. Je cherchais un nuage en 3D qui bouge…

**Comment by PanierAvide** [comment]
C'est ajouté, ce sera visible dès lundi :smile:
