### ISSUE TITLE
Afficher certaines statistiques sans être logué

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#93]
Quand un utilisateur n'est pas logué, on ne lui affiche aucune stat (https://github.com/vdct/ProjetDuMois/issues/30).

Pourtant on pourrait tout lui montrer sauf celles liées aux utilisateurs, c'est à dire les 6 chiffres clefs et les 3 graphiques. Qu'en pensez-vous ?
Si on fait ça je propose de laisser un espace vide à l'endroit où le podium s'affiche d'habitude et d'y mettre un bouton du type "s'identifier pour voir plus de stats"

**Comment by PanierAvide** [comment]
Hmm c'est déjà le cas en fait, ça donne ça quand on est déconnecté

![Capture d’écran_2020-10-17_18-44-06](https://user-images.githubusercontent.com/1349014/96348411-c58f8700-10a8-11eb-81b7-f707148caf1d.png)

Je ferme le ticket, à moins qu'il n'y ait d'autres stats à afficher.

**Comment by overflorian** [comment]
Ah ! Désolé, j'aurai dû vérifier.
