### ISSUE TITLE
Créer un compte "points OSM" universel

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#94]
Nouvelle idée (long terme, sûrement un projet différent du pdm) : créer un compte "points OSM" pour chaque contributeur OSM.

L'idée est de rendre interopérable (via [Open Badges](https://openbadgefactory.com/) ?) les mécanismes de gamification.
On pourrait imaginer que chaque compte OSM soit lié, sur demande de l'utilisateur, aux comptes :
https://projetdumois.fr/users/overflorian
http://www.missingmaps.org/users/#/overflorian/badges
http://streak.osmz.ru/user/overflorian
et tous les autres projets qui implémenteraient le "compte point" par la suite.

Dans l'idéal, ça apparaîtrait dans le compte utilisateur sur osm.org, mais on peut imaginer plus réalistiquement de créer un site web dédié.

**Comment by pyrog** [comment]
Ou de proposer à Pascal de les afficher dans [HDYC](https://hdyc.neis-one.org/?overflorian) ?

**Comment by overflorian** [comment]
Ah oui, tiens, bonne idée ça. Je vais commencer par le contacter pour lui proposer l'idée avant tout. Merci @pyrog

**Comment by PanierAvide** [comment]
Pas mal l'idée de les ajouter dans _How do you contribute_, ça me semble l'endroit tout indiqué pour ça :smile:

**Comment by nlehuby** [comment]
Pour info, il y a une discussion en ce moment sur la liste de la fondation sur les badges, les points, la ludification et les dérives que ça peut avoir : https://lists.openstreetmap.org/pipermail/osmf-talk/2020-October/007262.html

**Comment by PanierAvide** [comment]
Merci du lien. Ça vaut le coup de garder en tête ces dérives (traitement de masse sans grande réflexion des utilisateurs), mais à mon avis le plus grand péril auquel on peut être confronté c'est que ça ne serve à rien de faire ça...

**Comment by overflorian** [comment]
Voilà la réponse de Pascal :

```
"Badges" have been a topic for several years. E.g. see https://wiki.openstreetmap.org/wiki/Badges which you maybe already know.

However, similar as I do it with the OSM wiki, github or streak, if your website offers some kind of API, I could use it in HDYC.
I'm not sure if we really need some extra API for this.
I also utilized the HOTOSM API (v1) for getting some information, but it seems that they switched to v2 and now it didn't work anymore @ HDYC. Have to check this.

```

Est-ce qu'à ce point du projet on veut pousser plus loin et disposer d'une API pour utiliser les points dans d'autres projets comme _How do you contribute_ ou les éventuels projets discutés à la fondation ? That is the question my friends.

**Comment by PanierAvide** [comment]
Je sais pas si on _veut_, mais techniquement c'est sûr qu'on _peut_ et que ce serait probablement assez rapide à mettre en oeuvre.

**Comment by pyrog** [comment]
Pascal parle de la V1 de cette API https://tasks.hotosm.org/api-docs pour récupérer les badges de [Missing Maps](http://www.missingmaps.org/users/#/pyrog/badges) ?
En particulier de `/api/v2/users/{username}/statistics/` ?

**Comment by overflorian** [comment]
Sûrement oui. Ca te donne des idées ? ;)

**Comment by pyrog** [comment]
> Ca te donne des idées ? ;)

Oui, de se calquer sur leur API pour les badges 😉 
Comme ça Pascal pourra les afficher au côté de ceux de Missing Maps 😃

**Comment by PanierAvide** [comment]
Le mieux serait de demander à Pascal quelles sont les infos dont il a besoin et comment il préfèrerait les récupérer. En sachant qu'on peut fournir pour chaque utilisateur :
- La liste des badges acquis (nom, URL de l'image)
- Le nombre de points par projet du mois
- La nature des modifications réalisées (ajout, édition, suppression, création de notes)

**Comment by pyrog** [comment]
Leur système est simple :
- La catégorie correspond au badge,
- Chaque badge à 3 niveaux,
- un dessin par niveau.

<img width="33%" alt="Capture d’écran 2020-10-22 à 16 41 00" src="https://user-images.githubusercontent.com/2158081/96887937-60aba680-1485-11eb-872e-40103210aebd.png">


Badge|level 1|2|3
--|--|--|--
Long and Winding Road|  ![1](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/7-1-graphic.svg) | ![2](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/7-2-graphic.svg)| ![3](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/7-3-graphic.svg)
Awesome JOSM|  ![1](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/12-1-graphic.svg) | ![2](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/12-2-graphic.svg)| ![3](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/12-3-graphic.svg)
Whitewater Rafting|  ![1](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/8-1-graphic.svg) | ![2](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/8-2-graphic.svg)| ![3](https://raw.githubusercontent.com/MissingMaps/users/master/assets/graphics/badges/8-3-graphic.svg)

Dans PdM on a :
- Un projet = `category`
- Le classement = `level`
- Les points = `score` (a ajouter dans la structure de données)
- Le badge est représenté avec le dessin du niveau le plus élevé

Mais aussi des badges transversaux calqués sur les badges de Missing Maps.
On pourrait ajouter un badge concernant les ajout de photos…

category|Projet
--|--
2020-09_aed|Défibrillateurs
2020-03_evcharging|Recharge de véhicules électriques
2018-07_substation|Postes électriques

level|Classement
--|--
0|Hors classement
1|Troisième
2|Second
3|Premier

**Comment by PanierAvide** [comment]
Je vois pas trop comment on peut avancer sur le sujet :
- Intégration dans HDYC : pdm.fr reste un outil national, pas trop de sens
- Compte point universel : on en est pas là, et pas forcément envie d'être leader sur le sujet (on ne peut pas être partout)

Je ferme le ticket.
