### ISSUE TITLE
Mix de traduction

### ISSUE THREAD

**Issue by frodrigo** [vdct/ProjetDuMois#95]
![imagen](https://user-images.githubusercontent.com/1785486/96348584-35ead800-10aa-11eb-91e6-5fad2c8c8d06.png)

Français et espagnol mélangé.
Mon Firefox est en espagnol, mais a le français configuré comme langue préféré pour le contenu web.

**Comment by PanierAvide** [comment]
Sympa comme bug :grin:  Je vais regarder ça

**Comment by PanierAvide** [comment]
C'est corrigé, merci du signalement :+1:
