### ISSUE TITLE
Détecter les mots clefs dans les notes

### ISSUE THREAD

**Issue by overflorian** [vdct/ProjetDuMois#96]
Je viens de fermer cette note https://www.openstreetmap.org/note/2317947
jusqu'à présent elle ne remontait pas dans pdm car elle n'avait pas le bon hashtag. Peut-être que le mot clef "défibrillateur" aurait pu être détecté automatiquement ?
autres mots-clefs : DAE, défibrilateur (avec la faute d'orthographe), defibrilateur, defibrillateur

**Comment by PanierAvide** [comment]
C'est déjà sensé être le cas, voir https://github.com/vdct/ProjetDuMois/blob/master/projects/2020-09_aed/info.json#L44

Le problème ici doit être plus subtil que ça, ce serait bien de trouver une autre note dans le même genre encore ouverte et qui ne ressort pas pour pouvoir investiguer.

**Comment by pyrog** [comment]
La [note 2317947](https://www.openstreetmap.org/note/2317947) est bien détectée.

Je sais que l'API ne distingue pas les mots `défibrillateur` et `defibrillateur`.
Par contre elle est insensible à la casse `Défibrillateur` et trouvé au même titre que `défibrillateur`.

**Comment by PanierAvide** [comment]
Là dans le code les deux versions avec et sans accents sont bien recherchées. Le bug est sûrement encore plus subtil :stuck_out_tongue:

**Comment by PanierAvide** [comment]
Bon comme c'est pas clair, je ferme le ticket et on ré-ouvrira si le cas se présente à nouveau.
