### ISSUE TITLE
Uncaught SyntaxError: expected expression, got ')' (firefox 81.0.2)

### ISSUE THREAD

**Issue by Shnoulle** [vdct/ProjetDuMois#97]
Sur https://projetdumois.fr/projects/2020-09_aed/map#map=16.16/50.697934/3.157439 

Tout me semble vide dès que je zoom.

Sur la console : 1ere erreur
`Uncaught SyntaxError: expected expression, got ')' map:1669:5`

Et oui, cela à l'air d'être un peu court en tous cas pour firefox 81.0.2
```
function addContribution(type) {
	// Old project : show nothing specific
	if(!) {
		postContribBadgesDom.classList.add("d-none");
	}
```

Ensuite, j'ai pas mal de problème avec `Cross-Origin Request`

![Capture d’écran du 2020-10-19 11-56-20](https://user-images.githubusercontent.com/1439428/96430168-1ff02b00-1202-11eb-8a64-54a5980dfdc2.png)

**Comment by PanierAvide** [comment]
Merci du signalement, c'est réglé :+1:

**Comment by Shnoulle** [comment]
Merci ! PrivacyBadger vous aime pas … je sais pas si on peut faire comme sur UBlock des listes blanches générales …

**Comment by PanierAvide** [comment]
Il faut autoriser tout ce qui est en *.projetdumois.fr et *.openstreetmap.fr, on a pas d'autres ressources mobilisées pour l'instant (sauf peut-être dans la feuille de style vectorielle ?).

**Comment by Shnoulle** [comment]
C'est pas le soucis ici, j'ai pas remonté :).

C'est plus une info .
Je sais pas si il serait possible de valider le https://www.eff.org/dnt-policy . Pas pris le temps de regarder (et je ne remonterais pas ici ;) )
![Capture d’écran du 2020-10-19 13-09-08](https://user-images.githubusercontent.com/1439428/96443121-66e31e00-120c-11eb-9d4f-36b17b168f10.png)
