### ISSUE TITLE
Le bouton Afficher / Masquer l'image satellite ne répond plus…

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#98]
## Comment reproduire le problème

1. Charger la [page](https://projetdumois.fr/projects/2020-09_aed/map#map=19.5/46.7475297/5.910011)
1. Cliquer sur le bouton : l'image satellite s'affiche
1. Cliquer sur le bouton : la carte vectorielle s'affiche
1. Cliquer sur le bouton : plus d'effet

## Informations complémentaires 

Testé avec **Firefox** et **Safari**

**Comment by PanierAvide** [comment]
Je viens de tester avec les dernières version de Chromium et Firefox, je n'arrive pas à reproduire ce bug. Est-ce qu'il y a un message dans la console web du navigateur ?

**Comment by pyrog** [comment]
ça ne se produit pas systématiquement au bout de 3 clicks.
J'ai reproduit le bug, puis impossible à reproduire ⁉️ 

Pas de message particulier à part :
```
Failed to load resource: the server responded with a status of 404 () https://proxy-ign.openstreetmap.fr/94GjiyqD/bdortho/20/541500/369886.jpg
```

**Comment by PanierAvide** [comment]
Ça ressemble plutôt à une indisponibilité temporaire du service de tuiles, donc pas lié à projetdumois.fr. Je ferme le ticket mais si ça se reproduit il faudra en parler aux personnes qui gèrent ça (Christian ?).

**Comment by pyrog** [comment]
J'ai re testé avec Firefox, c'est aléatoire.

En cliquant, l'attribution change systématiquement, mais pas les tuiles.

> Ça ressemble plutôt à une indisponibilité temporaire du service de tuiles

Certes, mais sans changer ni de position ni de zoom, cela se reproduit.
Il y a probablement une exception. Mais indisponibilité ou pas, les tuiles en cache devraient être affichées.

**Comment by pyrog** [comment]
Merci Adrien pour la correction 😃
