### ISSUE TITLE
Style vectoriel et indoor mapping

### ISSUE THREAD

**Issue by pyrog** [vdct/ProjetDuMois#99]
@frodrigo Ce bâtiment contenant des polygones avec `indoor=*` n'est pas rendu.

[Oppidum](http://tile-vect.openstreetmap.fr/#map=18/46.74746/5.90972) (2 niveaux)
<img width="33%" alt="Vectoriel (2 niveaux)" src="https://user-images.githubusercontent.com/2158081/96546699-03f49400-12ab-11eb-8ca3-73321713c53f.png"> <img width="33%" alt="Bitmap" src="https://user-images.githubusercontent.com/2158081/96546714-0951de80-12ab-11eb-8dfd-cb01fde9d431.png"> 
<img width="33%" alt="indoor=" src="https://user-images.githubusercontent.com/2158081/96546973-96953300-12ab-11eb-855e-3dcf0d58c0a4.png">

### Bâtiments rendus
[Restaurant municipal](http://tile-vect.openstreetmap.fr/#map=18/46.682585/5.578748) (1 niveau)
<img width="33%" alt="Vectoriel (1 niveau)" src="https://user-images.githubusercontent.com/2158081/96547992-5cc52c00-12ad-11eb-9da9-e0cf161a55dd.png">

[Beffroi](http://tile-vect.openstreetmap.fr/#map=17.72/48.819625/2.319809) (2 niveaux)
<img width="33%" alt="Capture d’écran 2020-10-20 à 08 35 38" src="https://user-images.githubusercontent.com/2158081/96549063-3f915d00-12af-11eb-91f0-3307d3cf5e30.png">

**Comment by PanierAvide** [comment]
Ce n'est pas le dépôt du service de tuiles vectoriel ici :grin: Tu peux envoyer le ticket là bas : https://github.com/makina-maps/makina-maps/issues

**Comment by frodrigo** [comment]
Le server de tuile n'est pas non plus le dépôt du style et du schéma de données. Mais pour te la faire courte, il te faut aussi le version outdoor du batiment.
